/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AnnotationPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/annotationFile/AnnotationFileManager.ts
var import_obsidian = require("obsidian");

// src/constants.ts
var COLOR_MAP = {
  red: { bg: "rgba(255, 107, 107, 0.35)", border: "#ff6b6b" },
  blue: { bg: "rgba(84, 160, 255, 0.35)", border: "#54a0ff" },
  yellow: { bg: "rgba(255, 212, 59, 0.45)", border: "#ffd43b" },
  green: { bg: "rgba(38, 194, 129, 0.35)", border: "#26c281" },
  purple: { bg: "rgba(155, 89, 182, 0.35)", border: "#9b59b6" },
  none: { bg: "transparent", border: "#999" }
};
var PATH_SEPARATOR = "&.";

// src/utils/helpers.ts
function generateId() {
  return `${Date.now()}-${Math.random().toString(36).substring(2, 11)}`;
}
function notePathToAnnotationPath(pluginDir, notePath) {
  const normalizedPath = notePath.replace(/[/\\]/g, PATH_SEPARATOR);
  return `${pluginDir}/annotations/${normalizedPath}`;
}
function encodeAttr(str) {
  return str.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
function decodeAttr(str) {
  return str.replace(/&gt;/g, ">").replace(/&lt;/g, "<").replace(/&quot;/g, '"').replace(/&amp;/g, "&");
}

// src/annotationFile/annotationParser.ts
var MARK_REGEX = /<mark\s+([^>]*)>([\s\S]*?)<\/mark>/g;
var RUBY_REGEX = /<ruby\s+([^>]*)>([\s\S]*?)<\/ruby>/g;
function getAttr(attrs, name) {
  const regex = new RegExp(`${name}="([^"]*)"`, "i");
  const match = attrs.match(regex);
  return match ? match[1] : null;
}
function extractColorFromStyle(style) {
  for (const [color, { bg }] of Object.entries(COLOR_MAP)) {
    if (style.includes(bg)) {
      return color;
    }
  }
  return "yellow";
}
function parseRubyTags(content, parentAnnotationId) {
  const rubies = [];
  let match;
  RUBY_REGEX.lastIndex = 0;
  while ((match = RUBY_REGEX.exec(content)) !== null) {
    const rubyAttrs = match[1];
    const rubyContent = match[2];
    const rtMatch = rubyContent.match(/<rt[^>]*data-annotation-id="[^"]*"[^>]*>([\s\S]*?)<\/rt>/);
    const rtText = rtMatch ? rtMatch[1] : "";
    const spanMatch = rubyContent.match(/<span[^>]*data-annotation-id="[^"]*"[^>]*>([\s\S]*?)<\/span>/);
    const spanText = spanMatch ? spanMatch[1] : "";
    if (spanText && rtText) {
      const beforeRuby = content.substring(0, match.index);
      const plainBefore = stripTags(beforeRuby);
      rubies.push({
        startIndex: plainBefore.length,
        length: spanText.length,
        ruby: rtText
      });
    }
  }
  return rubies;
}
function stripTags(html) {
  return html.replace(/<[^>]+>/g, "");
}
function stripAnnotationTags(content) {
  let result = content.replace(
    /<ruby\s+[^>]*><span\s+[^>]*>([\s\S]*?)<\/span><rt\s+[^>]*>([\s\S]*?)<\/rt><\/ruby>/g,
    "$1"
  );
  result = result.replace(/<mark\s+[^>]*>([\s\S]*?)<\/mark>/g, "$1");
  return result;
}
function parseAnnotations(content) {
  const annotations = [];
  let match;
  MARK_REGEX.lastIndex = 0;
  while ((match = MARK_REGEX.exec(content)) !== null) {
    const attrs = match[1];
    const innerContent = match[2];
    const fullMatch = match[0];
    const startIndex = match.index;
    const id = getAttr(attrs, "data-annotation-id");
    if (!id) continue;
    const style = getAttr(attrs, "style") || "";
    const color = extractColorFromStyle(style);
    const note = decodeAttr(getAttr(attrs, "data-annotation-note") || "");
    const createdAt = getAttr(attrs, "data-annotation-created") || (/* @__PURE__ */ new Date()).toISOString();
    const text = stripTags(innerContent);
    const rubyTexts = parseRubyTags(innerContent, id);
    annotations.push({
      id,
      color,
      note,
      text,
      rubyTexts,
      createdAt,
      position: {
        start: startIndex,
        end: startIndex + fullMatch.length
      }
    });
  }
  return annotations;
}

// src/annotationFile/annotationSerializer.ts
function buildRubyTag(annotationId, text, ruby) {
  return `<ruby data-annotation-id="${annotationId}"><span data-annotation-id="${annotationId}">${text}</span><rt data-annotation-id="${annotationId}">${ruby}</rt></ruby>`;
}
function buildAnnotatedText(text, annotationId, rubyTexts) {
  if (!rubyTexts || rubyTexts.length === 0) return text;
  const sorted = [...rubyTexts].sort((a, b) => b.startIndex - a.startIndex);
  let result = text;
  for (const ruby of sorted) {
    const before = result.substring(0, ruby.startIndex);
    const target = result.substring(ruby.startIndex, ruby.startIndex + ruby.length);
    const after = result.substring(ruby.startIndex + ruby.length);
    result = before + buildRubyTag(annotationId, target, ruby.ruby) + after;
  }
  return result;
}
function buildMarkTag(id, text, color, note, rubyTexts, createdAt) {
  const bg = COLOR_MAP[color].bg;
  const created = createdAt || (/* @__PURE__ */ new Date()).toISOString();
  const noteAttr = note ? ` data-annotation-note="${encodeAttr(note)}"` : "";
  const annotatedText = buildAnnotatedText(text, id, rubyTexts);
  return `<mark style="background:${bg}" data-annotation-id="${id}" data-annotation-color="${color}"${noteAttr} data-annotation-created="${created}">${annotatedText}</mark>`;
}
function insertAnnotation(content, annotation) {
  const id = generateId();
  const tag = buildMarkTag(id, annotation.text, annotation.color, annotation.note, annotation.rubyTexts);
  const before = content.substring(0, annotation.position.start);
  const after = content.substring(annotation.position.end);
  return {
    content: before + tag + after,
    id
  };
}
function removeAnnotationTag(content, annotationId) {
  const regex = new RegExp(
    `<mark\\s+[^>]*data-annotation-id="${annotationId}"[^>]*>([\\s\\S]*?)<\\/mark>`,
    "g"
  );
  return content.replace(regex, "$1");
}
function updateAnnotationTag(content, annotationId, updates) {
  const regex = new RegExp(
    `(<mark\\s+)([^>]*data-annotation-id="${annotationId}"[^>]*)(>)([\\s\\S]*?)(<\\/mark>)`,
    "g"
  );
  return content.replace(regex, (_match, prefix, attrs, open, innerContent, close) => {
    let newAttrs = attrs;
    if (updates.color) {
      const bg = COLOR_MAP[updates.color].bg;
      newAttrs = newAttrs.replace(
        /style="background:[^"]*"/,
        `style="background:${bg}"`
      );
      newAttrs = newAttrs.replace(
        /data-annotation-color="[^"]*"/,
        `data-annotation-color="${updates.color}"`
      );
    }
    if (updates.note !== void 0) {
      if (updates.note) {
        if (newAttrs.includes("data-annotation-note=")) {
          newAttrs = newAttrs.replace(
            /data-annotation-note="[^"]*"/,
            `data-annotation-note="${encodeAttr(updates.note)}"`
          );
        } else {
          newAttrs += ` data-annotation-note="${encodeAttr(updates.note)}"`;
        }
      } else {
        newAttrs = newAttrs.replace(/\s*data-annotation-note="[^"]*"/, "");
      }
    }
    if (updates.rubyTexts !== void 0) {
      const plainText = innerContent.replace(/<ruby\s+[^>]*>[\s\S]*?<\/ruby>/g, (rubyMatch) => {
        const spanMatch = rubyMatch.match(/<span\s+[^>]*>([\s\S]*?)<\/span>/);
        return spanMatch ? spanMatch[1] : "";
      });
      const newInnerContent = buildAnnotatedText(plainText, annotationId, updates.rubyTexts);
      return `${prefix}${newAttrs}${open}${newInnerContent}${close}`;
    }
    return `${prefix}${newAttrs}${open}${innerContent}${close}`;
  });
}

// src/annotationFile/AnnotationFileManager.ts
var AnnotationFileManager = class {
  constructor(app, pluginDir) {
    this.app = app;
    this.pluginDir = pluginDir;
  }
  // 获取标注文件路径
  getAnnotationFilePath(notePath) {
    return notePathToAnnotationPath(this.pluginDir, notePath);
  }
  // 检查标注文件是否存在
  async hasAnnotationFile(notePath) {
    const path = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(notePath));
    return this.app.vault.adapter.exists(path);
  }
  // 确保标注文件存在（不存在则从原文件复制创建）
  async ensureAnnotationFile(notePath) {
    const annotationPath = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(notePath));
    if (await this.app.vault.adapter.exists(annotationPath)) {
      await this.syncFromOriginal(notePath);
      return true;
    }
    const originalFile = this.app.vault.getAbstractFileByPath(notePath);
    if (!(originalFile instanceof import_obsidian.TFile)) return false;
    const content = await this.app.vault.read(originalFile);
    const dir = annotationPath.substring(0, annotationPath.lastIndexOf("/"));
    if (dir && !await this.app.vault.adapter.exists(dir)) {
      await this.app.vault.adapter.mkdir(dir);
    }
    await this.app.vault.adapter.write(annotationPath, content);
    return true;
  }
  // 读取标注文件内容
  async readAnnotationFile(notePath) {
    const annotationPath = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(notePath));
    return this.app.vault.adapter.read(annotationPath);
  }
  // 写入标注文件内容
  async writeAnnotationFile(notePath, content) {
    const annotationPath = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(notePath));
    await this.app.vault.adapter.write(annotationPath, content);
  }
  // 同步原文件更新到标注文件
  async syncFromOriginal(notePath) {
    const file = this.app.vault.getAbstractFileByPath(notePath);
    if (!(file instanceof import_obsidian.TFile)) return;
    const originalContent = await this.app.vault.read(file);
    const annotatedContent = await this.readAnnotationFile(notePath);
    const strippedContent = stripAnnotationTags(annotatedContent);
    if (strippedContent === originalContent) return;
    const syncedContent = this.simpleSync(originalContent, annotatedContent, strippedContent);
    await this.writeAnnotationFile(notePath, syncedContent);
  }
  simpleSync(originalContent, annotatedContent, strippedContent) {
    if (!originalContent || !annotatedContent) return originalContent;
    const segments = this.buildContentMap(annotatedContent);
    const stripped = segments.filter((s) => !s.isTag).map((s) => s.text).join("");
    if (stripped === originalContent) return annotatedContent;
    return annotatedContent;
  }
  buildContentMap(content) {
    const segments = [];
    const tagRegex = /<(?:mark|ruby|rt|span)\s+[^>]*data-annotation-id="[^"]*"[^>]*>|<\/(?:mark|ruby|rt|span)>/g;
    let lastIndex = 0;
    let match;
    while ((match = tagRegex.exec(content)) !== null) {
      if (match.index > lastIndex) {
        segments.push({ text: content.substring(lastIndex, match.index), isTag: false, offset: lastIndex });
      }
      segments.push({ text: match[0], isTag: true, offset: match.index });
      lastIndex = tagRegex.lastIndex;
    }
    if (lastIndex < content.length) {
      segments.push({ text: content.substring(lastIndex), isTag: false, offset: lastIndex });
    }
    return segments;
  }
  // 同步标注文件编辑回原文件
  async syncToOriginal(notePath) {
    const file = this.app.vault.getAbstractFileByPath(notePath);
    if (!(file instanceof import_obsidian.TFile)) return;
    const annotatedContent = await this.readAnnotationFile(notePath);
    const pureContent = stripAnnotationTags(annotatedContent);
    const currentContent = await this.app.vault.read(file);
    if (currentContent !== pureContent) {
      await this.app.vault.modify(file, pureContent);
    }
  }
  // 文件重命名时迁移标注文件
  async migrateAnnotationFile(oldPath, newPath) {
    const oldAnnotationPath = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(oldPath));
    if (!await this.app.vault.adapter.exists(oldAnnotationPath)) return;
    const content = await this.app.vault.adapter.read(oldAnnotationPath);
    const newAnnotationPath = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(newPath));
    const dir = newAnnotationPath.substring(0, newAnnotationPath.lastIndexOf("/"));
    if (dir && !await this.app.vault.adapter.exists(dir)) {
      await this.app.vault.adapter.mkdir(dir);
    }
    await this.app.vault.adapter.write(newAnnotationPath, content);
    await this.app.vault.adapter.remove(oldAnnotationPath);
    await this.cleanupEmptyDirs(oldAnnotationPath);
  }
  // 文件删除时清理标注文件
  async deleteAnnotationFile(notePath) {
    const annotationPath = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(notePath));
    if (await this.app.vault.adapter.exists(annotationPath)) {
      await this.app.vault.adapter.remove(annotationPath);
      await this.cleanupEmptyDirs(annotationPath);
    }
  }
  // 清理空的父目录
  async cleanupEmptyDirs(filePath) {
    const annotationsDir = (0, import_obsidian.normalizePath)(`${this.pluginDir}/annotations`);
    let dir = filePath.substring(0, filePath.lastIndexOf("/"));
    while (dir.length > annotationsDir.length) {
      if (!await this.app.vault.adapter.exists(dir)) break;
      const listed = await this.app.vault.adapter.list(dir);
      if (listed.files.length > 0 || listed.folders.length > 0) break;
      await this.app.vault.adapter.rmdir(dir, false);
      dir = dir.substring(0, dir.lastIndexOf("/"));
    }
  }
  // 解析标注文件中的所有标注
  async getAnnotations(notePath) {
    const content = await this.readAnnotationFile(notePath);
    return parseAnnotations(content);
  }
  // 添加标注
  async addAnnotation(notePath, annotation) {
    const content = await this.readAnnotationFile(notePath);
    const { content: newContent, id } = insertAnnotation(content, annotation);
    await this.writeAnnotationFile(notePath, newContent);
    const result = parseAnnotations(newContent).find((a) => a.id === id);
    return result;
  }
  // 删除标注
  async removeAnnotation(notePath, annotationId) {
    const content = await this.readAnnotationFile(notePath);
    const newContent = removeAnnotationTag(content, annotationId);
    await this.writeAnnotationFile(notePath, newContent);
  }
  // 更新标注
  async updateAnnotation(notePath, annotationId, updates) {
    const content = await this.readAnnotationFile(notePath);
    const newContent = updateAnnotationTag(content, annotationId, updates);
    await this.writeAnnotationFile(notePath, newContent);
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  defaultColor: "yellow",
  maxNoteLength: 500
};

// src/main.ts
var AnnotationPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    // 原始文件路径 → 标注文件路径的映射
    this.activeAnnotationSessions = /* @__PURE__ */ new Map();
  }
  async onload() {
    var _a;
    await this.loadSettings();
    const pluginDir = (_a = this.manifest.dir) != null ? _a : ".obsidian/plugins/obsidian-annotation-marker";
    this.fileManager = new AnnotationFileManager(this.app, pluginDir);
    this.registerEvents();
    this.registerCommands();
    this.registerCacheListeners();
    this.addRibbonIcon("lucide-highlighter", "\u6807\u6CE8\u6A21\u5F0F", () => {
      this.toggleAnnotationView();
    });
  }
  onunload() {
    for (const [, annotationPath] of this.activeAnnotationSessions) {
      this.removeFakeTFile(annotationPath);
      this.removeMetadataCache(annotationPath);
    }
    this.activeAnnotationSessions.clear();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // 构造假 TFile 并注入 vault 的 fileMap
  createFakeTFile(path) {
    const vault = this.app.vault;
    const anyFile = vault.getFiles()[0];
    if (!anyFile) throw new Error("Vault is empty");
    const TFileConstructor = Object.getPrototypeOf(anyFile).constructor;
    const fakeFile = new TFileConstructor(vault, path);
    fakeFile.deleted = false;
    vault.fileMap[path] = fakeFile;
    return fakeFile;
  }
  // 从 vault.fileMap 中移除假文件
  removeFakeTFile(path) {
    delete this.app.vault.fileMap[path];
  }
  // 为标注文件注入原笔记的元数据缓存，使内部链接和大纲视图正常工作
  injectMetadataCache(annotationPath, originalPath, fakeTFile) {
    const cacheInternal = this.app.metadataCache;
    const originalCache = cacheInternal.metadataCache[originalPath];
    if (originalCache) {
      cacheInternal.metadataCache[annotationPath] = originalCache;
    }
    const originalFileCache = cacheInternal.fileCache[originalPath];
    if (originalFileCache) {
      cacheInternal.fileCache[annotationPath] = originalFileCache;
    }
    if (originalCache) {
      this.app.metadataCache.trigger("changed", fakeTFile, "", originalCache);
    }
  }
  // 清理标注文件的元数据缓存
  removeMetadataCache(annotationPath) {
    const cacheInternal = this.app.metadataCache;
    delete cacheInternal.metadataCache[annotationPath];
    delete cacheInternal.fileCache[annotationPath];
  }
  // 注册元数据缓存相关的全局事件监听
  registerCacheListeners() {
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor, info) => {
        var _a;
        const filePath = (_a = info.file) == null ? void 0 : _a.path;
        if (!filePath) return;
        const originalPath = this.getOriginalPathByAnnotationPath(filePath);
        if (originalPath) {
          this.injectMetadataCache(filePath, originalPath, info.file);
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        for (const [originalPath, annotationPath] of this.activeAnnotationSessions) {
          let isStillOpen = false;
          this.app.workspace.iterateAllLeaves((l) => {
            var _a, _b;
            if (((_b = (_a = l.view) == null ? void 0 : _a.file) == null ? void 0 : _b.path) === annotationPath) {
              isStillOpen = true;
            }
          });
          if (!isStillOpen) {
            this.removeFakeTFile(annotationPath);
            this.removeMetadataCache(annotationPath);
            this.activeAnnotationSessions.delete(originalPath);
          }
        }
      })
    );
  }
  // 获取当前视图的滚动位置
  getSavedScroll(leaf) {
    var _a;
    const view = leaf == null ? void 0 : leaf.view;
    if ((_a = view == null ? void 0 : view.currentMode) == null ? void 0 : _a.getScroll) {
      const scroll = view.currentMode.getScroll();
      return typeof scroll === "number" ? scroll : 0;
    }
    return 0;
  }
  // 恢复视图的滚动位置
  restoreScroll(leaf, scroll) {
    if (!scroll) return;
    const view = leaf == null ? void 0 : leaf.view;
    if (view == null ? void 0 : view.setEphemeralState) {
      view.setEphemeralState({ scroll });
    }
  }
  // 根据标注文件路径查找原始文件路径
  getOriginalPathByAnnotationPath(annotationPath) {
    for (const [originalPath, aPath] of this.activeAnnotationSessions) {
      if (aPath === annotationPath) return originalPath;
    }
    return null;
  }
  // 切换标注视图
  async toggleAnnotationView() {
    var _a;
    const leaf = this.app.workspace.activeLeaf;
    if (!leaf) return;
    const currentFile = (_a = leaf.view) == null ? void 0 : _a.file;
    if (!currentFile) {
      new import_obsidian2.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u4EF6");
      return;
    }
    const originalPath = this.getOriginalPathByAnnotationPath(currentFile.path);
    if (originalPath) {
      await this.closeAnnotationView(leaf, originalPath);
    } else if (currentFile.extension === "md") {
      await this.openAnnotationView(leaf, currentFile.path);
    }
  }
  // 打开标注视图
  async openAnnotationView(leaf, notePath) {
    var _a, _b;
    const savedScroll = this.getSavedScroll(leaf);
    const ok = await this.fileManager.ensureAnnotationFile(notePath);
    if (!ok) {
      new import_obsidian2.Notice("\u6807\u6CE8\u6587\u4EF6\u521B\u5EFA\u5931\u8D25");
      return;
    }
    const annotationPath = (0, import_obsidian2.normalizePath)(this.fileManager.getAnnotationFilePath(notePath));
    console.log("[\u6807\u6CE8] annotationPath:", annotationPath);
    const fakeTFile = this.createFakeTFile(annotationPath);
    console.log("[\u6807\u6CE8] fakeTFile:", fakeTFile.path, "basename:", fakeTFile.basename, "ext:", fakeTFile.extension, "deleted:", fakeTFile.deleted);
    this.activeAnnotationSessions.set(notePath, annotationPath);
    try {
      this.injectMetadataCache(annotationPath, notePath, fakeTFile);
      await leaf.openFile(fakeTFile, { state: { mode: "preview" } });
      console.log("[\u6807\u6CE8] openFile \u5B8C\u6210, \u5F53\u524D view:", (_b = (_a = leaf.view) == null ? void 0 : _a.constructor) == null ? void 0 : _b.name);
      if (savedScroll) {
        requestAnimationFrame(() => {
          requestAnimationFrame(() => this.restoreScroll(leaf, savedScroll));
        });
      }
    } catch (e) {
      console.error("[\u6807\u6CE8] openFile \u5931\u8D25:", e);
      new import_obsidian2.Notice("\u6253\u5F00\u6807\u6CE8\u6587\u4EF6\u5931\u8D25: " + e);
    }
  }
  // 关闭标注视图，切回原文件
  async closeAnnotationView(leaf, originalPath) {
    const savedScroll = this.getSavedScroll(leaf);
    const annotationPath = this.activeAnnotationSessions.get(originalPath);
    const originalFile = this.app.vault.getAbstractFileByPath(originalPath);
    if (!(originalFile instanceof import_obsidian2.TFile)) {
      new import_obsidian2.Notice("\u539F\u59CB\u6587\u4EF6\u4E0D\u5B58\u5728");
      if (annotationPath) {
        this.removeFakeTFile(annotationPath);
        this.removeMetadataCache(annotationPath);
      }
      this.activeAnnotationSessions.delete(originalPath);
      return;
    }
    await leaf.openFile(originalFile);
    if (annotationPath) {
      this.removeFakeTFile(annotationPath);
      this.removeMetadataCache(annotationPath);
    }
    this.activeAnnotationSessions.delete(originalPath);
    if (savedScroll) {
      requestAnimationFrame(() => {
        requestAnimationFrame(() => this.restoreScroll(leaf, savedScroll));
      });
    }
  }
  // 注册事件
  registerEvents() {
    this.registerEvent(
      this.app.vault.on("rename", async (file, oldPath) => {
        if (file instanceof import_obsidian2.TFile && file.extension === "md") {
          try {
            await this.fileManager.migrateAnnotationFile(oldPath, file.path);
          } catch (e) {
            console.error("\u8FC1\u79FB\u6807\u6CE8\u6587\u4EF6\u5931\u8D25:", e);
          }
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", async (file) => {
        if (file instanceof import_obsidian2.TFile && file.extension === "md") {
          try {
            await this.fileManager.deleteAnnotationFile(file.path);
          } catch (e) {
            console.error("\u5220\u9664\u6807\u6CE8\u6587\u4EF6\u5931\u8D25:", e);
          }
        }
      })
    );
  }
  // 注册命令
  registerCommands() {
    this.addCommand({
      id: "toggle-annotation-view",
      name: "\u5207\u6362\u6807\u6CE8\u89C6\u56FE",
      checkCallback: (checking) => {
        var _a;
        const leaf = this.app.workspace.activeLeaf;
        if (!leaf) return false;
        const file = (_a = leaf.view) == null ? void 0 : _a.file;
        if (!file || file.extension !== "md") return false;
        if (!checking) {
          this.toggleAnnotationView();
        }
        return true;
      }
    });
  }
};
