/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MarkdownAnnotationPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  defaultColor: "yellow",
  maxNoteLength: 500
};
var COLOR_MAP = {
  red: { bg: "rgba(255, 107, 107, 0.35)", border: "#ff6b6b" },
  blue: { bg: "rgba(84, 160, 255, 0.35)", border: "#54a0ff" },
  yellow: { bg: "rgba(255, 212, 59, 0.45)", border: "#ffd43b" },
  green: { bg: "rgba(38, 194, 129, 0.35)", border: "#26c281" },
  purple: { bg: "rgba(155, 89, 182, 0.35)", border: "#9b59b6" },
  none: { bg: "transparent", border: "#999" }
};
var COLOR_LABELS = {
  red: "\u7EA2\u8272",
  blue: "\u84DD\u8272",
  yellow: "\u9EC4\u8272",
  green: "\u7EFF\u8272",
  purple: "\u7D2B\u8272",
  none: "\u65E0\u8272"
};
var MATCH_THRESHOLD = 0.5;

// src/dataManager.ts
var import_obsidian = require("obsidian");

// src/utils/helpers.ts
function generateId() {
  return `${Date.now()}-${Math.random().toString(36).substring(2, 11)}`;
}
function calculateSimilarity(str1, str2) {
  var _a, _b, _c, _d, _e, _f;
  if (!str1 || !str2) return 0;
  if (str1 === str2) return 1;
  const len1 = str1.length;
  const len2 = str2.length;
  const maxLen = Math.max(len1, len2);
  if (maxLen === 0) return 1;
  const dp = [];
  for (let i = 0; i <= len1; i++) {
    const row = [];
    for (let j = 0; j <= len2; j++) {
      row[j] = 0;
    }
    dp[i] = row;
  }
  for (let i = 0; i <= len1; i++) {
    const row = dp[i];
    if (row) row[0] = i;
  }
  for (let j = 0; j <= len2; j++) {
    const row = dp[0];
    if (row) row[j] = j;
  }
  for (let i = 1; i <= len1; i++) {
    for (let j = 1; j <= len2; j++) {
      const currentRow = dp[i];
      const prevRow = dp[i - 1];
      if (!currentRow || !prevRow) continue;
      const char1 = str1[i - 1];
      const char2 = str2[j - 1];
      if (!char1 || !char2) continue;
      if (char1 === char2) {
        currentRow[j] = (_a = prevRow[j - 1]) != null ? _a : 0;
      } else {
        currentRow[j] = Math.min(
          ((_b = prevRow[j]) != null ? _b : 0) + 1,
          ((_c = currentRow[j - 1]) != null ? _c : 0) + 1,
          ((_d = prevRow[j - 1]) != null ? _d : 0) + 1
        );
      }
    }
  }
  const distance = (_f = (_e = dp[len1]) == null ? void 0 : _e[len2]) != null ? _f : maxLen;
  return 1 - distance / maxLen;
}

// src/dataManager.ts
var ANNOTATIONS_FOLDER = "annotations";
var DataManager = class {
  constructor(app, pluginDir) {
    this.cache = /* @__PURE__ */ new Map();
    this.app = app;
    this.pluginDir = pluginDir;
  }
  getAnnotationsDir() {
    return (0, import_obsidian.normalizePath)(`${this.pluginDir}/${ANNOTATIONS_FOLDER}`);
  }
  getAnnotationFilePath(filePath) {
    const pathWithoutExt = filePath.replace(/\.md$/i, "");
    const safeName = pathWithoutExt.replace(/[\\/:*?"<>|]/g, ".");
    return (0, import_obsidian.normalizePath)(`${this.getAnnotationsDir()}/${safeName}.json`);
  }
  async ensureAnnotationsDir() {
    const dir = this.getAnnotationsDir();
    const exists = await this.app.vault.adapter.exists(dir);
    if (!exists) {
      await this.app.vault.adapter.mkdir(dir);
    }
  }
  async loadAnnotations(filePath) {
    var _a;
    if (this.cache.has(filePath)) {
      return (_a = this.cache.get(filePath)) != null ? _a : null;
    }
    const annotationFilePath = this.getAnnotationFilePath(filePath);
    const exists = await this.app.vault.adapter.exists(annotationFilePath);
    if (!exists) {
      return null;
    }
    try {
      const content = await this.app.vault.adapter.read(annotationFilePath);
      const data = JSON.parse(content);
      data.annotations = this.migrateAnnotations(data.annotations);
      this.cache.set(filePath, data);
      return data;
    } catch (e) {
      console.error("\u52A0\u8F7D\u6807\u6CE8\u6570\u636E\u5931\u8D25:", e);
      return null;
    }
  }
  migrateAnnotations(annotations) {
    let migrated = false;
    const result = annotations.map((annotation) => {
      if (annotation.rubyText && !annotation.rubyTexts) {
        migrated = true;
        return {
          ...annotation,
          rubyTexts: [{
            startIndex: 0,
            length: annotation.text.length,
            ruby: annotation.rubyText
          }],
          rubyText: void 0
        };
      }
      return annotation;
    });
    if (migrated) {
      console.log("\u5DF2\u8FC1\u79FB\u65E7\u7248\u672C\u7684\u6CE8\u97F3\u6570\u636E\u5230\u65B0\u683C\u5F0F");
    }
    return result;
  }
  async saveAnnotations(filePath, data) {
    await this.ensureAnnotationsDir();
    const annotationFilePath = this.getAnnotationFilePath(filePath);
    const content = JSON.stringify(data, null, 2);
    await this.app.vault.adapter.write(annotationFilePath, content);
    this.cache.set(filePath, data);
  }
  async migrateAnnotation(oldPath, newPath) {
    const oldAnnotationPath = this.getAnnotationFilePath(oldPath);
    const newAnnotationPath = this.getAnnotationFilePath(newPath);
    if (oldAnnotationPath === newAnnotationPath) {
      return false;
    }
    const oldExists = await this.app.vault.adapter.exists(oldAnnotationPath);
    if (!oldExists) {
      return false;
    }
    try {
      const content = await this.app.vault.adapter.read(oldAnnotationPath);
      const data = JSON.parse(content);
      data.filePath = newPath;
      await this.saveAnnotations(newPath, data);
      await this.app.vault.adapter.remove(oldAnnotationPath);
      this.cache.delete(oldPath);
      return true;
    } catch (e) {
      console.error("\u8FC1\u79FB\u6807\u6CE8\u6570\u636E\u5931\u8D25:", e);
      return false;
    }
  }
  async deleteAnnotationData(filePath) {
    const annotationFilePath = this.getAnnotationFilePath(filePath);
    const exists = await this.app.vault.adapter.exists(annotationFilePath);
    if (!exists) {
      return false;
    }
    try {
      await this.app.vault.adapter.remove(annotationFilePath);
      this.cache.delete(filePath);
      return true;
    } catch (e) {
      console.error("\u5220\u9664\u6807\u6CE8\u6570\u636E\u5931\u8D25:", e);
      return false;
    }
  }
  async addAnnotation(filePath, annotation) {
    let data = await this.loadAnnotations(filePath);
    if (!data) {
      data = {
        filePath,
        annotations: []
      };
    }
    const existingIndex = data.annotations.findIndex((a) => {
      const textMatch = a.text.trim().toLowerCase() === annotation.text.trim().toLowerCase();
      const positionMatch = Math.abs(a.positionPercent - annotation.positionPercent) < 5;
      return textMatch && positionMatch;
    });
    if (existingIndex !== -1) {
      const existing = data.annotations[existingIndex];
      if (existing && existing.id && existing.id.trim()) {
        await this.deleteAnnotation(filePath, existing.id);
        await new Promise((resolve) => setTimeout(resolve, 300));
      }
      data = await this.loadAnnotations(filePath) || data;
    }
    const newAnnotation = {
      id: generateId(),
      text: annotation.text,
      contextBefore: annotation.contextBefore,
      contextAfter: annotation.contextAfter,
      positionPercent: annotation.positionPercent,
      color: annotation.color,
      note: annotation.note,
      rubyTexts: annotation.rubyTexts,
      createdAt: (/* @__PURE__ */ new Date()).toISOString(),
      updatedAt: (/* @__PURE__ */ new Date()).toISOString()
    };
    data.annotations.push(newAnnotation);
    await this.saveAnnotations(filePath, data);
    return newAnnotation;
  }
  async updateAnnotation(filePath, annotationId, updates) {
    var _a, _b, _c, _d, _e, _f;
    const data = await this.loadAnnotations(filePath);
    if (!data) return null;
    const index = data.annotations.findIndex((a) => a.id === annotationId);
    if (index === -1) return null;
    const existing = data.annotations[index];
    if (!existing) return null;
    const updated = {
      id: existing.id,
      text: existing.text,
      contextBefore: (_a = updates.contextBefore) != null ? _a : existing.contextBefore,
      contextAfter: (_b = updates.contextAfter) != null ? _b : existing.contextAfter,
      positionPercent: (_c = updates.positionPercent) != null ? _c : existing.positionPercent,
      color: (_d = updates.color) != null ? _d : existing.color,
      note: (_e = updates.note) != null ? _e : existing.note,
      rubyTexts: (_f = updates.rubyTexts) != null ? _f : existing.rubyTexts,
      createdAt: existing.createdAt,
      updatedAt: (/* @__PURE__ */ new Date()).toISOString()
    };
    data.annotations[index] = updated;
    await this.saveAnnotations(filePath, data);
    return updated;
  }
  async deleteAnnotation(filePath, annotationId) {
    const data = await this.loadAnnotations(filePath);
    if (!data) return false;
    const index = data.annotations.findIndex((a) => a.id === annotationId);
    if (index === -1) return false;
    data.annotations.splice(index, 1);
    await this.saveAnnotations(filePath, data);
    return true;
  }
  hasDuplicateText(annotations, text, contextBefore, contextAfter) {
    const normalizedText = text.trim().toLowerCase();
    return annotations.some(
      (a) => a.text.trim().toLowerCase() === normalizedText && a.contextBefore === contextBefore && a.contextAfter === contextAfter
    );
  }
  clearCache() {
    this.cache.clear();
  }
};

// src/annotationMode.ts
var import_obsidian5 = require("obsidian");

// src/annotationRenderer.ts
var AnnotationRenderer = class {
  constructor(view) {
    this.annotations = [];
    this.annotationElements = /* @__PURE__ */ new Map();
    this.tooltipEl = null;
    this.hideTooltipTimeout = null;
    this.view = view;
  }
  destroy() {
  }
  setAnnotations(annotations) {
    this.annotations = annotations;
  }
  renderByText(container) {
    this.clear();
    const lostAnnotations = [];
    const updatedContexts = [];
    this.annotations.forEach((annotation) => {
      const result = this.findAndHighlight(annotation, container);
      if (!result) {
        lostAnnotations.push(annotation);
      } else if (result.updated) {
        updatedContexts.push({
          id: annotation.id,
          contextBefore: result.newContextBefore,
          contextAfter: result.newContextAfter,
          positionPercent: result.newPositionPercent
        });
      }
    });
    return { lostAnnotations, updatedContexts };
  }
  findAndHighlight(annotation, container) {
    const textNodes = this.getAllTextNodes(container);
    const fullText = textNodes.map((n) => {
      var _a;
      return (_a = n.textContent) != null ? _a : "";
    }).join("");
    const searchText = annotation.text;
    const exactResult = this.findExactMatch(annotation, fullText, textNodes);
    if (exactResult) {
      return { updated: false };
    }
    const fuzzyResult = this.findFuzzyMatch(annotation, fullText, textNodes);
    if (fuzzyResult) {
      return {
        updated: true,
        newContextBefore: fuzzyResult.newContextBefore,
        newContextAfter: fuzzyResult.newContextAfter,
        newPositionPercent: fuzzyResult.newPositionPercent
      };
    }
    return null;
  }
  findExactMatch(annotation, fullText, textNodes) {
    const { text, contextBefore, contextAfter, positionPercent } = annotation;
    const centerPosition = positionPercent / 100 * fullText.length;
    const halfTextLength = text.length / 2;
    const initialStart = Math.max(0, Math.floor(centerPosition - halfTextLength));
    const initialEnd = Math.min(fullText.length, Math.ceil(centerPosition + halfTextLength));
    const contextStart = Math.max(0, initialStart - contextBefore.length);
    const contextEnd = Math.min(fullText.length, initialEnd + contextAfter.length);
    const extension5Percent = Math.max(50, Math.floor(fullText.length * 0.05));
    let searchStart = Math.max(0, contextStart - extension5Percent);
    let searchEnd = Math.min(fullText.length, contextEnd + extension5Percent);
    const maxExtension = 250;
    const extensionStep = 50;
    for (let currentExtension = 0; currentExtension <= maxExtension; currentExtension += extensionStep) {
      const searchArea = fullText.substring(searchStart, searchEnd);
      const searchText = contextBefore + text + contextAfter;
      let searchIndex = 0;
      while (searchIndex < searchArea.length) {
        const index = searchArea.indexOf(searchText, searchIndex);
        if (index === -1) break;
        const actualIndex = searchStart + index;
        const textIndex = actualIndex + contextBefore.length;
        const matchResult = this.findNodesForPosition(textNodes, textIndex, text.length);
        if (matchResult) {
          this.wrapMatchedNodes(annotation, matchResult);
          return true;
        }
        searchIndex = index + 1;
      }
      searchStart = Math.max(0, searchStart - extensionStep);
      searchEnd = Math.min(fullText.length, searchEnd + extensionStep);
    }
    return false;
  }
  findFuzzyMatch(annotation, fullText, textNodes) {
    const { text, contextBefore, contextAfter, positionPercent } = annotation;
    const centerPosition = positionPercent / 100 * fullText.length;
    const halfTextLength = text.length / 2;
    const initialStart = Math.max(0, Math.floor(centerPosition - halfTextLength));
    const initialEnd = Math.min(fullText.length, Math.ceil(centerPosition + halfTextLength));
    const extension5Percent = Math.max(50, Math.floor(fullText.length * 0.05));
    let searchStart = Math.max(0, initialStart - extension5Percent);
    let searchEnd = Math.min(fullText.length, initialEnd + extension5Percent);
    const maxExtension = 250;
    const extensionStep = 50;
    let bestMatch = null;
    for (let currentExtension = 0; currentExtension <= maxExtension; currentExtension += extensionStep) {
      const searchArea = fullText.substring(searchStart, searchEnd);
      let searchIndex = 0;
      while (searchIndex < searchArea.length) {
        const index = searchArea.indexOf(text, searchIndex);
        if (index === -1) break;
        const actualIndex = searchStart + index;
        const actualBefore = fullText.substring(
          Math.max(0, actualIndex - contextBefore.length),
          actualIndex
        );
        const actualAfter = fullText.substring(
          actualIndex + text.length,
          Math.min(fullText.length, actualIndex + text.length + contextAfter.length)
        );
        const beforeScore = contextBefore.length > 0 ? calculateSimilarity(contextBefore, actualBefore) : 1;
        const afterScore = contextAfter.length > 0 ? calculateSimilarity(contextAfter, actualAfter) : 1;
        const totalScore = (beforeScore + afterScore) / 2;
        if (totalScore > MATCH_THRESHOLD) {
          if (!bestMatch || totalScore > bestMatch.score) {
            bestMatch = {
              index: actualIndex,
              score: totalScore,
              contextBefore: actualBefore,
              contextAfter: actualAfter
            };
          }
        }
        searchIndex = index + 1;
      }
      if (bestMatch && bestMatch.score > 0.8) {
        break;
      }
      searchStart = Math.max(0, searchStart - extensionStep);
      searchEnd = Math.min(fullText.length, searchEnd + extensionStep);
    }
    if (!bestMatch) {
      searchStart = 0;
      searchEnd = fullText.length;
      let searchIndex = 0;
      while (searchIndex < searchEnd) {
        const index = fullText.indexOf(text, searchIndex);
        if (index === -1) break;
        const actualBefore = fullText.substring(
          Math.max(0, index - contextBefore.length),
          index
        );
        const actualAfter = fullText.substring(
          index + text.length,
          Math.min(fullText.length, index + text.length + contextAfter.length)
        );
        const beforeScore = contextBefore.length > 0 ? calculateSimilarity(contextBefore, actualBefore) : 1;
        const afterScore = contextAfter.length > 0 ? calculateSimilarity(contextAfter, actualAfter) : 1;
        const totalScore = (beforeScore + afterScore) / 2;
        if (totalScore > MATCH_THRESHOLD) {
          if (!bestMatch || totalScore > bestMatch.score) {
            bestMatch = {
              index,
              score: totalScore,
              contextBefore: actualBefore,
              contextAfter: actualAfter
            };
          }
        }
        searchIndex = index + 1;
      }
    }
    if (!bestMatch || bestMatch.score <= MATCH_THRESHOLD) {
      return null;
    }
    const matchResult = this.findNodesForPosition(textNodes, bestMatch.index, text.length);
    if (matchResult) {
      const textLength = fullText.length;
      const newPositionPercent = textLength > 0 ? (bestMatch.index + bestMatch.index + text.length) / 2 / textLength * 100 : 50;
      this.wrapMatchedNodes(annotation, matchResult);
      return {
        newContextBefore: bestMatch.contextBefore,
        newContextAfter: bestMatch.contextAfter,
        newPositionPercent
      };
    }
    return null;
  }
  findNodesForPosition(textNodes, globalStart, length) {
    var _a, _b;
    let currentOffset = 0;
    let remaining = length;
    const result = [];
    for (const textNode of textNodes) {
      const nodeText = (_a = textNode.textContent) != null ? _a : "";
      const nodeLength = nodeText.length;
      const offsetInDocument = ((_b = textNode.parentElement) == null ? void 0 : _b.closest("mark[data-annotation-id]")) ? -1 : currentOffset;
      if (currentOffset + nodeLength <= globalStart) {
        currentOffset += nodeLength;
        continue;
      }
      if (remaining <= 0) break;
      const startInNode = globalStart - currentOffset;
      const availableInNode = nodeLength - Math.max(0, startInNode);
      const takeLength = Math.min(availableInNode, remaining);
      result.push({
        node: textNode,
        start: Math.max(0, startInNode),
        length: takeLength
      });
      remaining -= takeLength;
      currentOffset += nodeLength;
      if (remaining <= 0) break;
    }
    return result.length > 0 ? result : null;
  }
  wrapMatchedNodes(annotation, matches) {
    var _a, _b, _c;
    const colorStyle = COLOR_MAP[annotation.color];
    const rubyTexts = annotation.rubyTexts;
    if (matches.length === 0) return;
    let fullHighlightedText = "";
    matches.forEach((match, index) => {
      var _a2;
      if (!document.contains(match.node)) {
        return;
      }
      const text = (_a2 = match.node.textContent) != null ? _a2 : "";
      const highlighted = text.substring(match.start, match.start + match.length);
      fullHighlightedText += highlighted;
    });
    const markElement = this.createHighlightSpan(annotation, fullHighlightedText, colorStyle);
    if (matches.length === 1) {
      const match = matches[0];
      const text = (_a = match.node.textContent) != null ? _a : "";
      const before = text.substring(0, match.start);
      const after = text.substring(match.start + match.length);
      const parent = match.node.parentNode;
      if (parent) {
        const fragment = document.createDocumentFragment();
        if (before) fragment.appendChild(document.createTextNode(before));
        fragment.appendChild(markElement);
        if (after) fragment.appendChild(document.createTextNode(after));
        parent.replaceChild(fragment, match.node);
      }
    } else {
      const firstMatch = matches[0];
      const lastMatch = matches[matches.length - 1];
      const firstParent = firstMatch.node.parentNode;
      const lastParent = lastMatch.node.parentNode;
      if (!firstParent || !lastParent) return;
      const firstText = (_b = firstMatch.node.textContent) != null ? _b : "";
      const before = firstText.substring(0, firstMatch.start);
      const lastText = (_c = lastMatch.node.textContent) != null ? _c : "";
      const after = lastText.substring(lastMatch.start + lastMatch.length);
      const fragment = document.createDocumentFragment();
      if (before) fragment.appendChild(document.createTextNode(before));
      fragment.appendChild(markElement);
      if (after) fragment.appendChild(document.createTextNode(after));
      const allNodesBetween = [];
      let current = firstMatch.node.nextSibling;
      while (current) {
        allNodesBetween.push(current);
        if (current === lastMatch.node) {
          break;
        }
        current = current.nextSibling;
      }
      firstParent.insertBefore(fragment, firstMatch.node);
      allNodesBetween.forEach((node) => {
        if (node.parentNode) {
          node.parentNode.removeChild(node);
        }
      });
      if (firstMatch.node.parentNode) {
        firstMatch.node.parentNode.removeChild(firstMatch.node);
      }
    }
    this.annotationElements.set(annotation.id, [markElement]);
  }
  getAllTextNodes(container) {
    const textNodes = [];
    const walker = document.createTreeWalker(container, NodeFilter.SHOW_TEXT, null);
    let node = walker.nextNode();
    while (node) {
      const textNode = node;
      if (textNode.textContent && textNode.textContent.trim().length > 0) {
        const parent = textNode.parentElement;
        if (parent && parent.tagName !== "RT" && !parent.closest("mark[data-annotation-id]") && !parent.closest("div.inline-title") && !parent.closest("[class*='metadata-']") && !parent.closest("div.multi-select-pill-content") && !parent.closest("div.metadata-content") && !parent.closest("div.mod-header") && !parent.closest("div.mod-ui")) {
          textNodes.push(textNode);
        }
      }
      node = walker.nextNode();
    }
    return textNodes;
  }
  createHighlightSpan(annotation, text, colorStyle) {
    let rubyTexts = annotation.rubyTexts;
    if (!rubyTexts && annotation.rubyText) {
      rubyTexts = [{
        startIndex: 0,
        length: text.length,
        ruby: annotation.rubyText
      }];
    }
    const hasRubies = rubyTexts && rubyTexts.length > 0;
    const container = document.createElement("mark");
    container.dataset.annotationId = annotation.id;
    if (annotation.color !== "none") {
      container.style.backgroundColor = colorStyle.bg;
    }
    if (annotation.note && annotation.note.trim()) {
      container.style.borderBottom = `2px solid ${colorStyle.border}`;
    }
    if (!hasRubies) {
      container.textContent = text;
    } else {
      let currentIndex = 0;
      const sortedRubies = [...rubyTexts].sort((a, b) => a.startIndex - b.startIndex);
      for (const ruby of sortedRubies) {
        if (ruby.startIndex > currentIndex) {
          const beforeText = text.substring(currentIndex, ruby.startIndex);
          container.appendChild(document.createTextNode(beforeText));
        }
        const rubyEl = document.createElement("ruby");
        const spanEl = document.createElement("span");
        spanEl.textContent = text.substring(ruby.startIndex, ruby.startIndex + ruby.length);
        rubyEl.appendChild(spanEl);
        const rtEl = document.createElement("rt");
        rtEl.textContent = ruby.ruby;
        rubyEl.appendChild(rtEl);
        container.appendChild(rubyEl);
        currentIndex = ruby.startIndex + ruby.length;
      }
      if (currentIndex < text.length) {
        const afterText = text.substring(currentIndex);
        container.appendChild(document.createTextNode(afterText));
      }
    }
    container.style.cursor = "pointer";
    container.addEventListener("mouseenter", (e) => this.showTooltip(e, annotation));
    container.addEventListener("mousemove", (e) => this.moveTooltip(e));
    container.addEventListener("mouseleave", () => this.hideTooltip());
    return container;
  }
  showTooltip(e, annotation) {
    var _a;
    if (!annotation.note || !annotation.note.trim()) {
      return;
    }
    if (this.hideTooltipTimeout) {
      clearTimeout(this.hideTooltipTimeout);
      this.hideTooltipTimeout = null;
    }
    if (!this.tooltipEl) {
      this.tooltipEl = document.createElement("div");
      this.tooltipEl.className = "annotation-highlight-tooltip";
      document.body.appendChild(this.tooltipEl);
    }
    const noteText = ((_a = annotation.note) == null ? void 0 : _a.trim()) || "";
    const tooltipContent = noteText ? `<div class="annotation-tooltip-label">\u6279\u6CE8\u5185\u5BB9</div><div class="annotation-tooltip-content">${this.escapeHtml(noteText)}</div>` : `<div class="annotation-tooltip-empty">\u65E0\u6279\u6CE8\u5185\u5BB9</div>`;
    this.tooltipEl.innerHTML = tooltipContent;
    const rect = e.target.getBoundingClientRect();
    const tooltipRect = this.tooltipEl.getBoundingClientRect();
    const threshold = window.innerHeight * 0.5;
    if (rect.bottom > threshold) {
      this.tooltipEl.classList.add("tooltip-bottom");
      this.tooltipEl.style.top = `${rect.top - tooltipRect.height - 12}px`;
    } else {
      this.tooltipEl.classList.remove("tooltip-bottom");
      this.tooltipEl.style.top = `${rect.bottom + 8}px`;
    }
    const left = rect.left + rect.width / 2 - tooltipRect.width / 2;
    this.tooltipEl.style.left = `${Math.max(10, Math.min(left, window.innerWidth - tooltipRect.width - 10))}px`;
    this.tooltipEl.style.opacity = "1";
    this.tooltipEl.style.visibility = "visible";
  }
  moveTooltip(e) {
    if (!this.tooltipEl) return;
    const target = e.target;
    const rect = target.getBoundingClientRect();
    const tooltipRect = this.tooltipEl.getBoundingClientRect();
    const threshold = window.innerHeight * 0.5;
    if (rect.bottom > threshold) {
      this.tooltipEl.classList.add("tooltip-bottom");
      this.tooltipEl.style.top = `${rect.top - tooltipRect.height - 12}px`;
    } else {
      this.tooltipEl.classList.remove("tooltip-bottom");
      this.tooltipEl.style.top = `${rect.bottom + 8}px`;
    }
    const left = rect.left + rect.width / 2 - tooltipRect.width / 2;
    this.tooltipEl.style.left = `${Math.max(10, Math.min(left, window.innerWidth - tooltipRect.width - 10))}px`;
  }
  hideTooltip() {
    if (this.tooltipEl) {
      this.tooltipEl.style.opacity = "0";
      this.tooltipEl.style.visibility = "hidden";
    }
  }
  escapeHtml(text) {
    const div = document.createElement("div");
    div.textContent = text;
    return div.innerHTML;
  }
  clear() {
    this.hideTooltip();
    this.annotationElements.forEach((elements) => {
      elements.forEach((el) => {
        var _a;
        const parent = el.parentNode;
        if (parent) {
          let textContent = "";
          if (el.tagName === "MARK") {
            const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT, null);
            let node = walker.nextNode();
            while (node) {
              const textNode2 = node;
              const parentElement = textNode2.parentElement;
              if (parentElement && parentElement.tagName !== "RT") {
                textContent += textNode2.textContent;
              }
              node = walker.nextNode();
            }
          } else {
            textContent = (_a = el.textContent) != null ? _a : "";
          }
          const textNode = document.createTextNode(textContent);
          parent.replaceChild(textNode, el);
        }
      });
    });
    this.annotationElements.clear();
  }
};

// src/selectionMenu.ts
var import_obsidian2 = require("obsidian");
var SelectionMenu = class {
  constructor(app, dataManager) {
    this.menuEl = null;
    this.selectedColor = "yellow";
    this.currentFilePath = null;
    this.selectedText = "";
    this.contextBefore = "";
    this.contextAfter = "";
    this.positionPercent = 0;
    this.onAddCallback = null;
    this.pendingNote = "";
    this.noteInput = null;
    this.colorContainer = null;
    this.rubyTextEnabled = false;
    this.rubyTexts = [];
    this.rubyTextInput = null;
    this.rubyTextContainer = null;
    this.rubyPreview = null;
    this.rubyTextPreview = null;
    this.selectedRubyRange = null;
    this.extractedRubyInfo = null;
    this.partialAnnotationInfo = null;
    this.updateRubyList = null;
    this.fullText = "";
    this.startIndexInFullText = 0;
    this.endIndexInFullText = 0;
    this.app = app;
    this.dataManager = dataManager;
  }
  show(x, y, selectedText, contextBefore, contextAfter, positionPercent, filePath, onAdd, extractedRubyInfo, partialAnnotationInfo) {
    this.currentFilePath = filePath;
    this.selectedText = selectedText;
    this.contextBefore = contextBefore;
    this.contextAfter = contextAfter;
    this.positionPercent = positionPercent;
    this.onAddCallback = onAdd;
    this.extractedRubyInfo = extractedRubyInfo || null;
    this.partialAnnotationInfo = partialAnnotationInfo || null;
    this.hide();
    const isUpdatingAnnotation = !!this.partialAnnotationInfo;
    this.rubyTexts = (extractedRubyInfo == null ? void 0 : extractedRubyInfo.rubyTexts) ? [...extractedRubyInfo.rubyTexts] : [];
    this.rubyTextEnabled = this.rubyTexts.length > 0 || isUpdatingAnnotation;
    this.selectedRubyRange = null;
    this.menuEl = document.createElement("div");
    this.menuEl.className = "annotation-card-menu annotation-selection-menu";
    const header = this.menuEl.createDiv({ cls: "annotation-menu-header" });
    const titleText = isUpdatingAnnotation ? "\u6DFB\u52A0\u6CE8\u97F3" : "\u6DFB\u52A0\u6807\u6CE8";
    header.createEl("span", { text: titleText, cls: "annotation-menu-title" });
    const closeBtn = header.createEl("button", { cls: "annotation-menu-close", text: "\xD7" });
    closeBtn.addEventListener("click", () => this.hide());
    const scrollableContent = this.menuEl.createDiv({ cls: "annotation-menu-scrollable-content" });
    const textPreview = scrollableContent.createDiv({ cls: "annotation-menu-preview" });
    const previewText = selectedText.length > 80 ? selectedText.substring(0, 80) + "..." : selectedText;
    textPreview.createEl("span", { text: `"${previewText}"` });
    const colorSection = scrollableContent.createDiv({ cls: "annotation-menu-section" });
    colorSection.createEl("label", { text: "\u9009\u62E9\u989C\u8272\u7ACB\u5373\u6807\u6CE8" });
    this.colorContainer = colorSection.createDiv({ cls: "annotation-color-buttons" });
    const colors = ["red", "yellow", "green", "blue", "purple", "none"];
    colors.forEach((c) => {
      const btn = this.colorContainer.createEl("button", { cls: `annotation-color-dot color-${c}` });
      if (isUpdatingAnnotation) {
        btn.disabled = true;
        btn.style.opacity = "0.5";
        btn.style.cursor = "not-allowed";
        btn.title = "\u66F4\u65B0\u5DF2\u6709\u6807\u6CE8\u65F6\u4E0D\u80FD\u66F4\u6539\u989C\u8272";
      } else {
        if (c === this.selectedColor) {
          btn.addClass("active");
        }
        btn.title = COLOR_LABELS[c];
        btn.addEventListener("click", (e) => {
          e.stopPropagation();
          this.selectedColor = c;
          this.colorContainer.querySelectorAll(".annotation-color-dot").forEach((b) => b.removeClass("active"));
          btn.addClass("active");
          if (c === "none" && !this.pendingNote && this.rubyTexts.length === 0) {
            this.hide();
            return;
          }
          if (this.pendingNote) {
            return;
          }
          this.createAnnotation("");
        });
      }
    });
    const noteSection = scrollableContent.createDiv({ cls: "annotation-menu-section" });
    const noteLabel = noteSection.createDiv({ cls: "annotation-note-label-row" });
    noteLabel.createEl("label", { text: "\u6216\u6DFB\u52A0\u6279\u6CE8" });
    const charCount = noteLabel.createSpan({ cls: "annotation-char-count", text: "(0/400)" });
    this.noteInput = noteSection.createEl("textarea", { cls: "annotation-note-input-small", placeholder: "\u8F93\u5165\u6279\u6CE8\u5185\u5BB9\uFF08\u53EF\u9009\uFF0C\u6700\u591A400\u5B57\uFF09..." });
    this.noteInput.setAttribute("maxlength", "400");
    this.noteInput.addEventListener("input", () => {
      const len = this.noteInput.value.length;
      this.pendingNote = this.noteInput.value;
      charCount.textContent = `(${len}/400)`;
      if (len > 400) {
        charCount.addClass("annotation-char-count-error");
      } else {
        charCount.removeClass("annotation-char-count-error");
      }
    });
    const rubySection = noteSection.createDiv({ cls: "annotation-ruby-section" });
    const rubyRow = rubySection.createDiv({ cls: "annotation-ruby-row" });
    const rubyCheckbox = rubyRow.createEl("input", { type: "checkbox", cls: "annotation-ruby-checkbox" });
    rubyCheckbox.checked = this.rubyTextEnabled;
    rubyCheckbox.addEventListener("change", () => {
      var _a;
      this.rubyTextEnabled = rubyCheckbox.checked;
      if (this.rubyTextEnabled) {
        this.rubyTextContainer.style.display = "block";
        this.rubyTextInput.focus();
        requestAnimationFrame(() => {
          this.adjustMenuPosition();
        });
      } else {
        this.rubyTextContainer.style.display = "none";
        this.rubyTexts = [];
        (_a = this.updateRubyList) == null ? void 0 : _a.call(this);
      }
    });
    rubyRow.createEl("label", { text: "\u6CE8\u97F3" });
    this.rubyTextContainer = rubySection.createDiv({ cls: "annotation-ruby-input-container" });
    if (!this.rubyTextEnabled) {
      this.rubyTextContainer.style.display = "none";
    }
    this.rubyPreview = this.rubyTextContainer.createDiv({ cls: "annotation-ruby-preview" });
    const rubyLabelText = isUpdatingAnnotation ? "\u5DF2\u9009\u4E2D\u6587\u5B57\uFF08\u5C06\u6DFB\u52A0\u6CE8\u97F3\uFF09\uFF1A" : "\u5212\u9009\u9700\u8981\u6CE8\u97F3\u7684\u6587\u5B57\uFF1A";
    this.rubyPreview.createEl("label", { text: rubyLabelText });
    this.rubyTextPreview = this.rubyPreview.createDiv({ cls: "annotation-ruby-text-preview", text: selectedText });
    this.rubyTextPreview.setAttribute("data-selected-text", selectedText);
    const rubyInputRow = this.rubyTextContainer.createDiv({ cls: "annotation-ruby-input-row" });
    rubyInputRow.createEl("label", { text: "\u6CE8\u97F3\u5185\u5BB9\uFF1A" });
    this.rubyTextInput = rubyInputRow.createEl("input", { type: "text", cls: "annotation-ruby-input", placeholder: "\u8F93\u5165\u6CE8\u97F3\u5185\u5BB9..." });
    this.rubyTextPreview.addEventListener("mouseup", () => {
      setTimeout(() => {
        const selection = window.getSelection();
        if (selection && !selection.isCollapsed) {
          const selectedRubyText = selection.toString();
          const fullText = this.rubyTextPreview.textContent || "";
          const startIndex = fullText.indexOf(selectedRubyText);
          if (startIndex !== -1) {
            this.selectedRubyRange = { start: startIndex, end: startIndex + selectedRubyText.length };
          }
        }
      }, 10);
    });
    this.rubyTextInput.addEventListener("focus", () => {
      if (this.selectedRubyRange) {
        const selection = window.getSelection();
        if (selection) {
          const fullText = this.rubyTextPreview.textContent || "";
          const textNode = this.rubyTextPreview.firstChild;
          if (textNode) {
            const range = document.createRange();
            range.setStart(textNode, this.selectedRubyRange.start);
            range.setEnd(textNode, this.selectedRubyRange.end);
            selection.removeAllRanges();
            selection.addRange(range);
          }
        }
      }
    });
    const addRubyBtn = rubyInputRow.createEl("button", { text: "\u6DFB\u52A0", cls: "annotation-btn annotation-btn-small" });
    addRubyBtn.addEventListener("click", () => {
      var _a, _b;
      const selection = window.getSelection();
      let selectedRubyText = "";
      if (selection && !selection.isCollapsed) {
        selectedRubyText = selection.toString();
      } else if (this.selectedRubyRange) {
        selectedRubyText = selectedText.substring(this.selectedRubyRange.start, this.selectedRubyRange.end);
      }
      if (selectedRubyText && this.rubyTextInput.value.trim()) {
        const fullText = this.rubyTextPreview.textContent || "";
        const startIndex = fullText.indexOf(selectedRubyText);
        if (startIndex !== -1) {
          this.rubyTexts.push({
            startIndex,
            length: selectedRubyText.length,
            ruby: this.rubyTextInput.value.trim()
          });
          this.rubyTextInput.value = "";
          this.selectedRubyRange = null;
          if (selection) {
            selection.removeAllRanges();
          }
          (_a = this.updateRubyList) == null ? void 0 : _a.call(this);
        }
      } else {
        if (!selectedRubyText) {
          if (selectedText.length === 1) {
            this.rubyTexts.push({
              startIndex: 0,
              length: 1,
              ruby: this.rubyTextInput.value.trim()
            });
            this.rubyTextInput.value = "";
            this.selectedRubyRange = null;
            (_b = this.updateRubyList) == null ? void 0 : _b.call(this);
          } else {
            new import_obsidian2.Notice("\u8BF7\u5148\u5212\u9009\u9700\u8981\u6CE8\u97F3\u7684\u6587\u5B57");
          }
        } else {
          new import_obsidian2.Notice("\u8BF7\u8F93\u5165\u6CE8\u97F3\u5185\u5BB9");
        }
      }
    });
    const rubyListContainer = this.rubyTextContainer.createDiv({ cls: "annotation-ruby-list-container" });
    rubyListContainer.createEl("label", { text: "\u5DF2\u6DFB\u52A0\u7684\u6CE8\u97F3\uFF1A" });
    const rubyList = rubyListContainer.createDiv({ cls: "annotation-ruby-list" });
    this.updateRubyList = () => {
      rubyList.empty();
      if (this.rubyTexts.length === 0) {
        rubyList.createDiv({ text: "\u6682\u65E0\u6CE8\u97F3", cls: "annotation-ruby-empty" });
      } else {
        this.rubyTexts.forEach((ruby, index) => {
          const item = rubyList.createDiv({ cls: "annotation-ruby-item" });
          const textPart = item.createSpan({ text: `${selectedText.substring(ruby.startIndex, ruby.startIndex + ruby.length)} \u2192 ${ruby.ruby}`, cls: "annotation-ruby-item-text" });
          const deleteBtn = item.createEl("button", { text: "\xD7", cls: "annotation-ruby-item-delete" });
          deleteBtn.addEventListener("click", (e) => {
            var _a;
            e.stopPropagation();
            this.rubyTexts.splice(index, 1);
            (_a = this.updateRubyList) == null ? void 0 : _a.call(this);
          });
        });
      }
    };
    this.updateRubyList();
    const actionRow = this.menuEl.createDiv({ cls: "annotation-action-row" });
    actionRow.style.flexShrink = "0";
    const copyBtn = actionRow.createEl("button", { cls: "annotation-btn annotation-btn-secondary annotation-btn-small", text: "\u590D\u5236" });
    copyBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      navigator.clipboard.writeText(selectedText);
      new import_obsidian2.Notice("\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F");
    });
    const saveButtonText = isUpdatingAnnotation ? "\u4FDD\u5B58\u6CE8\u97F3" : "\u4FDD\u5B58";
    const noteBtn = actionRow.createEl("button", {
      cls: "annotation-btn annotation-btn-primary annotation-btn-small",
      text: saveButtonText
    });
    noteBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      const note = this.noteInput.value.trim();
      if (note.length > 400) {
        new import_obsidian2.Notice("\u6279\u6CE8\u5185\u5BB9\u4E0D\u80FD\u8D85\u8FC7400\u5B57");
        return;
      }
      await this.createAnnotation(note);
    });
    document.body.appendChild(this.menuEl);
    requestAnimationFrame(() => {
      const menuWidth = 280;
      const menuHeight = this.menuEl.offsetHeight || 200;
      let menuX = x + 10;
      let menuY = y + 10;
      if (menuX + menuWidth > window.innerWidth) {
        menuX = x - menuWidth - 10;
      }
      const threshold = window.innerHeight * 0.4;
      if (y > threshold) {
        menuY = y - menuHeight - 10;
      }
      if (menuY + menuHeight > window.innerHeight) {
        menuY = window.innerHeight - menuHeight - 10;
      }
      if (menuY < 10) {
        menuY = 10;
      }
      this.menuEl.style.left = `${Math.max(10, menuX)}px`;
      this.menuEl.style.top = `${menuY}px`;
    });
    const clickHandler = (e) => {
      if (this.menuEl && !this.menuEl.contains(e.target)) {
        this.hide();
        document.removeEventListener("click", clickHandler);
      }
    };
    setTimeout(() => document.addEventListener("click", clickHandler), 10);
  }
  async createAnnotation(note) {
    if (!this.currentFilePath) return;
    try {
      if (this.partialAnnotationInfo) {
        const annotationId = this.partialAnnotationInfo.annotationId;
        const data = await this.dataManager.loadAnnotations(this.currentFilePath);
        if (!data) {
          new import_obsidian2.Notice("\u65E0\u6CD5\u627E\u5230\u539F\u6709\u6807\u6CE8");
          return;
        }
        const existingAnnotation = data.annotations.find((a) => a.id === annotationId);
        if (!existingAnnotation) {
          new import_obsidian2.Notice("\u65E0\u6CD5\u627E\u5230\u539F\u6709\u6807\u6CE8");
          return;
        }
        const newRubyTexts = this.rubyTexts.map((ruby) => ({
          startIndex: this.partialAnnotationInfo.startIndex + ruby.startIndex,
          length: ruby.length,
          ruby: ruby.ruby
        }));
        const updatedRubyTexts = this.mergeRubyTexts(
          existingAnnotation.rubyTexts || [],
          newRubyTexts
        );
        await this.dataManager.updateAnnotation(this.currentFilePath, annotationId, {
          rubyTexts: updatedRubyTexts.length > 0 ? updatedRubyTexts : void 0
        });
        this.partialAnnotationInfo = null;
        this.hide();
        if (this.onAddCallback) {
          await new Promise((resolve) => setTimeout(resolve, 300));
          await this.onAddCallback();
        }
        new import_obsidian2.Notice("\u6CE8\u97F3\u5DF2\u6DFB\u52A0");
        return;
      }
      if (this.extractedRubyInfo && this.extractedRubyInfo.annotationIds && this.extractedRubyInfo.annotationIds.length > 0) {
        for (const annotationId of this.extractedRubyInfo.annotationIds) {
          await this.dataManager.deleteAnnotation(this.currentFilePath, annotationId);
        }
        this.dataManager.clearCache();
        await new Promise((resolve) => setTimeout(resolve, 100));
      }
      const rubyTexts = this.rubyTextEnabled && this.rubyTexts.length > 0 ? this.rubyTexts : void 0;
      const result = await this.dataManager.addAnnotation(this.currentFilePath, {
        text: this.selectedText,
        contextBefore: this.contextBefore,
        contextAfter: this.contextAfter,
        positionPercent: this.positionPercent,
        color: this.selectedColor,
        note,
        rubyTexts
      });
      if (result) {
        this.pendingNote = "";
        this.rubyTextEnabled = false;
        this.rubyTexts = [];
        this.extractedRubyInfo = null;
        this.hide();
        if (this.onAddCallback) {
          await new Promise((resolve) => setTimeout(resolve, 300));
          await this.onAddCallback();
        }
        new import_obsidian2.Notice(note || rubyTexts ? "\u6807\u6CE8\u548C\u6279\u6CE8\u5DF2\u6DFB\u52A0" : "\u6807\u6CE8\u5DF2\u6DFB\u52A0");
      }
    } catch (e) {
      console.error("\u6DFB\u52A0\u6807\u6CE8\u5931\u8D25:", e);
      new import_obsidian2.Notice("\u6DFB\u52A0\u6807\u6CE8\u5931\u8D25");
    }
  }
  mergeRubyTexts(existing, newItems) {
    const merged = [...existing];
    for (const newItem of newItems) {
      const overlapIndex = merged.findIndex(
        (item) => newItem.startIndex >= item.startIndex && newItem.startIndex < item.startIndex + item.length || item.startIndex >= newItem.startIndex && item.startIndex < newItem.startIndex + newItem.length
      );
      if (overlapIndex !== -1) {
        merged[overlapIndex] = newItem;
      } else {
        merged.push(newItem);
      }
    }
    return merged.sort((a, b) => a.startIndex - b.startIndex);
  }
  hide() {
    if (this.menuEl) {
      this.menuEl.remove();
      this.menuEl = null;
    }
  }
  adjustMenuPosition() {
    if (!this.menuEl) return;
    const menuHeight = this.menuEl.offsetHeight || 200;
    const currentTop = parseInt(this.menuEl.style.top || "0", 10);
    const bottomPosition = currentTop + menuHeight;
    if (bottomPosition > window.innerHeight - 20) {
      const newTop = Math.max(10, window.innerHeight - menuHeight - 20);
      this.menuEl.style.top = `${newTop}px`;
    }
  }
};

// src/annotationMenu.ts
var import_obsidian3 = require("obsidian");
var AnnotationMenu = class {
  constructor(app, dataManager) {
    this.menuEl = null;
    this.app = app;
    this.dataManager = dataManager;
  }
  show(x, y, annotation, filePath, onUpdate) {
    this.hide();
    this.menuEl = document.createElement("div");
    this.menuEl.className = "annotation-card-menu annotation-view-menu";
    const header = this.menuEl.createDiv({ cls: "annotation-menu-header" });
    header.createEl("span", { text: "\u6807\u6CE8\u8BE6\u60C5", cls: "annotation-menu-title" });
    const closeBtn = header.createEl("button", { cls: "annotation-menu-close", text: "\xD7" });
    closeBtn.addEventListener("click", () => this.hide());
    const textPreview = this.menuEl.createDiv({ cls: "annotation-menu-text" });
    const previewText = annotation.text.length > 80 ? annotation.text.substring(0, 80) + "..." : annotation.text;
    textPreview.createEl("span", { text: `"${previewText}"` });
    if (annotation.note) {
      const noteSection = this.menuEl.createDiv({ cls: "annotation-menu-note" });
      noteSection.createEl("label", { text: "\u6279\u6CE8\u5185\u5BB9" });
      noteSection.createEl("div", { cls: "annotation-note-text", text: annotation.note });
    }
    const colorSection = this.menuEl.createDiv({ cls: "annotation-menu-section" });
    colorSection.createEl("label", { text: "\u6807\u6CE8\u989C\u8272" });
    const colorContainer = colorSection.createDiv({ cls: "annotation-color-buttons" });
    const colors = ["red", "yellow", "green", "blue", "purple", "none"];
    colors.forEach((c) => {
      const btn = colorContainer.createEl("button", { cls: `annotation-color-dot color-${c}` });
      if (c === annotation.color) {
        btn.addClass("active");
      }
      btn.title = COLOR_LABELS[c];
      btn.addEventListener("click", (e) => {
        e.stopPropagation();
        if (c !== annotation.color) {
          this.updateColor(annotation, filePath, c, onUpdate);
        }
      });
    });
    const actions = this.menuEl.createDiv({ cls: "annotation-menu-actions" });
    const editBtn = actions.createEl("button", { cls: "annotation-btn annotation-btn-secondary", text: "\u7F16\u8F91\u6279\u6CE8" });
    editBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.showEditModal(annotation, filePath, onUpdate);
    });
    const copyBtn = actions.createEl("button", { cls: "annotation-btn annotation-btn-secondary", text: "\u590D\u5236\u539F\u6587" });
    copyBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      navigator.clipboard.writeText(annotation.text);
      new import_obsidian3.Notice("\u5DF2\u590D\u5236\u539F\u6587\u5230\u526A\u8D34\u677F");
    });
    const deleteBtn = actions.createEl("button", { cls: "annotation-btn annotation-btn-danger", text: "\u5220\u9664" });
    deleteBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      await this.dataManager.deleteAnnotation(filePath, annotation.id);
      this.hide();
      onUpdate();
      new import_obsidian3.Notice("\u6807\u6CE8\u5DF2\u5220\u9664");
    });
    document.body.appendChild(this.menuEl);
    const menuWidth = 300;
    const menuHeight = this.menuEl.offsetHeight || 250;
    let menuX = x + 10;
    let menuY = y + 10;
    if (menuX + menuWidth > window.innerWidth) {
      menuX = x - menuWidth - 10;
    }
    const threshold = window.innerHeight * 0.4;
    if (y > threshold) {
      menuY = y - menuHeight - 10;
    }
    if (menuY + menuHeight > window.innerHeight) {
      menuY = window.innerHeight - menuHeight - 10;
    }
    this.menuEl.style.left = `${Math.max(10, menuX)}px`;
    this.menuEl.style.top = `${Math.max(10, menuY)}px`;
    const clickHandler = (e) => {
      if (this.menuEl && !this.menuEl.contains(e.target)) {
        this.hide();
        document.removeEventListener("click", clickHandler);
      }
    };
    setTimeout(() => document.addEventListener("click", clickHandler), 10);
  }
  async updateColor(annotation, filePath, color, onUpdate) {
    await this.dataManager.updateAnnotation(filePath, annotation.id, { color });
    this.hide();
    onUpdate();
    new import_obsidian3.Notice("\u6807\u6CE8\u989C\u8272\u5DF2\u4FEE\u6539");
  }
  showEditModal(annotation, filePath, onUpdate) {
    this.hide();
    const modal = new EditNoteModal(this.app, annotation, async (note, color, rubyTexts) => {
      await this.dataManager.updateAnnotation(filePath, annotation.id, { note, color, rubyTexts });
      onUpdate();
      new import_obsidian3.Notice("\u6279\u6CE8\u5DF2\u66F4\u65B0");
    });
    modal.open();
  }
  hide() {
    if (this.menuEl) {
      this.menuEl.remove();
      this.menuEl = null;
    }
  }
};
var EditNoteModal = class extends import_obsidian3.Modal {
  constructor(app, annotation, onSave) {
    super(app);
    this.noteInput = null;
    this.rubyTextEnabled = false;
    this.rubyTexts = [];
    this.rubyTextInput = null;
    this.rubyTextContainer = null;
    this.rubyPreview = null;
    this.rubyTextPreview = null;
    this.selectedRubyRange = null;
    this.updateRubyList = null;
    this.annotation = annotation;
    this.onSave = onSave;
    this.currentColor = annotation.color;
    if (annotation.rubyText && !annotation.rubyTexts) {
      this.rubyTexts = [{
        startIndex: 0,
        length: annotation.text.length,
        ruby: annotation.rubyText
      }];
      this.rubyTextEnabled = true;
    } else {
      this.rubyTextEnabled = !!annotation.rubyTexts && annotation.rubyTexts.length > 0;
      this.rubyTexts = annotation.rubyTexts || [];
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("annotation-note-modal");
    contentEl.createEl("h3", { text: this.annotation.note ? "\u7F16\u8F91\u6279\u6CE8" : "\u6DFB\u52A0\u6279\u6CE8" });
    const previewEl = contentEl.createDiv({ cls: "annotation-modal-preview" });
    previewEl.createEl("strong", { text: "\u6807\u6CE8\u6587\u5B57\uFF1A" });
    const previewText = this.annotation.text.length > 50 ? this.annotation.text.substring(0, 50) + "..." : this.annotation.text;
    previewEl.createEl("span", { text: previewText });
    const colorContainer = contentEl.createDiv({ cls: "annotation-color-picker" });
    colorContainer.createEl("label", { text: "\u6807\u6CE8\u989C\u8272\uFF1A" });
    const colors = ["red", "yellow", "green", "blue", "purple", "none"];
    colors.forEach((c) => {
      const btn = colorContainer.createEl("button", { cls: `annotation-color-dot color-${c}` });
      btn.title = COLOR_LABELS[c];
      if (c === this.currentColor) {
        btn.addClass("active");
      }
      btn.addEventListener("click", () => {
        colorContainer.querySelectorAll(".annotation-color-dot").forEach((b) => b.removeClass("active"));
        btn.addClass("active");
        this.currentColor = c;
      });
    });
    const noteContainer = contentEl.createDiv({ cls: "annotation-note-container" });
    noteContainer.createEl("label", { text: "\u6279\u6CE8\u5185\u5BB9\uFF08\u6700\u591A400\u5B57\uFF09\uFF1A" });
    this.noteInput = noteContainer.createEl("textarea", { cls: "annotation-note-input" });
    this.noteInput.setAttribute("maxlength", "400");
    this.noteInput.setAttribute("rows", "4");
    this.noteInput.setAttribute("placeholder", "\u8BF7\u8F93\u5165\u6279\u6CE8\u5185\u5BB9...");
    this.noteInput.value = this.annotation.note;
    const charCount = noteContainer.createDiv({ cls: "annotation-char-count", text: `${this.annotation.note.length}/400` });
    this.noteInput.addEventListener("input", () => {
      var _a, _b;
      const len = (_b = (_a = this.noteInput) == null ? void 0 : _a.value.length) != null ? _b : 0;
      charCount.textContent = `${len}/400`;
    });
    const rubySection = contentEl.createDiv({ cls: "annotation-ruby-section" });
    const rubyRow = rubySection.createDiv({ cls: "annotation-ruby-row" });
    const rubyCheckbox = rubyRow.createEl("input", { type: "checkbox", cls: "annotation-ruby-checkbox" });
    rubyCheckbox.checked = this.rubyTextEnabled;
    rubyCheckbox.addEventListener("change", () => {
      var _a;
      this.rubyTextEnabled = rubyCheckbox.checked;
      if (this.rubyTextEnabled) {
        this.rubyTextContainer.style.display = "block";
        this.rubyTextInput.focus();
      } else {
        this.rubyTextContainer.style.display = "none";
        this.rubyTexts = [];
        (_a = this.updateRubyList) == null ? void 0 : _a.call(this);
      }
    });
    rubyRow.createEl("label", { text: "\u6CE8\u97F3" });
    this.rubyTextContainer = rubySection.createDiv({ cls: "annotation-ruby-input-container" });
    this.rubyTextContainer.style.display = this.rubyTextEnabled ? "block" : "none";
    this.rubyPreview = this.rubyTextContainer.createDiv({ cls: "annotation-ruby-preview" });
    this.rubyPreview.createEl("label", { text: "\u5212\u9009\u9700\u8981\u6CE8\u97F3\u7684\u6587\u5B57\uFF1A" });
    this.rubyTextPreview = this.rubyPreview.createDiv({ cls: "annotation-ruby-text-preview", text: this.annotation.text });
    this.rubyTextPreview.setAttribute("data-selected-text", this.annotation.text);
    const rubyInputRow = this.rubyTextContainer.createDiv({ cls: "annotation-ruby-input-row" });
    rubyInputRow.createEl("label", { text: "\u6CE8\u97F3\u5185\u5BB9\uFF1A" });
    this.rubyTextInput = rubyInputRow.createEl("input", { type: "text", cls: "annotation-ruby-input", placeholder: "\u8F93\u5165\u6CE8\u97F3\u5185\u5BB9..." });
    this.rubyTextPreview.addEventListener("mouseup", () => {
      setTimeout(() => {
        const selection = window.getSelection();
        if (selection && !selection.isCollapsed) {
          const selectedRubyText = selection.toString();
          const fullText = this.rubyTextPreview.textContent || "";
          const startIndex = fullText.indexOf(selectedRubyText);
          if (startIndex !== -1) {
            this.selectedRubyRange = { start: startIndex, end: startIndex + selectedRubyText.length };
          }
        }
      }, 10);
    });
    this.rubyTextInput.addEventListener("focus", () => {
      if (this.selectedRubyRange) {
        const selection = window.getSelection();
        if (selection) {
          const fullText = this.rubyTextPreview.textContent || "";
          const textNode = this.rubyTextPreview.firstChild;
          if (textNode) {
            const range = document.createRange();
            range.setStart(textNode, this.selectedRubyRange.start);
            range.setEnd(textNode, this.selectedRubyRange.end);
            selection.removeAllRanges();
            selection.addRange(range);
          }
        }
      }
    });
    const addRubyBtn = rubyInputRow.createEl("button", { text: "\u6DFB\u52A0", cls: "annotation-btn annotation-btn-small" });
    addRubyBtn.addEventListener("click", () => {
      var _a, _b;
      const selection = window.getSelection();
      let selectedRubyText = "";
      if (selection && !selection.isCollapsed) {
        selectedRubyText = selection.toString();
      } else if (this.selectedRubyRange) {
        selectedRubyText = this.annotation.text.substring(this.selectedRubyRange.start, this.selectedRubyRange.end);
      }
      if (selectedRubyText && this.rubyTextInput.value.trim()) {
        const fullText = this.rubyTextPreview.textContent || "";
        const startIndex = fullText.indexOf(selectedRubyText);
        if (startIndex !== -1) {
          this.rubyTexts.push({
            startIndex,
            length: selectedRubyText.length,
            ruby: this.rubyTextInput.value.trim()
          });
          this.rubyTextInput.value = "";
          this.selectedRubyRange = null;
          if (selection) {
            selection.removeAllRanges();
          }
          (_a = this.updateRubyList) == null ? void 0 : _a.call(this);
        }
      } else {
        if (!selectedRubyText) {
          if (this.annotation.text.length === 1) {
            this.rubyTexts.push({
              startIndex: 0,
              length: 1,
              ruby: this.rubyTextInput.value.trim()
            });
            this.rubyTextInput.value = "";
            this.selectedRubyRange = null;
            (_b = this.updateRubyList) == null ? void 0 : _b.call(this);
          } else {
            new import_obsidian3.Notice("\u8BF7\u5148\u5212\u9009\u9700\u8981\u6CE8\u97F3\u7684\u6587\u5B57");
          }
        } else {
          new import_obsidian3.Notice("\u8BF7\u8F93\u5165\u6CE8\u97F3\u5185\u5BB9");
        }
      }
    });
    const rubyListContainer = this.rubyTextContainer.createDiv({ cls: "annotation-ruby-list-container" });
    rubyListContainer.createEl("label", { text: "\u5DF2\u6DFB\u52A0\u7684\u6CE8\u97F3\uFF1A" });
    const rubyList = rubyListContainer.createDiv({ cls: "annotation-ruby-list" });
    this.updateRubyList = () => {
      rubyList.empty();
      if (this.rubyTexts.length === 0) {
        rubyList.createDiv({ text: "\u6682\u65E0\u6CE8\u97F3", cls: "annotation-ruby-empty" });
      } else {
        this.rubyTexts.forEach((ruby, index) => {
          const item = rubyList.createDiv({ cls: "annotation-ruby-item" });
          const textPart = item.createSpan({ text: `${this.annotation.text.substring(ruby.startIndex, ruby.startIndex + ruby.length)} \u2192 ${ruby.ruby}`, cls: "annotation-ruby-item-text" });
          const deleteBtn = item.createEl("button", { text: "\xD7", cls: "annotation-ruby-item-delete" });
          deleteBtn.addEventListener("click", (e) => {
            var _a;
            e.stopPropagation();
            this.rubyTexts.splice(index, 1);
            (_a = this.updateRubyList) == null ? void 0 : _a.call(this);
          });
        });
      }
    };
    this.updateRubyList();
    const buttonContainer = contentEl.createDiv({ cls: "annotation-modal-buttons" });
    buttonContainer.createEl("button", { text: "\u53D6\u6D88", cls: "annotation-btn annotation-btn-secondary" }).addEventListener("click", () => {
      this.close();
    });
    const saveBtn = buttonContainer.createEl("button", { text: "\u4FDD\u5B58", cls: "annotation-btn annotation-btn-primary" });
    saveBtn.addEventListener("click", () => {
      var _a, _b;
      const note = (_b = (_a = this.noteInput) == null ? void 0 : _a.value) != null ? _b : "";
      const rubyTexts = this.rubyTextEnabled && this.rubyTexts.length > 0 ? this.rubyTexts : void 0;
      this.onSave(note, this.currentColor, rubyTexts);
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/annotationListPanel.ts
var import_obsidian4 = require("obsidian");
var AnnotationListPanel = class {
  constructor(app, dataManager) {
    this.panelEl = null;
    this.listBtn = null;
    this.filePath = null;
    this.onUpdate = null;
    this.previewContainer = null;
    this.sortOption = "position-asc";
    this.app = app;
    this.dataManager = dataManager;
  }
  show(filePath, previewContainer, onUpdate) {
    this.filePath = filePath;
    this.previewContainer = previewContainer;
    this.onUpdate = onUpdate;
    this.hide();
    this.createListButton();
  }
  createListButton() {
    if (!this.previewContainer) return;
    this.listBtn = document.createElement("div");
    this.listBtn.className = "annotation-list-btn";
    this.listBtn.innerHTML = `<span>\u{1F4DD}</span>`;
    this.listBtn.title = "\u67E5\u770B\u6807\u6CE8";
    const containerRect = this.previewContainer.getBoundingClientRect();
    this.listBtn.style.position = "absolute";
    this.listBtn.style.right = "8px";
    this.listBtn.style.top = "50%";
    this.listBtn.style.transform = "translateY(-50%)";
    this.previewContainer.style.position = "relative";
    this.previewContainer.appendChild(this.listBtn);
    this.listBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      if (this.panelEl && this.panelEl.style.display !== "none") {
        this.hidePanel();
      } else {
        this.showPanel();
      }
    });
  }
  async showPanel() {
    if (!this.filePath || !this.previewContainer) return;
    this.panelEl = document.createElement("div");
    this.panelEl.className = "annotation-list-panel";
    const header = this.panelEl.createDiv({ cls: "annotation-list-header" });
    header.createEl("span", { text: "\u6807\u6CE8\u5217\u8868", cls: "annotation-list-title" });
    const sortContainer = header.createDiv({ cls: "annotation-list-sort-container" });
    const sortSelect = sortContainer.createEl("select", { cls: "annotation-list-sort-select" });
    sortSelect.innerHTML = `
      <option value="position-asc" ${this.sortOption === "position-asc" ? "selected" : ""}>\u6309\u5185\u5BB9\u987A\u5E8F\uFF08\u4ECE\u4E0A\u5230\u4E0B\uFF09</option>
      <option value="position-desc" ${this.sortOption === "position-desc" ? "selected" : ""}>\u6309\u5185\u5BB9\u5012\u5E8F\uFF08\u4ECE\u4E0B\u5230\u4E0A\uFF09</option>
      <option value="time-asc" ${this.sortOption === "time-asc" ? "selected" : ""}>\u6309\u65F6\u95F4\u6B63\u5E8F\uFF08\u4ECE\u65E7\u5230\u65B0\uFF09</option>
      <option value="time-desc" ${this.sortOption === "time-desc" ? "selected" : ""}>\u6309\u65F6\u95F4\u5012\u5E8F\uFF08\u4ECE\u65B0\u5230\u65E7\uFF09</option>
    `;
    sortSelect.addEventListener("change", () => {
      this.sortOption = sortSelect.value;
      this.refreshContent();
    });
    const closeBtn = header.createEl("button", { cls: "annotation-list-close", text: "\xD7" });
    closeBtn.addEventListener("click", () => this.hidePanel());
    const content = this.panelEl.createDiv({ cls: "annotation-list-content" });
    this.renderContent(content);
    this.previewContainer.appendChild(this.panelEl);
    const containerRect = this.previewContainer.getBoundingClientRect();
    this.panelEl.style.position = "absolute";
    this.panelEl.style.right = "60px";
    this.panelEl.style.top = "50%";
    this.panelEl.style.transform = "translateY(-50%)";
    const clickHandler = (e) => {
      if (this.panelEl && !this.panelEl.contains(e.target) && (!this.listBtn || !this.listBtn.contains(e.target))) {
        this.hidePanel();
        document.removeEventListener("click", clickHandler);
      }
    };
    setTimeout(() => document.addEventListener("click", clickHandler), 10);
  }
  async renderContent(content) {
    content.empty();
    if (!this.filePath) {
      content.createDiv({
        cls: "annotation-list-empty",
        text: "\u6682\u65E0\u6807\u6CE8"
      });
      return;
    }
    const data = await this.dataManager.loadAnnotations(this.filePath);
    if (!data || data.annotations.length === 0) {
      content.createDiv({
        cls: "annotation-list-empty",
        text: "\u6682\u65E0\u6807\u6CE8"
      });
      return;
    }
    let annotations = [...data.annotations];
    switch (this.sortOption) {
      case "position-asc":
        annotations.sort((a, b) => a.positionPercent - b.positionPercent);
        break;
      case "position-desc":
        annotations.sort((a, b) => b.positionPercent - a.positionPercent);
        break;
      case "time-asc":
        annotations.sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime());
        break;
      case "time-desc":
        annotations.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
        break;
    }
    annotations.forEach((annotation) => {
      const item = content.createDiv({ cls: "annotation-list-item" });
      const colorDot = item.createSpan({
        cls: `annotation-list-dot color-${annotation.color}`
      });
      const textPreview = item.createDiv({ cls: "annotation-list-text" });
      const previewText = annotation.text.length > 60 ? annotation.text.substring(0, 60) + "..." : annotation.text;
      textPreview.textContent = previewText;
      if (annotation.note) {
        const notePreview = item.createDiv({ cls: "annotation-list-note" });
        const noteText = annotation.note.length > 100 ? annotation.note.substring(0, 100) + "..." : annotation.note;
        notePreview.textContent = `\u{1F4DD} ${noteText}`;
      }
      item.addEventListener("click", () => {
        this.scrollToAnnotation(annotation);
      });
      item.addEventListener("contextmenu", (e) => {
        e.preventDefault();
        e.stopPropagation();
        this.showContextMenu(annotation, e.clientX, e.clientY);
      });
    });
  }
  async refreshContent() {
    if (!this.panelEl) return;
    const content = this.panelEl.querySelector(".annotation-list-content");
    if (content) {
      await this.renderContent(content);
    }
  }
  showContextMenu(annotation, x, y) {
    const menu = document.createElement("div");
    menu.className = "annotation-context-menu";
    const detailBtn = menu.createEl("button", { text: "\u6807\u6CE8\u8BE6\u60C5", cls: "annotation-context-menu-item" });
    detailBtn.addEventListener("click", () => {
      this.showAnnotationDetail(annotation);
      menu.remove();
    });
    const deleteBtn = menu.createEl("button", { text: "\u5220\u9664\u6807\u6CE8", cls: "annotation-context-menu-item annotation-context-menu-danger" });
    deleteBtn.addEventListener("click", async () => {
      await this.deleteAnnotation(annotation);
      menu.remove();
    });
    document.body.appendChild(menu);
    const menuWidth = 120;
    const menuHeight = menu.offsetHeight || 80;
    let menuX = x + 10;
    let menuY = y + 10;
    if (menuX + menuWidth > window.innerWidth) {
      menuX = x - menuWidth - 10;
    }
    if (menuY + menuHeight > window.innerHeight) {
      menuY = window.innerHeight - menuHeight - 10;
    }
    menu.style.left = `${Math.max(10, menuX)}px`;
    menu.style.top = `${Math.max(10, menuY)}px`;
    const clickHandler = (e) => {
      if (!menu.contains(e.target)) {
        menu.remove();
        document.removeEventListener("click", clickHandler);
      }
    };
    setTimeout(() => document.addEventListener("click", clickHandler), 10);
  }
  showAnnotationDetail(annotation) {
    const highlightEl = this.findAnnotationElement(annotation.id);
    if (highlightEl) {
      highlightEl.scrollIntoView({ behavior: "smooth", block: "center" });
      const rect = highlightEl.getBoundingClientRect();
      setTimeout(() => {
        const clickEvent = new MouseEvent("click", {
          bubbles: true,
          cancelable: true,
          clientX: rect.left + rect.width / 2,
          clientY: rect.top + rect.height / 2
        });
        highlightEl.dispatchEvent(clickEvent);
      }, 300);
    }
    this.hidePanel();
  }
  async deleteAnnotation(annotation) {
    if (!this.filePath) return;
    await this.dataManager.deleteAnnotation(this.filePath, annotation.id);
    new import_obsidian4.Notice("\u6807\u6CE8\u5DF2\u5220\u9664");
    this.hidePanel();
    if (this.onUpdate) {
      this.onUpdate();
    }
  }
  findAnnotationElement(annotationId) {
    if (!annotationId) return null;
    const highlightEl = document.querySelector(`[data-annotation-id="${annotationId}"]`);
    return highlightEl;
  }
  scrollToAnnotation(annotation) {
    const highlightEl = this.findAnnotationElement(annotation.id);
    if (highlightEl) {
      highlightEl.scrollIntoView({ behavior: "smooth", block: "center" });
      highlightEl.style.transition = "box-shadow 0.3s ease";
      highlightEl.style.boxShadow = "0 0 0 3px var(--interactive-accent)";
      setTimeout(() => {
        highlightEl.style.boxShadow = "";
      }, 2e3);
    }
    this.hidePanel();
  }
  hidePanel() {
    if (this.panelEl) {
      this.panelEl.remove();
      this.panelEl = null;
    }
  }
  hide() {
    this.hidePanel();
    if (this.listBtn) {
      this.listBtn.remove();
      this.listBtn = null;
    }
  }
};

// src/annotationMode.ts
var LeafAnnotationState = class {
  constructor(leaf, app, dataManager) {
    this.isActive = false;
    this.currentView = null;
    this.currentFilePath = null;
    this.currentFileContent = "";
    this.renderer = null;
    this.mouseUpHandler = null;
    this.clickHandler = null;
    this.leaf = leaf;
    this.app = app;
    this.dataManager = dataManager;
    this.selectionMenu = new SelectionMenu(app, dataManager);
    this.annotationMenu = new AnnotationMenu(app, dataManager);
    this.annotationListPanel = new AnnotationListPanel(app, dataManager);
  }
  async activate(file) {
    const view = this.leaf.view;
    if (!view) {
      new import_obsidian5.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2AMarkdown\u6587\u4EF6");
      return;
    }
    if (view.getMode() !== "preview") {
      view.setState({ mode: "preview" }, { history: false });
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
    this.currentView = view;
    this.currentFilePath = file.path;
    this.currentFileContent = await this.app.vault.cachedRead(file);
    this.isActive = true;
    this.addAnnotationCursorStyle();
    this.renderer = new AnnotationRenderer(view);
    await this.loadAndRenderAnnotations();
    this.setupEventListeners();
    const previewContainer = this.currentView.previewMode.containerEl;
    this.annotationListPanel.show(this.currentFilePath, previewContainer, async () => {
      var _a;
      (_a = this.renderer) == null ? void 0 : _a.clear();
      await this.loadAndRenderAnnotations();
    });
    new import_obsidian5.Notice("\u6807\u6CE8\u6A21\u5F0F\u5DF2\u5F00\u542F");
  }
  deactivate() {
    if (!this.isActive) return;
    this.removeEventListeners();
    this.removeAnnotationCursorStyle();
    if (this.renderer) {
      this.renderer.clear();
      this.renderer = null;
    }
    this.selectionMenu.hide();
    this.annotationMenu.hide();
    this.annotationListPanel.hide();
    this.currentView = null;
    this.currentFilePath = null;
    this.currentFileContent = "";
    this.isActive = false;
    new import_obsidian5.Notice("\u6807\u6CE8\u6A21\u5F0F\u5DF2\u5173\u95ED");
  }
  addAnnotationCursorStyle() {
    document.body.classList.add("annotation-mode-active");
  }
  removeAnnotationCursorStyle() {
    document.body.classList.remove("annotation-mode-active");
  }
  async loadAndRenderAnnotations() {
    if (!this.currentFilePath || !this.renderer || !this.currentView) return;
    this.dataManager.clearCache();
    await new Promise((resolve) => setTimeout(resolve, 100));
    const previewEl = this.currentView.previewMode.containerEl;
    const allMarks = Array.from(previewEl.querySelectorAll("mark[data-annotation-id]"));
    const allRubies = Array.from(previewEl.querySelectorAll("ruby"));
    if (allMarks.length > 0) {
      for (const mark of allMarks) {
        if (!document.contains(mark)) {
          continue;
        }
        const parent = mark.parentNode;
        if (parent) {
          let textContent = "";
          const walker = document.createTreeWalker(mark, NodeFilter.SHOW_TEXT, null);
          let node = walker.nextNode();
          while (node) {
            const textNode2 = node;
            const parentElement = textNode2.parentElement;
            if (parentElement && parentElement.tagName !== "RT") {
              textContent += textNode2.textContent;
            }
            node = walker.nextNode();
          }
          const textNode = document.createTextNode(textContent);
          parent.replaceChild(textNode, mark);
        }
      }
    }
    const rubiesAfterMarks = Array.from(previewEl.querySelectorAll("ruby"));
    if (rubiesAfterMarks.length > 0) {
      for (const ruby of rubiesAfterMarks) {
        if (!document.contains(ruby)) {
          continue;
        }
        const parent = ruby.parentNode;
        if (parent) {
          let textContent = "";
          const walker = document.createTreeWalker(ruby, NodeFilter.SHOW_TEXT, null);
          let node = walker.nextNode();
          while (node) {
            const textNode2 = node;
            const parentElement = textNode2.parentElement;
            if (parentElement && parentElement.tagName !== "RT") {
              textContent += textNode2.textContent;
            }
            node = walker.nextNode();
          }
          const textNode = document.createTextNode(textContent);
          parent.replaceChild(textNode, ruby);
        }
      }
    }
    await new Promise((resolve) => setTimeout(resolve, 200));
    this.mergeAdjacentTextNodes(previewEl);
    const data = await this.dataManager.loadAnnotations(this.currentFilePath);
    if (!data || data.annotations.length === 0) {
      return;
    }
    await new Promise((resolve) => setTimeout(resolve, 100));
    this.renderer.setAnnotations(data.annotations);
    const result = this.renderer.renderByText(previewEl);
    if (result.updatedContexts.length > 0) {
      for (const update of result.updatedContexts) {
        await this.dataManager.updateAnnotation(this.currentFilePath, update.id, {
          contextBefore: update.contextBefore,
          contextAfter: update.contextAfter,
          positionPercent: update.positionPercent
        });
      }
    }
    if (result.lostAnnotations.length > 0) {
      new import_obsidian5.Notice(`${result.lostAnnotations.length} \u6761\u6807\u6CE8\u5185\u5BB9\u5DF2\u4E22\u5931`, 5e3);
    }
  }
  setupEventListeners() {
    this.mouseUpHandler = (e) => this.handleMouseUp(e);
    this.clickHandler = (e) => this.handleClick(e);
    document.addEventListener("mouseup", this.mouseUpHandler);
    document.addEventListener("click", this.clickHandler, true);
  }
  removeEventListeners() {
    if (this.mouseUpHandler) {
      document.removeEventListener("mouseup", this.mouseUpHandler);
      this.mouseUpHandler = null;
    }
    if (this.clickHandler) {
      document.removeEventListener("click", this.clickHandler, true);
      this.clickHandler = null;
    }
  }
  handleMouseUp(e) {
    if (!this.isActive || !this.currentView || !this.currentFilePath) return;
    if (this.currentView.getMode() === "source") {
      this.deactivate();
      return;
    }
    const previewEl = this.currentView.previewMode.containerEl;
    if (!previewEl.contains(e.target)) return;
    const target = e.target;
    if (target.classList.contains("annotation-highlight") || target.closest(".annotation-card-menu")) return;
    setTimeout(async () => {
      const selection = window.getSelection();
      if (!selection || selection.isCollapsed) return;
      const range = selection.getRangeAt(0);
      let selectedText = this.getCleanTextFromRange(range).trim();
      if (!selectedText) return;
      const extractedRubyInfo = this.extractRubyInfoFromSelection(range, selectedText);
      const partialAnnotationInfo = this.extractPartialAnnotationInfo(range, selectedText, previewEl);
      const contextInfo = this.extractContextFromSelection(range, previewEl);
      if (contextInfo) {
        this.selectionMenu.show(
          e.clientX,
          e.clientY,
          selectedText,
          contextInfo.contextBefore,
          contextInfo.contextAfter,
          contextInfo.positionPercent,
          this.currentFilePath,
          async () => {
            var _a;
            const file = this.app.workspace.getActiveFile();
            if (file) {
              this.currentFileContent = await this.app.vault.cachedRead(file);
            }
            (_a = this.renderer) == null ? void 0 : _a.clear();
            await this.loadAndRenderAnnotations();
          },
          extractedRubyInfo || void 0,
          partialAnnotationInfo || void 0
        );
      }
    }, 10);
  }
  handleClick(e) {
    if (!this.isActive || !this.currentView || !this.currentFilePath || !this.renderer) return;
    if (this.currentView.getMode() === "source") {
      this.deactivate();
      return;
    }
    const selection = window.getSelection();
    if (selection && !selection.isCollapsed) {
      return;
    }
    const target = e.target;
    const highlightTarget = target.closest("[data-annotation-id]");
    if (!highlightTarget) return;
    e.preventDefault();
    e.stopPropagation();
    const annotationId = highlightTarget.dataset.annotationId;
    if (!annotationId) return;
    this.showAnnotationMenu(annotationId, e.clientX, e.clientY);
  }
  showAnnotationMenu(annotationId, x, y) {
    if (!this.currentFilePath) return;
    const data = this.dataManager.loadAnnotations(this.currentFilePath);
    data == null ? void 0 : data.then((d) => {
      if (!d) return;
      const annotation = d.annotations.find((a) => a.id === annotationId);
      if (annotation) {
        this.annotationMenu.show(x, y, annotation, this.currentFilePath, async () => {
          var _a;
          (_a = this.renderer) == null ? void 0 : _a.clear();
          await this.loadAndRenderAnnotations();
        });
      }
    });
  }
  getCleanTextFromRange(range) {
    const container = range.cloneContents();
    const rtElements = container.querySelectorAll("rt");
    rtElements.forEach((rt) => rt.remove());
    return container.textContent || "";
  }
  mergeAdjacentTextNodes(container) {
    const walker = document.createTreeWalker(container, NodeFilter.SHOW_TEXT, null);
    const textNodes = [];
    let node = walker.nextNode();
    while (node) {
      textNodes.push(node);
      node = walker.nextNode();
    }
    let mergeCount = 0;
    for (const textNode of textNodes) {
      let current = textNode;
      while (current.nextSibling && current.nextSibling.nodeType === Node.TEXT_NODE) {
        const nextText = current.nextSibling;
        if (current.textContent && nextText.textContent) {
          current.textContent += nextText.textContent;
          nextText.remove();
          mergeCount++;
        } else {
          current = nextText;
        }
      }
    }
  }
  extractContextFromSelection(range, container) {
    var _a;
    const textNodes = this.getAllTextNodes(container, false);
    let fullText = "";
    const nodeStartOffsets = /* @__PURE__ */ new Map();
    for (const node of textNodes) {
      const parent = node.parentElement;
      if (parent && parent.tagName === "RT") {
        continue;
      }
      nodeStartOffsets.set(node, fullText.length);
      fullText += (_a = node.textContent) != null ? _a : "";
    }
    let startGlobalOffset = -1;
    let endGlobalOffset = -1;
    const startContainer = range.startContainer;
    const endContainer = range.endContainer;
    const startOffset = range.startOffset;
    const endOffset = range.endOffset;
    if (startContainer.nodeType === Node.TEXT_NODE) {
      const parent = startContainer.parentElement;
      if (parent && parent.tagName !== "RT") {
        const startOffsetInFullText = nodeStartOffsets.get(startContainer);
        if (startOffsetInFullText !== void 0) {
          startGlobalOffset = startOffsetInFullText + startOffset;
        }
      }
    }
    if (endContainer.nodeType === Node.TEXT_NODE) {
      const parent = endContainer.parentElement;
      if (parent && parent.tagName !== "RT") {
        const endOffsetInFullText = nodeStartOffsets.get(endContainer);
        if (endOffsetInFullText !== void 0) {
          endGlobalOffset = endOffsetInFullText + endOffset;
        }
      }
    }
    if (startGlobalOffset === -1 || endGlobalOffset === -1) {
      return null;
    }
    const textLength = fullText.length;
    const positionPercent = textLength > 0 ? (startGlobalOffset + endGlobalOffset) / 2 / textLength * 100 : 50;
    const contextBefore = fullText.substring(Math.max(0, startGlobalOffset - 50), startGlobalOffset);
    const contextAfter = fullText.substring(endGlobalOffset, Math.min(fullText.length, endGlobalOffset + 50));
    return { contextBefore, contextAfter, positionPercent };
  }
  getAllTextNodes(container, excludeAnnotated = true) {
    const textNodes = [];
    const walker = document.createTreeWalker(container, NodeFilter.SHOW_TEXT, null);
    let node = walker.nextNode();
    while (node) {
      const textNode = node;
      if (textNode.textContent && textNode.textContent.trim().length > 0) {
        const parent = textNode.parentElement;
        if (parent && parent.tagName !== "RT" && (!excludeAnnotated || !parent.closest("[data-annotation-id]")) && !parent.closest("div.inline-title") && !parent.closest("[class*='metadata-']") && !parent.closest("div.multi-select-pill-content") && !parent.closest("div.metadata-content") && !parent.closest("div.mod-header") && !parent.closest("div.mod-ui")) {
          textNodes.push(textNode);
        }
      }
      node = walker.nextNode();
    }
    return textNodes;
  }
  extractPartialAnnotationInfo(range, selectedText, container) {
    var _a;
    const startContainer = range.startContainer;
    const annotatedElement = startContainer.nodeType === Node.TEXT_NODE ? (_a = startContainer.parentElement) == null ? void 0 : _a.closest("mark[data-annotation-id]") : startContainer.closest("mark[data-annotation-id]");
    if (!annotatedElement) {
      return null;
    }
    const annotationId = annotatedElement.getAttribute("data-annotation-id");
    if (!annotationId) {
      return null;
    }
    const annotatedText = this.getCleanTextFromElement(annotatedElement);
    const startIndex = this.calculateOffsetFromRange(range, annotatedElement);
    if (startIndex === -1) {
      return null;
    }
    return {
      annotationId,
      startIndex,
      length: selectedText.length,
      rubyText: ""
    };
  }
  calculateOffsetFromRange(range, annotatedElement) {
    let offset = 0;
    const walker = document.createTreeWalker(annotatedElement, NodeFilter.SHOW_TEXT, null);
    const startContainer = range.startContainer;
    let node = walker.nextNode();
    while (node) {
      const textNode = node;
      const parentElement = textNode.parentElement;
      if (parentElement && parentElement.tagName !== "RT") {
        if (textNode === startContainer) {
          return offset + range.startOffset;
        }
        offset += (textNode.textContent || "").length;
      }
      node = walker.nextNode();
    }
    return -1;
  }
  getCleanTextFromElement(element) {
    let text = "";
    const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT, null);
    let node = walker.nextNode();
    while (node) {
      const textNode = node;
      const parentElement = textNode.parentElement;
      if (parentElement && parentElement.tagName !== "RT") {
        text += textNode.textContent || "";
      }
      node = walker.nextNode();
    }
    return text;
  }
  extractRubyInfoFromSelection(range, selectedText) {
    var _a;
    const rubyInfo = {
      annotationIds: [],
      rubyTexts: []
    };
    const allRubyElements = Array.from(document.querySelectorAll("ruby"));
    if (allRubyElements.length === 0) return null;
    for (const ruby of allRubyElements) {
      if (!range.intersectsNode(ruby)) {
        continue;
      }
      let rubyReading = "";
      let rubyFullText = "";
      const span = ruby.querySelector("span");
      const rb = ruby.querySelector("rb");
      const rt = ruby.querySelector("rt");
      if (span && rt) {
        rubyFullText = span.textContent || "";
        rubyReading = rt.textContent || "";
      } else if (rb && rt) {
        rubyFullText = rb.textContent || "";
        rubyReading = rt.textContent || "";
      } else {
        const textNodes2 = Array.from(ruby.childNodes).filter((n) => n.nodeType === Node.TEXT_NODE);
        const rtNodes = Array.from(ruby.querySelectorAll("rt"));
        if (textNodes2.length > 0 && rtNodes.length > 0) {
          rubyFullText = textNodes2.map((n) => n.textContent || "").join("");
          const firstRt = rtNodes[0];
          if (firstRt) {
            rubyReading = firstRt.textContent || "";
          }
        }
      }
      if (!rubyFullText || !rubyReading) {
        continue;
      }
      const rubyRange = document.createRange();
      rubyRange.selectNodeContents(ruby);
      const intersectionRange = this.getIntersectionRange(range, rubyRange);
      if (!intersectionRange) {
        continue;
      }
      let intersectedRubyText = rubyFullText;
      const compareStart = range.compareBoundaryPoints(Range.START_TO_START, rubyRange);
      const compareEnd = range.compareBoundaryPoints(Range.END_TO_END, rubyRange);
      if (compareStart > 0 || compareEnd < 0) {
        intersectedRubyText = "";
        const textNodes2 = Array.from(ruby.childNodes).filter((n) => {
          if (n.nodeType !== Node.TEXT_NODE) return false;
          const parent = n.parentElement;
          return !!parent && parent.tagName !== "RT";
        });
        for (const textNode of textNodes2) {
          const nodeRange = document.createRange();
          nodeRange.selectNodeContents(textNode);
          const nodeIntersection = this.getIntersectionRange(range, nodeRange);
          if (nodeIntersection) {
            const clonedNode = nodeIntersection.cloneContents();
            const nodeText = Array.from(clonedNode.childNodes).filter((n) => n.nodeType === Node.TEXT_NODE).map((n) => n.textContent || "").join("");
            intersectedRubyText += nodeText;
          }
        }
      }
      intersectedRubyText = intersectedRubyText.trim();
      if (!intersectedRubyText) {
        continue;
      }
      const container = this.findContainerForOffsetCalculation(ruby);
      if (!container) {
        continue;
      }
      const textNodes = this.getAllTextNodes(container, false);
      const nodeStartOffsets = /* @__PURE__ */ new Map();
      let fullText = "";
      for (const node of textNodes) {
        const parent = node.parentElement;
        if (parent && parent.tagName === "RT") {
          continue;
        }
        nodeStartOffsets.set(node, fullText.length);
        fullText += (_a = node.textContent) != null ? _a : "";
      }
      let startGlobalOffset = -1;
      const startContainer = range.startContainer;
      const startOffset = range.startOffset;
      if (startContainer.nodeType === Node.TEXT_NODE) {
        const parent = startContainer.parentElement;
        if (parent && parent.tagName !== "RT") {
          const startOffsetInFullText = nodeStartOffsets.get(startContainer);
          if (startOffsetInFullText !== void 0) {
            startGlobalOffset = startOffsetInFullText + startOffset;
          }
        }
      } else {
        const startRange = document.createRange();
        startRange.setStart(range.startContainer, range.startOffset);
        startRange.setEnd(range.startContainer, range.startOffset);
        for (const [node, offset] of nodeStartOffsets) {
          const nodeRange = document.createRange();
          nodeRange.selectNodeContents(node);
          if (startRange.intersectsNode(node)) {
            startGlobalOffset = offset;
            break;
          }
        }
      }
      if (startGlobalOffset === -1) {
        continue;
      }
      let rubyGlobalOffset = -1;
      const rubyTextElement = span || rb || ruby;
      if (rubyTextElement === ruby) {
        const textNodes2 = Array.from(ruby.childNodes).filter((n) => {
          if (n.nodeType !== Node.TEXT_NODE) return false;
          const parent = n.parentElement;
          return !!parent && parent.tagName !== "RT";
        });
        if (textNodes2.length > 0) {
          const firstTextNode = textNodes2[0];
          const offset = nodeStartOffsets.get(firstTextNode);
          if (offset !== void 0) {
            rubyGlobalOffset = offset;
          }
        }
      } else {
        const firstChild = rubyTextElement.firstChild;
        if (firstChild && firstChild.nodeType === Node.TEXT_NODE) {
          const offset = nodeStartOffsets.get(firstChild);
          if (offset !== void 0) {
            rubyGlobalOffset = offset;
          }
        }
      }
      if (rubyGlobalOffset === -1) {
        continue;
      }
      let startIndexInSelected = rubyGlobalOffset - startGlobalOffset;
      if (compareStart > 0) {
        const intersectionStartContainer = intersectionRange.startContainer;
        const intersectionStartOffset = intersectionRange.startOffset;
        if (intersectionStartContainer.nodeType === Node.TEXT_NODE) {
          const offsetInNode = nodeStartOffsets.get(intersectionStartContainer);
          if (offsetInNode !== void 0) {
            const intersectionGlobalOffset = offsetInNode + intersectionStartOffset;
            startIndexInSelected = intersectionGlobalOffset - startGlobalOffset;
          }
        }
      }
      if (startIndexInSelected < 0) {
        continue;
      }
      rubyInfo.rubyTexts.push({
        startIndex: startIndexInSelected,
        length: intersectedRubyText.length,
        ruby: rubyReading
      });
      const markedAncestor = ruby.closest("mark[data-annotation-id]");
      if (markedAncestor) {
        const annotationId = markedAncestor.getAttribute("data-annotation-id");
        if (annotationId && !rubyInfo.annotationIds.includes(annotationId)) {
          rubyInfo.annotationIds.push(annotationId);
        }
      }
    }
    return rubyInfo.rubyTexts.length > 0 ? rubyInfo : null;
  }
  findContainerForOffsetCalculation(ruby) {
    let container = ruby;
    while (container && container.tagName !== "BODY") {
      if (container.classList.contains("markdown-preview-view")) {
        return container;
      }
      if (container.parentElement && container.parentElement.tagName === "BODY") {
        return container;
      }
      container = container.parentElement;
    }
    return ruby.parentElement;
  }
  extractRubyTextFromContainer(container) {
    const clonedRubyElements = Array.from(container.querySelectorAll("ruby"));
    if (clonedRubyElements.length > 0) {
      for (const clonedRuby of clonedRubyElements) {
        const clonedSpan = clonedRuby.querySelector("span");
        if (clonedSpan) {
          return clonedSpan.textContent || "";
        }
        const clonedRb = clonedRuby.querySelector("rb");
        if (clonedRb) {
          return clonedRb.textContent || "";
        }
        const textNodes2 = Array.from(clonedRuby.childNodes).filter((n) => n.nodeType === Node.TEXT_NODE);
        if (textNodes2.length > 0) {
          return textNodes2.map((n) => n.textContent || "").join("");
        }
      }
    }
    const textNodes = Array.from(container.childNodes).filter((n) => {
      if (n.nodeType !== Node.TEXT_NODE) return false;
      const parent = n.parentElement;
      return !!parent && parent.tagName !== "RT";
    });
    if (textNodes.length > 0) {
      return textNodes.map((n) => n.textContent || "").join("");
    }
    return "";
  }
  extractTextFromContainer(container) {
    const rubyElement = container.querySelector("ruby");
    if (rubyElement) {
      const span = rubyElement.querySelector("span");
      if (span) {
        return span.textContent || "";
      }
      const textNodes2 = Array.from(rubyElement.childNodes).filter((n) => n.nodeType === Node.TEXT_NODE);
      if (textNodes2.length > 0) {
        return textNodes2.map((n) => n.textContent || "").join("");
      }
    }
    const textNodes = Array.from(container.childNodes).filter((n) => n.nodeType === Node.TEXT_NODE);
    if (textNodes.length > 0) {
      return textNodes.map((n) => n.textContent || "").join("");
    }
    return null;
  }
  findCommonSubstring(str1, str2) {
    const len1 = str1.length;
    const len2 = str2.length;
    let result = "";
    for (let i = 0; i < len1; i++) {
      for (let j = i + 1; j <= len1; j++) {
        const substr = str1.substring(i, j);
        if (str2.includes(substr) && substr.length > result.length) {
          result = substr;
        }
      }
    }
    return result.length > 0 ? result : null;
  }
  getIntersectionRange(rangeA, rangeB) {
    const compareA = rangeA.compareBoundaryPoints(Range.START_TO_START, rangeB);
    const compareB = rangeA.compareBoundaryPoints(Range.END_TO_END, rangeB);
    if (compareA >= 0 && compareB <= 0) {
      return rangeB.cloneRange();
    }
    if (compareA <= 0 && compareB >= 0) {
      return rangeA.cloneRange();
    }
    if (compareA >= 0) {
      return null;
    }
    if (compareB <= 0) {
      return null;
    }
    const result = document.createRange();
    result.setStart(rangeB.startContainer, rangeB.startOffset);
    result.setEnd(rangeA.endContainer, rangeA.endOffset);
    return result;
  }
  getIsActive() {
    return this.isActive;
  }
};
var AnnotationMode = class {
  constructor(app, dataManager) {
    this.leafStates = /* @__PURE__ */ new Map();
    this.fileOpenHandler = null;
    this.layoutChangeHandler = null;
    this.app = app;
    this.dataManager = dataManager;
    this.setupGlobalEventListeners();
  }
  toggle(file) {
    const leaf = this.app.workspace.activeLeaf;
    if (!leaf) return;
    const state = this.leafStates.get(leaf);
    if ((state == null ? void 0 : state.isActive) && state.currentFilePath === (file == null ? void 0 : file.path)) {
      this.deactivateForLeaf(leaf);
    } else if (file) {
      this.activateForLeaf(leaf, file);
    } else {
      new import_obsidian5.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2AMarkdown\u6587\u4EF6");
    }
  }
  async activateForLeaf(leaf, file) {
    let state = this.leafStates.get(leaf);
    if (!state) {
      state = new LeafAnnotationState(leaf, this.app, this.dataManager);
      this.leafStates.set(leaf, state);
    } else {
      if (state.currentFilePath !== file.path) {
        state.deactivate();
      }
    }
    await state.activate(file);
  }
  deactivateForLeaf(leaf) {
    const state = this.leafStates.get(leaf);
    if (state) {
      state.deactivate();
      this.leafStates.delete(leaf);
    }
  }
  deactivate() {
    for (const [leaf] of this.leafStates) {
      this.deactivateForLeaf(leaf);
    }
  }
  setupGlobalEventListeners() {
    this.fileOpenHandler = (file) => {
      const leaf = this.app.workspace.activeLeaf;
      if (!leaf) return;
      const state = this.leafStates.get(leaf);
      if (!(state == null ? void 0 : state.isActive)) return;
      if (file && file.path !== state.currentFilePath && file.extension === "md") {
        this.deactivateForLeaf(leaf);
      } else if (!file || file.extension !== "md") {
        this.deactivateForLeaf(leaf);
      }
    };
    this.app.workspace.on("file-open", this.fileOpenHandler);
    this.layoutChangeHandler = () => {
      this.cleanupInactiveLeaves();
    };
    this.app.workspace.on("layout-change", this.layoutChangeHandler);
  }
  cleanupInactiveLeaves() {
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    const activeLeafSet = new Set(leaves);
    for (const [leaf] of this.leafStates) {
      if (!activeLeafSet.has(leaf)) {
        this.deactivateForLeaf(leaf);
      }
    }
  }
  removeGlobalEventListeners() {
    if (this.fileOpenHandler) {
      this.app.workspace.off("file-open", this.fileOpenHandler);
      this.fileOpenHandler = null;
    }
    if (this.layoutChangeHandler) {
      this.app.workspace.off("layout-change", this.layoutChangeHandler);
      this.layoutChangeHandler = null;
    }
  }
  async updateFilePaths(oldPath, newPath) {
    for (const [leaf, state] of this.leafStates) {
      if (state.currentFilePath === oldPath && state.isActive) {
        state.deactivate();
        state.currentFilePath = newPath;
        const file = this.app.vault.getAbstractFileByPath(newPath);
        if (file && file instanceof import_obsidian5.TFile) {
          await state.activate(file);
        }
      } else if (state.currentFilePath === oldPath) {
        state.currentFilePath = newPath;
      }
    }
  }
  deactivateForFile(filePath) {
    for (const [leaf, state] of this.leafStates) {
      if (state.currentFilePath === filePath) {
        this.deactivateForLeaf(leaf);
      }
    }
  }
  getIsActive() {
    const leaf = this.app.workspace.activeLeaf;
    if (!leaf) return false;
    const state = this.leafStates.get(leaf);
    return state ? state.getIsActive() : false;
  }
};

// src/main.ts
var MarkdownAnnotationPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    var _a;
    await this.loadSettings();
    const pluginDir = (_a = this.manifest.dir) != null ? _a : ".obsidian/plugins/obsidian-annotation-marker";
    this.dataManager = new DataManager(this.app, pluginDir);
    this.annotationMode = new AnnotationMode(this.app, this.dataManager);
    this.fileRenameEventRef = this.app.vault.on("rename", async (file, oldPath) => {
      if (file instanceof import_obsidian6.TFile && file.extension === "md") {
        const success = await this.dataManager.migrateAnnotation(oldPath, file.path);
        if (success) {
          new import_obsidian6.Notice(`\u6807\u6CE8\u6570\u636E\u5DF2\u81EA\u52A8\u8FC1\u79FB`);
          await this.annotationMode.updateFilePaths(oldPath, file.path);
        }
      }
    });
    this.fileDeleteEventRef = this.app.vault.on("delete", async (file) => {
      if (file instanceof import_obsidian6.TFile && file.extension === "md") {
        const success = await this.dataManager.deleteAnnotationData(file.path);
        if (success) {
          new import_obsidian6.Notice(`\u6807\u6CE8\u6570\u636E\u5DF2\u81EA\u52A8\u5220\u9664`);
          this.annotationMode.deactivateForFile(file.path);
        }
      }
    });
    this.addRibbonIcon("highlighter", "\u6807\u6CE8\u6A21\u5F0F", async () => {
      const file = this.app.workspace.getActiveFile();
      this.annotationMode.toggle(file);
    });
    this.addCommand({
      id: "toggle-annotation-mode",
      name: "\u5207\u6362\u6807\u6CE8\u6A21\u5F0F",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && file.extension === "md") {
          if (!checking) {
            this.annotationMode.toggle(file);
          }
          return true;
        }
        return false;
      }
    });
  }
  onunload() {
    this.annotationMode.deactivate();
    this.dataManager.clearCache();
    if (this.fileRenameEventRef) {
      this.app.vault.offref(this.fileRenameEventRef);
    }
    if (this.fileDeleteEventRef) {
      this.app.vault.offref(this.fileDeleteEventRef);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
