/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AnnotationPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/annotationFile/AnnotationFileManager.ts
var import_obsidian = require("obsidian");

// src/constants.ts
var COLOR_MAP = {
  red: { bg: "rgba(255, 107, 107, 0.35)", border: "#ff6b6b" },
  blue: { bg: "rgba(84, 160, 255, 0.35)", border: "#54a0ff" },
  yellow: { bg: "rgba(255, 212, 59, 0.45)", border: "#ffd43b" },
  green: { bg: "rgba(38, 194, 129, 0.35)", border: "#26c281" },
  purple: { bg: "rgba(155, 89, 182, 0.35)", border: "#9b59b6" },
  none: { bg: "transparent", border: "#999" }
};
var COLOR_LABELS = {
  red: "\u7EA2\u8272",
  blue: "\u84DD\u8272",
  yellow: "\u9EC4\u8272",
  green: "\u7EFF\u8272",
  purple: "\u7D2B\u8272",
  none: "\u65E0\u8272"
};
var PATH_SEPARATOR = "&.";

// src/utils/helpers.ts
function generateId() {
  return `${Date.now()}-${Math.random().toString(36).substring(2, 11)}`;
}
function notePathToAnnotationPath(pluginDir, notePath) {
  const normalizedPath = notePath.replace(/[/\\]/g, PATH_SEPARATOR);
  return `${pluginDir}/annotations/${normalizedPath}`;
}
function encodeAttr(str) {
  return str.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\r/g, "&#13;").replace(/\n/g, "&#10;");
}
function decodeAttr(str) {
  return str.replace(/&#10;/g, "\n").replace(/&#13;/g, "\r").replace(/&gt;/g, ">").replace(/&lt;/g, "<").replace(/&quot;/g, '"').replace(/&amp;/g, "&");
}
function calculateRangeOffsetInElement(range, element) {
  var _a;
  let start = 0;
  let end = 0;
  let foundStart = false;
  const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT, null);
  let node = walker.nextNode();
  while (node) {
    const textNode = node;
    const nodeLength = ((_a = textNode.textContent) == null ? void 0 : _a.length) || 0;
    if (!foundStart) {
      if (textNode === range.startContainer) {
        start += range.startOffset;
        foundStart = true;
        if (range.endContainer === textNode) {
          end = start + (range.endOffset - range.startOffset);
          return { start, end };
        }
      } else if (textNode === range.endContainer) {
        end = start + range.endOffset;
        return { start: 0, end };
      } else {
        start += nodeLength;
      }
    } else {
      if (textNode === range.endContainer) {
        end = start + range.endOffset;
        return { start, end };
      } else {
        start += nodeLength;
      }
    }
    node = walker.nextNode();
  }
  return null;
}

// src/annotationFile/annotationParser.ts
function getAttr(attrs, name) {
  const regex = new RegExp(`${name}="([^"]*)"`, "i");
  const match = attrs.match(regex);
  return match ? match[1] : null;
}
function extractColorFromStyle(style) {
  for (const [color, { bg }] of Object.entries(COLOR_MAP)) {
    if (style.includes(bg)) {
      return color;
    }
  }
  return "yellow";
}
function stripTags(html) {
  return html.replace(/<[^>]+>/g, "");
}
function stripRubyText(html) {
  const noRt = html.replace(/<rt[^>]*>[\s\S]*?<\/rt>/g, "");
  return stripTags(noRt);
}
function stripAnnotationTags(content) {
  let result = content.replace(
    /<ruby\s+[^>]*>([\s\S]*?)<rt\s+[^>]*>([\s\S]*?)<\/rt><\/ruby>/g,
    "$1"
  );
  result = stripNestedMarks(result);
  return result;
}
function stripNestedMarks(content) {
  const openRe = /<mark\s+[^>]*>/g;
  const closeRe = /<\/mark>/g;
  const segments = [];
  const tags = [];
  let m;
  openRe.lastIndex = 0;
  while ((m = openRe.exec(content)) !== null) {
    tags.push({ index: m.index, length: m[0].length, isOpen: true });
  }
  closeRe.lastIndex = 0;
  while ((m = closeRe.exec(content)) !== null) {
    tags.push({ index: m.index, length: m[0].length, isOpen: false });
  }
  tags.sort((a, b) => a.index - b.index);
  let lastIdx = 0;
  for (const tag of tags) {
    if (tag.index > lastIdx) {
      segments.push({ text: content.substring(lastIdx, tag.index), isTag: false, index: lastIdx });
    }
    lastIdx = tag.index + tag.length;
  }
  if (lastIdx < content.length) {
    segments.push({ text: content.substring(lastIdx), isTag: false, index: lastIdx });
  }
  return segments.map((s) => s.text).join("");
}
function findMatchingCloseMark(content, openTagEnd) {
  let depth = 1;
  let pos = openTagEnd;
  while (depth > 0 && pos < content.length) {
    const nextOpen = content.indexOf("<mark ", pos);
    const nextOpenSelf = content.indexOf("<mark>", pos);
    const nextClose = content.indexOf("</mark>", pos);
    let effectiveOpen = -1;
    if (nextOpen !== -1) effectiveOpen = nextOpen;
    if (nextOpenSelf !== -1 && (effectiveOpen === -1 || nextOpenSelf < effectiveOpen)) {
      effectiveOpen = nextOpenSelf;
    }
    if (nextClose === -1) break;
    if (effectiveOpen !== -1 && effectiveOpen < nextClose) {
      depth++;
      pos = effectiveOpen + 6;
    } else {
      depth--;
      if (depth === 0) return nextClose;
      pos = nextClose + 7;
    }
  }
  return -1;
}
function parseRubyTags(content, parentAnnotationId) {
  const rubies = [];
  const rubyRegex = new RegExp(
    `<ruby\\s+[^>]*data-annotation-id="${parentAnnotationId}"[^>]*>([\\s\\S]*?)<\\/ruby>`,
    "g"
  );
  let match;
  while ((match = rubyRegex.exec(content)) !== null) {
    const rubyContent = match[1];
    const rtMatch = rubyContent.match(/<rt[^>]*data-annotation-id="[^"]*"[^>]*>([\s\S]*?)<\/rt>/);
    const rtText = rtMatch ? rtMatch[1] : "";
    const baseTextMatch = rubyContent.match(/^([\s\S]*?)<rt/);
    const baseText = baseTextMatch ? baseTextMatch[1] : "";
    if (baseText && rtText) {
      const beforeRuby = content.substring(0, match.index);
      const plainBefore = stripRubyText(beforeRuby);
      rubies.push({
        startIndex: plainBefore.length,
        length: baseText.length,
        ruby: rtText
      });
    }
  }
  return rubies;
}
function parseAnnotations(content) {
  const segments = [];
  const openRegex = /<mark\s+([^>]*)>/g;
  let openMatch;
  while ((openMatch = openRegex.exec(content)) !== null) {
    const attrs = openMatch[1];
    const id = getAttr(attrs, "data-annotation-id");
    if (!id) continue;
    const openTagStart = openMatch.index;
    const openTagEnd = openTagStart + openMatch[0].length;
    const closeTagStart = findMatchingCloseMark(content, openTagEnd);
    if (closeTagStart === -1) continue;
    const innerContent = content.substring(openTagEnd, closeTagStart);
    segments.push({
      id,
      attrs,
      content: innerContent,
      startIndex: openTagStart,
      endIndex: closeTagStart + 7
      // "</mark>" 的长度
    });
  }
  const groupMap = /* @__PURE__ */ new Map();
  for (const seg of segments) {
    let group = groupMap.get(seg.id);
    if (!group) {
      group = [];
      groupMap.set(seg.id, group);
    }
    group.push(seg);
  }
  const annotations = [];
  for (const [id, group] of groupMap) {
    const first = group[0];
    const style = getAttr(first.attrs, "style") || "";
    const color = extractColorFromStyle(style);
    const note = decodeAttr(getAttr(first.attrs, "data-annotation-note") || "");
    const createdAt = getAttr(first.attrs, "data-annotation-created") || (/* @__PURE__ */ new Date()).toISOString();
    const isFullText = getAttr(first.attrs, "data-annotation-fulltext") === "true";
    const text = isFullText ? stripRubyText(first.content) : group.map((seg) => stripRubyText(seg.content)).join("");
    const rubyTexts = [];
    if (isFullText) {
      rubyTexts.push(...parseRubyTags(first.content, id));
    } else {
      let offset = 0;
      for (const seg of group) {
        const segRubies = parseRubyTags(seg.content, id);
        for (const r of segRubies) {
          rubyTexts.push({
            startIndex: offset + r.startIndex,
            length: r.length,
            ruby: r.ruby
          });
        }
        offset += stripRubyText(seg.content).length;
      }
    }
    const positions = group.map((seg) => ({
      start: seg.startIndex,
      end: seg.endIndex
    }));
    annotations.push({
      id,
      color,
      note,
      text,
      rubyTexts,
      createdAt,
      positions,
      isFullText
    });
  }
  return annotations;
}

// src/utils/contentMapper.ts
function findTextInSource(sourceContent, searchText, contextBefore, contextAfter, searchStartLine, searchEndLine, occurrence) {
  var _a, _b;
  if (!searchText) return null;
  let searchContent = sourceContent;
  let lineOffset = 0;
  if (searchStartLine !== void 0 && searchEndLine !== void 0) {
    const lines = sourceContent.split("\n");
    const startLine = Math.max(0, searchStartLine);
    const endLine = Math.min(lines.length - 1, searchEndLine);
    searchContent = lines.slice(startLine, endLine + 1).join("\n");
    lineOffset = lines.slice(0, startLine).join("\n").length;
    if (startLine > 0) lineOffset += 1;
  }
  const map = buildCleanedMap(searchContent);
  const { cleaned, cleanedToSource } = map;
  const occurrences = [];
  let searchFrom = 0;
  while (true) {
    const idx = cleaned.indexOf(searchText, searchFrom);
    if (idx < 0) break;
    occurrences.push(idx);
    searchFrom = idx + 1;
  }
  if (occurrences.length === 0) return null;
  const targetCleanedIdx = occurrence !== void 0 && occurrence < occurrences.length ? occurrences[occurrence] : occurrences[0];
  const cleanedStart = targetCleanedIdx;
  const cleanedEnd = targetCleanedIdx + searchText.length;
  if (cleanedEnd > cleanedToSource.length) return null;
  return {
    start: ((_a = cleanedToSource[cleanedStart]) != null ? _a : 0) + lineOffset,
    end: ((_b = cleanedToSource[cleanedEnd - 1]) != null ? _b : 0) + 1 + lineOffset
  };
}
function buildCleanedMap(source) {
  const cleanedChars = [];
  const cleanedToSource = [];
  const syntaxRegex = new RegExp([
    "<rt[^>]*>[\\s\\S]*?<\\/rt>",
    // <rt>内容</rt> 整体去除
    "|<[^<>]+>",
    // HTML 标签去除（保留标签间文本）
    "|\\*\\*\\*([^\\*]+)\\*\\*\\*",
    // ***粗斜体*** → 保留内文本
    "|\\*\\*([^\\*]+)\\*\\*",
    // **粗体** → 保留内文本
    "|\\*([^\\*]+)\\*",
    // *斜体* → 保留内文本
    "|``([^`]+)``",
    // ``代码`` → 保留内文本
    "|`([^`]+)`",
    // `代码` → 保留内文本
    "|_([^_]+)_",
    // _斜体_ → 保留内文本
    "|==([^=]+)==",
    // ==高亮== → 保留内文本
    "|~~([^~]+)~~",
    // ~~删除线~~ → 保留内文本
    "|!\\[\\[[^\\[\\]]+\\]\\]",
    // ![[图片]] 整体去除
    "|\\[\\[(?:[^\\[\\]\\|]*\\|)?([^\\[\\]]+)\\]\\]",
    // [[链接]] 或 [[目标|显示]] → 保留显示文本
    "|!\\[[^\\[\\]\\(\\)]*\\]\\([^)]+\\)",
    // ![图片](url) 整体去除
    "|\\[([^\\[\\]\\(\\)]+)\\]\\([^)]+\\)",
    // [链接](url) → 保留链接文本
    "|^#{1,6}\\s*",
    // 标题标记去除
    "|^\\>\\s?",
    // 引用标记去除
    "|^[-*+]\\s(?:\\[[ x]\\]\\s)?",
    // 列表标记去除
    "|^\\d+\\.\\s",
    // 有序列表标记去除
    "|^-{3,}$",
    // --- 水平线整体去除
    "|^\\*{3,}$"
    // *** 水平线整体去除
  ].join(""), "gm");
  const prefixLengths = {
    1: 3,
    // ***
    2: 2,
    // **
    3: 1,
    // *
    4: 2,
    // ``
    5: 1,
    // `
    6: 1,
    // _
    7: 2,
    // ==
    8: 2
    // ~~
  };
  let lastIndex = 0;
  let match;
  while ((match = syntaxRegex.exec(source)) !== null) {
    if (match.index > lastIndex) {
      const text = source.substring(lastIndex, match.index);
      for (let i = 0; i < text.length; i++) {
        cleanedChars.push(text.charAt(i));
        cleanedToSource.push(lastIndex + i);
      }
    }
    let keptText = null;
    let keptSourceStart = 0;
    if (match[1] !== void 0) {
      keptText = match[1];
      keptSourceStart = match.index + 3;
    } else if (match[2] !== void 0) {
      keptText = match[2];
      keptSourceStart = match.index + 2;
    } else if (match[3] !== void 0) {
      keptText = match[3];
      keptSourceStart = match.index + 1;
    } else if (match[4] !== void 0) {
      keptText = match[4];
      keptSourceStart = match.index + 2;
    } else if (match[5] !== void 0) {
      keptText = match[5];
      keptSourceStart = match.index + 1;
    } else if (match[6] !== void 0) {
      keptText = match[6];
      keptSourceStart = match.index + 1;
    } else if (match[7] !== void 0) {
      keptText = match[7];
      keptSourceStart = match.index + 2;
    } else if (match[8] !== void 0) {
      keptText = match[8];
      keptSourceStart = match.index + 2;
    } else if (match[9] !== void 0) {
      keptText = match[9];
      const fullMatch = match[0];
      const displayOffset = fullMatch.indexOf(keptText);
      keptSourceStart = match.index + displayOffset;
    } else if (match[10] !== void 0) {
      keptText = match[10];
      keptSourceStart = match.index + 1;
    }
    if (keptText) {
      for (let i = 0; i < keptText.length; i++) {
        cleanedChars.push(keptText.charAt(i));
        cleanedToSource.push(keptSourceStart + i);
      }
    }
    lastIndex = syntaxRegex.lastIndex;
  }
  if (lastIndex < source.length) {
    const text = source.substring(lastIndex);
    for (let i = 0; i < text.length; i++) {
      cleanedChars.push(text.charAt(i));
      cleanedToSource.push(lastIndex + i);
    }
  }
  return {
    cleaned: cleanedChars.join(""),
    cleanedToSource
  };
}
function calculateOffsetInBlock(range, block) {
  var _a, _b, _c;
  const walker = document.createTreeWalker(block, NodeFilter.SHOW_TEXT, null);
  let offset = 0;
  let node;
  while (node = walker.nextNode()) {
    if (((_a = node.parentElement) == null ? void 0 : _a.tagName) === "RT") continue;
    if (node === range.startContainer) {
      return offset + range.startOffset;
    }
    offset += (_c = (_b = node.textContent) == null ? void 0 : _b.length) != null ? _c : 0;
  }
  return offset;
}
function extractSelectionContext(selection) {
  var _a, _b, _c;
  if (!selection.rangeCount) return null;
  const range = selection.getRangeAt(0);
  if (range.collapsed) return null;
  const container = range.commonAncestorContainer;
  const block = container instanceof HTMLElement ? container : container.parentElement;
  if (!block) return null;
  const cleanParts = [];
  const walker = document.createTreeWalker(block, NodeFilter.SHOW_TEXT, null);
  let node;
  let selStart = -1;
  let selEnd = -1;
  let currentOffset = 0;
  while (node = walker.nextNode()) {
    if (((_a = node.parentElement) == null ? void 0 : _a.tagName) === "RT") continue;
    const len = (_c = (_b = node.textContent) == null ? void 0 : _b.length) != null ? _c : 0;
    if (node === range.startContainer) {
      selStart = currentOffset + range.startOffset;
    }
    if (node === range.endContainer) {
      selEnd = currentOffset + range.endOffset;
    }
    cleanParts.push(node.textContent || "");
    currentOffset += len;
  }
  const cleanBlockText = cleanParts.join("");
  if (selStart < 0 || selEnd < 0) {
    const text2 = selection.toString().trim();
    if (!text2) return null;
    return { text: text2, contextBefore: "", contextAfter: "" };
  }
  const text = cleanBlockText.substring(selStart, selEnd).trim();
  if (!text) return null;
  const CONTEXT_LEN = 50;
  const contextBefore = cleanBlockText.substring(Math.max(0, selStart - CONTEXT_LEN), selStart);
  const contextAfter = cleanBlockText.substring(
    selEnd,
    selEnd + CONTEXT_LEN
  );
  return { text, contextBefore, contextAfter };
}

// src/utils/overlapUtils.ts
function computeSegments(intervals) {
  if (intervals.length === 0) return [];
  const points = /* @__PURE__ */ new Set();
  for (const iv of intervals) {
    points.add(iv.start);
    points.add(iv.end);
  }
  const sorted = Array.from(points).sort((a, b) => a - b);
  const segments = [];
  for (let i = 0; i < sorted.length - 1; i++) {
    const segStart = sorted[i];
    const segEnd = sorted[i + 1];
    const coveringIds = intervals.filter((iv) => iv.start <= segStart && iv.end >= segEnd).map((iv) => iv.id);
    if (coveringIds.length > 0) {
      segments.push({ ids: coveringIds, start: segStart, end: segEnd });
    }
  }
  return segments;
}
function buildSegmentHtml(segments, plainText, annotations) {
  var _a;
  const parts = [];
  let lastEnd = 0;
  for (const seg of segments) {
    if (seg.start > lastEnd) {
      parts.push(plainText.substring(lastEnd, seg.start));
    }
    let enrichedText = plainText.substring(seg.start, seg.end);
    const segmentRubies = [];
    for (const id of seg.ids) {
      const ann = annotations.get(id);
      if (ann == null ? void 0 : ann.rubyTexts) {
        for (const ruby of ann.rubyTexts) {
          const absStart = ann.start + ruby.startIndex;
          const absEnd = absStart + ruby.length;
          if (absStart >= seg.start && absEnd <= seg.end) {
            segmentRubies.push({
              localStart: absStart - seg.start,
              localEnd: absEnd - seg.start,
              ruby: ruby.ruby,
              annId: id
            });
          }
        }
      }
    }
    segmentRubies.sort((a, b) => b.localStart - a.localStart);
    for (const sr of segmentRubies) {
      const before = enrichedText.substring(0, sr.localStart);
      const target = enrichedText.substring(sr.localStart, sr.localEnd);
      const after = enrichedText.substring(sr.localEnd);
      enrichedText = `${before}<ruby data-annotation-id="${sr.annId}">${target}<rt data-annotation-id="${sr.annId}">${sr.ruby}</rt></ruby>${after}`;
    }
    const sortedIds = [...seg.ids].sort();
    let wrapped = enrichedText;
    for (let i = sortedIds.length - 1; i >= 0; i--) {
      const id = sortedIds[i];
      const ann = annotations.get(id);
      const bg = (_a = ann == null ? void 0 : ann.color) != null ? _a : "rgba(255, 212, 59, 0.45)";
      const colorAttr = (ann == null ? void 0 : ann.annotationColor) ? ` data-annotation-color="${ann.annotationColor}"` : "";
      const noteAttr = (ann == null ? void 0 : ann.note) ? ` data-annotation-note="${ann.note}"` : "";
      const createdAttr = (ann == null ? void 0 : ann.created) ? ` data-annotation-created="${ann.created}"` : "";
      wrapped = `<mark style="background:${bg}" data-annotation-id="${id}"${colorAttr}${noteAttr}${createdAttr}>${wrapped}</mark>`;
    }
    parts.push(wrapped);
    lastEnd = seg.end;
  }
  if (lastEnd < plainText.length) {
    parts.push(plainText.substring(lastEnd));
  }
  return parts.join("");
}

// src/annotationFile/annotationSerializer.ts
function buildRubyTag(annotationId, text, ruby) {
  return `<ruby data-annotation-id="${annotationId}">${text}<rt data-annotation-id="${annotationId}">${ruby}</rt></ruby>`;
}
function buildAnnotatedText(text, annotationId, rubyTexts) {
  if (!rubyTexts || rubyTexts.length === 0) return text;
  const sorted = [...rubyTexts].sort((a, b) => b.startIndex - a.startIndex);
  let result = text;
  for (const ruby of sorted) {
    const before = result.substring(0, ruby.startIndex);
    const target = result.substring(ruby.startIndex, ruby.startIndex + ruby.length);
    const after = result.substring(ruby.startIndex + ruby.length);
    result = before + buildRubyTag(annotationId, target, ruby.ruby) + after;
  }
  return result;
}
function buildMarkTag(id, text, color, note, rubyTexts, createdAt, isFullText) {
  const bg = COLOR_MAP[color].bg;
  const created = createdAt || (/* @__PURE__ */ new Date()).toISOString();
  const noteAttr = note ? ` data-annotation-note="${encodeAttr(note)}"` : "";
  const fullTextAttr = isFullText ? ` data-annotation-fulltext="true"` : "";
  const annotatedText = buildAnnotatedText(text, id, rubyTexts);
  return `<mark style="background:${bg}" data-annotation-id="${id}" data-annotation-color="${color}"${noteAttr} data-annotation-created="${created}"${fullTextAttr}>${annotatedText}</mark>`;
}
function insertAnnotation(content, annotation) {
  const id = generateId();
  let start = -1;
  let end = -1;
  if (annotation.position) {
    start = annotation.position.start;
    end = annotation.position.end;
  } else {
    const found = findTextInSource(
      content,
      annotation.text,
      annotation.contextBefore,
      annotation.contextAfter,
      annotation.startLine,
      annotation.endLine,
      annotation.occurrence
    );
    if (found) {
      start = found.start;
      end = found.end;
    }
  }
  if (start < 0) {
    return { content, id };
  }
  if (end < 0) {
    end = start + annotation.text.length;
  }
  const sourceSlice = content.substring(start, end);
  const hasTagsInSlice = /<[^>]+>/.test(sourceSlice);
  const beforeStart = content.substring(0, start);
  const openMarkCount = (beforeStart.match(/<mark[\s>]/g) || []).length;
  const closeMarkCount = (beforeStart.match(/<\/mark>/g) || []).length;
  const insideExistingMark = openMarkCount > closeMarkCount;
  if (!hasTagsInSlice && !insideExistingMark) {
    const tag = sourceSlice === annotation.text ? buildMarkTag(id, sourceSlice, annotation.color, annotation.note, annotation.rubyTexts) : buildMarkTag(id, sourceSlice, annotation.color, annotation.note);
    return {
      content: content.substring(0, start) + tag + content.substring(end),
      id
    };
  }
  return rebuildOverlapRegion(content, start, end, id, annotation);
}
function rebuildOverlapRegion(content, newStart, newEnd, newId, annotation) {
  const existingAnnotations = parseAnnotations(content);
  const involvedAnnotations = existingAnnotations.filter(
    (a) => a.positions.some((p) => p.start < newEnd && p.end > newStart)
  );
  const allStarts = [newStart, ...involvedAnnotations.flatMap((a) => a.positions.map((p) => p.start))];
  const allEnds = [newEnd, ...involvedAnnotations.flatMap((a) => a.positions.map((p) => p.end))];
  const affectedStart = Math.min(...allStarts);
  const affectedEnd = Math.max(...allEnds);
  const nestedAnnotations = existingAnnotations.filter(
    (a) => !involvedAnnotations.includes(a) && a.positions.some((p) => p.start >= affectedStart && p.end <= affectedEnd)
  );
  const allExistingToRebuild = [...involvedAnnotations, ...nestedAnnotations];
  const affectedRegion = content.substring(affectedStart, affectedEnd);
  const plainRegion = stripAnnotationTags(affectedRegion);
  const allInvolved = [
    ...allExistingToRebuild.map((a) => ({
      id: a.id,
      text: a.text,
      color: a.color,
      note: a.note,
      created: a.createdAt,
      rubyTexts: a.rubyTexts
    })),
    {
      id: newId,
      text: annotation.text,
      color: annotation.color,
      note: annotation.note,
      created: (/* @__PURE__ */ new Date()).toISOString(),
      rubyTexts: annotation.rubyTexts
    }
  ];
  const intervals = [];
  for (const ann of allInvolved) {
    const idx = plainRegion.indexOf(ann.text);
    if (idx >= 0) {
      intervals.push({
        id: ann.id,
        start: idx,
        end: idx + ann.text.length,
        color: COLOR_MAP[ann.color].bg,
        annotationColor: ann.color,
        note: ann.note ? encodeAttr(ann.note) : void 0,
        created: ann.created,
        rubyTexts: ann.rubyTexts
      });
    }
  }
  const segments = computeSegments(intervals);
  const annotationMap = /* @__PURE__ */ new Map();
  for (const iv of intervals) {
    annotationMap.set(iv.id, iv);
  }
  const rebuiltRegion = buildSegmentHtml(segments, plainRegion, annotationMap);
  return {
    content: content.substring(0, affectedStart) + rebuiltRegion + content.substring(affectedEnd),
    id: newId
  };
}
function removeAnnotationTag(content, annotationId) {
  const allAnnotations = parseAnnotations(content);
  const targetAnnotation = allAnnotations.find((a) => a.id === annotationId);
  if (!targetAnnotation) return content;
  let result = content;
  for (let i = targetAnnotation.positions.length - 1; i >= 0; i--) {
    const tp = targetAnnotation.positions[i];
    const overlappingAnnotations = allAnnotations.filter(
      (a) => a.id !== annotationId && a.positions.some((ap) => ap.start < tp.end && tp.start < ap.end)
    );
    if (overlappingAnnotations.length > 0) {
      result = rebuildLocalOverlap(result, tp, overlappingAnnotations);
    }
  }
  result = simpleRemoveAnnotationTag(result, annotationId);
  result = mergeAdjacentMarks(result);
  return result;
}
function mergeAdjacentMarks(content) {
  var _a;
  const openRe = /<mark\s+([^>]*)>/g;
  const closeRe = /<\/mark>/g;
  const tags = [];
  let m;
  while ((m = openRe.exec(content)) !== null) {
    const attrs = m[1];
    const id = ((_a = attrs.match(/data-annotation-id="([^"]*)"/)) == null ? void 0 : _a[1]) || "";
    const isFullText = attrs.includes('data-annotation-fulltext="true"');
    tags.push({ index: m.index, length: m[0].length, type: "open", id, isFullText });
  }
  while ((m = closeRe.exec(content)) !== null) {
    tags.push({ index: m.index, length: 7, type: "close", id: "", isFullText: false });
  }
  tags.sort((a, b) => a.index - b.index);
  const stack = [];
  const skipSet = /* @__PURE__ */ new Set();
  for (let i = 0; i < tags.length; i++) {
    if (skipSet.has(i)) continue;
    const tag = tags[i];
    if (tag.type === "open") {
      stack.push(i);
    } else {
      const openIdx = stack.pop();
      if (openIdx === void 0) continue;
      const openTag = tags[openIdx];
      const nextIdx = i + 1;
      const nextTag = tags[nextIdx];
      if (nextTag && nextTag.type === "open" && nextTag.id === openTag.id && !nextTag.isFullText && openTag.id && tag.index + tag.length === nextTag.index) {
        skipSet.add(i);
        skipSet.add(nextIdx);
        stack.push(openIdx);
      }
    }
  }
  if (skipSet.size === 0) return content;
  const parts = [];
  let lastIdx = 0;
  for (let i = 0; i < tags.length; i++) {
    const tag = tags[i];
    if (tag.index > lastIdx) {
      parts.push(content.substring(lastIdx, tag.index));
    }
    if (!skipSet.has(i)) {
      parts.push(content.substring(tag.index, tag.index + tag.length));
    }
    lastIdx = tag.index + tag.length;
  }
  if (lastIdx < content.length) {
    parts.push(content.substring(lastIdx));
  }
  return parts.join("");
}
function simpleRemoveAnnotationTag(content, annotationId) {
  const rubyRegex = new RegExp(
    `<ruby\\s+[^>]*data-annotation-id="${annotationId}"[^>]*>([\\s\\S]*?)<rt\\s+[^>]*data-annotation-id="${annotationId}"[^>]*>[\\s\\S]*?<\\/rt><\\/ruby>`,
    "g"
  );
  let result = content.replace(rubyRegex, "$1");
  const markRegex = new RegExp(
    `<mark\\s+[^>]*data-annotation-id="${annotationId}"[^>]*>([\\s\\S]*?)<\\/mark>`,
    "g"
  );
  result = result.replace(markRegex, "$1");
  return result;
}
function rebuildLocalOverlap(content, targetPos, overlappingAnnotations) {
  const allStarts = [targetPos.start];
  const allEnds = [targetPos.end];
  for (const ann of overlappingAnnotations) {
    for (const ap of ann.positions) {
      if (ap.start < targetPos.end && targetPos.start < ap.end) {
        allStarts.push(ap.start);
        allEnds.push(ap.end);
      }
    }
  }
  const affectedStart = Math.min(...allStarts);
  const affectedEnd = Math.max(...allEnds);
  const affectedRegion = content.substring(affectedStart, affectedEnd);
  const plainRegion = stripAnnotationTags(affectedRegion);
  const intervals = [];
  for (const ann of overlappingAnnotations) {
    for (const pos of ann.positions) {
      if (pos.start < affectedEnd && pos.end > affectedStart) {
        const localStart = pos.start - affectedStart;
        const localEnd = pos.end - affectedStart;
        const plainBefore = stripAnnotationTags(affectedRegion.substring(0, localStart));
        const plainAtPos = stripAnnotationTags(affectedRegion.substring(localStart, localEnd));
        if (plainAtPos.length > 0) {
          intervals.push({
            id: ann.id,
            start: plainBefore.length,
            end: plainBefore.length + plainAtPos.length,
            color: COLOR_MAP[ann.color].bg,
            annotationColor: ann.color,
            note: ann.note ? encodeAttr(ann.note) : void 0,
            created: ann.createdAt,
            rubyTexts: ann.rubyTexts
          });
        }
      }
    }
  }
  if (intervals.length === 0) {
    return content.substring(0, affectedStart) + plainRegion + content.substring(affectedEnd);
  }
  const segments = computeSegments(intervals);
  const annotationMap = /* @__PURE__ */ new Map();
  for (const iv of intervals) {
    annotationMap.set(iv.id, iv);
  }
  const rebuiltRegion = buildSegmentHtml(segments, plainRegion, annotationMap);
  return content.substring(0, affectedStart) + rebuiltRegion + content.substring(affectedEnd);
}
function updateAnnotationTag(content, annotationId, updates) {
  const regex = new RegExp(
    `(<mark\\s+)([^>]*data-annotation-id="${annotationId}"[^>]*)(>)([\\s\\S]*?)(<\\/mark>)`,
    "g"
  );
  return content.replace(regex, (_match, prefix, attrs, open, innerContent, close) => {
    let newAttrs = attrs;
    if (updates.color) {
      const bg = COLOR_MAP[updates.color].bg;
      newAttrs = newAttrs.replace(
        /style="background:[^"]*"/,
        `style="background:${bg}"`
      );
      newAttrs = newAttrs.replace(
        /data-annotation-color="[^"]*"/,
        `data-annotation-color="${updates.color}"`
      );
    }
    if (updates.note !== void 0) {
      if (updates.note) {
        if (newAttrs.includes("data-annotation-note=")) {
          newAttrs = newAttrs.replace(
            /data-annotation-note="[^"]*"/,
            `data-annotation-note="${encodeAttr(updates.note)}"`
          );
        } else {
          newAttrs += ` data-annotation-note="${encodeAttr(updates.note)}"`;
        }
      } else {
        newAttrs = newAttrs.replace(/\s*data-annotation-note="[^"]*"/, "");
      }
    }
    if (updates.rubyTexts !== void 0) {
      const plainText = innerContent.replace(/<ruby\s+[^>]*>([\s\S]*?)<rt\s+[^>]*>[\s\S]*?<\/rt><\/ruby>/g, "$1");
      const newInnerContent = buildAnnotatedText(plainText, annotationId, updates.rubyTexts);
      return `${prefix}${newAttrs}${open}${newInnerContent}${close}`;
    }
    return `${prefix}${newAttrs}${open}${innerContent}${close}`;
  });
}
function insertFullTextAnnotation(content, annotation) {
  var _a, _b;
  const id = generateId();
  const map = buildCleanedMap(content);
  const occurrences = [];
  let searchFrom = 0;
  while (true) {
    const idx = map.cleaned.indexOf(annotation.text, searchFrom);
    if (idx < 0) break;
    occurrences.push(idx);
    searchFrom = idx + 1;
  }
  if (occurrences.length === 0) return { content, id, count: 0 };
  let newContent = content;
  for (let i = occurrences.length - 1; i >= 0; i--) {
    const cleanStart = occurrences[i];
    const cleanEnd = cleanStart + annotation.text.length;
    const srcStart = (_a = map.cleanedToSource[cleanStart]) != null ? _a : 0;
    const srcEnd = ((_b = map.cleanedToSource[cleanEnd - 1]) != null ? _b : srcStart) + 1;
    const sourceSlice = newContent.substring(srcStart, srcEnd);
    const tag = buildMarkTag(id, sourceSlice, annotation.color, annotation.note, void 0, void 0, true);
    newContent = newContent.substring(0, srcStart) + tag + newContent.substring(srcEnd);
  }
  return { content: newContent, id, count: occurrences.length };
}

// src/annotationFile/AnnotationFileManager.ts
var AnnotationFileManager = class {
  constructor(app, pluginDir) {
    this.app = app;
    this.pluginDir = pluginDir;
  }
  // 获取标注文件路径
  getAnnotationFilePath(notePath) {
    return notePathToAnnotationPath(this.pluginDir, notePath);
  }
  // 检查标注文件是否存在
  async hasAnnotationFile(notePath) {
    const path = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(notePath));
    return this.app.vault.adapter.exists(path);
  }
  // 确保标注文件存在（不存在则从原文件复制创建）
  async ensureAnnotationFile(notePath) {
    const annotationPath = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(notePath));
    if (await this.app.vault.adapter.exists(annotationPath)) {
      await this.syncFromOriginal(notePath);
      return true;
    }
    const originalFile = this.app.vault.getAbstractFileByPath(notePath);
    if (!(originalFile instanceof import_obsidian.TFile)) return false;
    const content = await this.app.vault.read(originalFile);
    const dir = annotationPath.substring(0, annotationPath.lastIndexOf("/"));
    if (dir && !await this.app.vault.adapter.exists(dir)) {
      await this.app.vault.adapter.mkdir(dir);
    }
    await this.app.vault.adapter.write(annotationPath, content);
    return true;
  }
  // 读取标注文件内容
  async readAnnotationFile(notePath) {
    const annotationPath = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(notePath));
    return this.app.vault.adapter.read(annotationPath);
  }
  // 写入标注文件内容
  async writeAnnotationFile(notePath, content) {
    const annotationPath = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(notePath));
    await this.app.vault.adapter.write(annotationPath, content);
  }
  // 同步原文件更新到标注文件
  async syncFromOriginal(notePath) {
    const file = this.app.vault.getAbstractFileByPath(notePath);
    if (!(file instanceof import_obsidian.TFile)) return;
    const originalContent = await this.app.vault.read(file);
    const annotatedContent = await this.readAnnotationFile(notePath);
    const strippedContent = stripAnnotationTags(annotatedContent);
    if (strippedContent === originalContent) return;
    const syncedContent = this.simpleSync(originalContent, annotatedContent, strippedContent);
    await this.writeAnnotationFile(notePath, syncedContent);
  }
  simpleSync(originalContent, annotatedContent, strippedContent) {
    if (!originalContent || !annotatedContent) return originalContent;
    const segments = this.buildContentMap(annotatedContent);
    const stripped = segments.filter((s) => !s.isTag).map((s) => s.text).join("");
    if (stripped === originalContent) return annotatedContent;
    return annotatedContent;
  }
  buildContentMap(content) {
    const segments = [];
    const tagRegex = /<(?:mark|ruby|rt)\s+[^>]*data-annotation-id="[^"]*"[^>]*>|<\/(?:mark|ruby|rt)>/g;
    let lastIndex = 0;
    let match;
    while ((match = tagRegex.exec(content)) !== null) {
      if (match.index > lastIndex) {
        segments.push({ text: content.substring(lastIndex, match.index), isTag: false, offset: lastIndex });
      }
      segments.push({ text: match[0], isTag: true, offset: match.index });
      lastIndex = tagRegex.lastIndex;
    }
    if (lastIndex < content.length) {
      segments.push({ text: content.substring(lastIndex), isTag: false, offset: lastIndex });
    }
    return segments;
  }
  // 同步标注文件编辑回原文件
  async syncToOriginal(notePath) {
    const file = this.app.vault.getAbstractFileByPath(notePath);
    if (!(file instanceof import_obsidian.TFile)) return;
    const annotatedContent = await this.readAnnotationFile(notePath);
    const pureContent = stripAnnotationTags(annotatedContent);
    const currentContent = await this.app.vault.read(file);
    if (currentContent !== pureContent) {
      await this.app.vault.modify(file, pureContent);
    }
  }
  // 文件重命名时迁移标注文件
  async migrateAnnotationFile(oldPath, newPath) {
    const oldAnnotationPath = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(oldPath));
    if (!await this.app.vault.adapter.exists(oldAnnotationPath)) return;
    const content = await this.app.vault.adapter.read(oldAnnotationPath);
    const newAnnotationPath = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(newPath));
    const dir = newAnnotationPath.substring(0, newAnnotationPath.lastIndexOf("/"));
    if (dir && !await this.app.vault.adapter.exists(dir)) {
      await this.app.vault.adapter.mkdir(dir);
    }
    await this.app.vault.adapter.write(newAnnotationPath, content);
    await this.app.vault.adapter.remove(oldAnnotationPath);
    await this.cleanupEmptyDirs(oldAnnotationPath);
  }
  // 文件删除时清理标注文件
  async deleteAnnotationFile(notePath) {
    const annotationPath = (0, import_obsidian.normalizePath)(this.getAnnotationFilePath(notePath));
    if (await this.app.vault.adapter.exists(annotationPath)) {
      await this.app.vault.adapter.remove(annotationPath);
      await this.cleanupEmptyDirs(annotationPath);
    }
  }
  // 清理空的父目录
  async cleanupEmptyDirs(filePath) {
    const annotationsDir = (0, import_obsidian.normalizePath)(`${this.pluginDir}/annotations`);
    let dir = filePath.substring(0, filePath.lastIndexOf("/"));
    while (dir.length > annotationsDir.length) {
      if (!await this.app.vault.adapter.exists(dir)) break;
      const listed = await this.app.vault.adapter.list(dir);
      if (listed.files.length > 0 || listed.folders.length > 0) break;
      await this.app.vault.adapter.rmdir(dir, false);
      dir = dir.substring(0, dir.lastIndexOf("/"));
    }
  }
  // 解析标注文件中的所有标注
  async getAnnotations(notePath) {
    const content = await this.readAnnotationFile(notePath);
    return parseAnnotations(content);
  }
  // 添加标注
  async addAnnotation(notePath, annotation) {
    const content = await this.readAnnotationFile(notePath);
    const { content: newContent, id } = insertAnnotation(content, annotation);
    await this.writeAnnotationFile(notePath, newContent);
    const result = parseAnnotations(newContent).find((a) => a.id === id);
    return result;
  }
  // 添加全文标注（所有匹配位置共享同一 ID）
  async addFullTextAnnotation(notePath, annotation) {
    var _a;
    const content = await this.readAnnotationFile(notePath);
    const result = insertFullTextAnnotation(content, annotation);
    if (result.count === 0) return null;
    await this.writeAnnotationFile(notePath, result.content);
    const annotations = parseAnnotations(result.content);
    return (_a = annotations.find((a) => a.id === result.id)) != null ? _a : null;
  }
  // 删除标注
  async removeAnnotation(notePath, annotationId) {
    const content = await this.readAnnotationFile(notePath);
    const newContent = removeAnnotationTag(content, annotationId);
    await this.writeAnnotationFile(notePath, newContent);
  }
  // 更新标注
  async updateAnnotation(notePath, annotationId, updates) {
    const content = await this.readAnnotationFile(notePath);
    const newContent = updateAnnotationTag(content, annotationId, updates);
    await this.writeAnnotationFile(notePath, newContent);
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  defaultColor: "yellow",
  maxNoteLength: 500
};

// src/ui/SelectionMenu.ts
var import_obsidian2 = require("obsidian");
var SelectionMenu = class {
  constructor(fileManager) {
    this.menuEl = null;
    this.selectedColor = "yellow";
    this.currentNotePath = null;
    this.selectedText = "";
    this.contextBefore = "";
    this.contextAfter = "";
    this.onAddCallback = null;
    this.pendingNote = "";
    this.noteInput = null;
    this.colorContainer = null;
    this.rubyTextEnabled = false;
    this.rubyTexts = [];
    this.rubyTextInput = null;
    this.rubyTextContainer = null;
    this.rubyTextPreview = null;
    this.selectedRubyRange = null;
    this.updateRubyList = null;
    this.fileManager = fileManager;
  }
  show(params) {
    this.hide();
    this.currentNotePath = params.notePath;
    this.selectedText = params.selectedText;
    this.contextBefore = params.contextBefore;
    this.contextAfter = params.contextAfter;
    this.startLine = params.startLine;
    this.endLine = params.endLine;
    this.occurrence = params.occurrence;
    this.onAddCallback = params.onAdd;
    this.selectedColor = "yellow";
    this.pendingNote = "";
    this.rubyTexts = [];
    this.rubyTextEnabled = false;
    this.selectedRubyRange = null;
    this.menuEl = document.createElement("div");
    this.menuEl.className = "annotation-card-menu annotation-selection-menu";
    this.menuEl.addEventListener("mousedown", (e) => e.stopPropagation());
    this.menuEl.addEventListener("mouseup", (e) => e.stopPropagation());
    this.menuEl.addEventListener("focusin", (e) => e.stopPropagation());
    const header = this.menuEl.createDiv({ cls: "annotation-menu-header" });
    header.createEl("span", { text: "\u6DFB\u52A0\u6807\u6CE8", cls: "annotation-menu-title" });
    const closeBtn = header.createEl("button", { cls: "annotation-menu-close", text: "\xD7" });
    closeBtn.addEventListener("click", () => this.hide());
    const scrollableContent = this.menuEl.createDiv({ cls: "annotation-menu-scrollable-content" });
    const textPreview = scrollableContent.createDiv({ cls: "annotation-menu-preview" });
    const previewText = this.selectedText.length > 80 ? this.selectedText.substring(0, 80) + "..." : this.selectedText;
    textPreview.createEl("span", { text: `"${previewText}"` });
    const colorSection = scrollableContent.createDiv({ cls: "annotation-menu-section" });
    colorSection.createEl("label", { text: "\u9009\u62E9\u989C\u8272\u7ACB\u5373\u6807\u6CE8" });
    this.colorContainer = colorSection.createDiv({ cls: "annotation-color-buttons" });
    const colors = ["red", "yellow", "green", "blue", "purple", "none"];
    for (const c of colors) {
      const btn = this.colorContainer.createEl("button", {
        cls: `annotation-color-dot color-${c}`
      });
      if (c === this.selectedColor) btn.addClass("active");
      btn.title = COLOR_LABELS[c];
      btn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.selectedColor = c;
        this.colorContainer.querySelectorAll(".annotation-color-dot").forEach((b) => b.removeClass("active"));
        btn.addClass("active");
        if (c !== "none" && !this.pendingNote && this.rubyTexts.length === 0) {
          this.createAnnotation("");
          return;
        }
      });
    }
    const noteSection = scrollableContent.createDiv({ cls: "annotation-menu-section" });
    const noteLabel = noteSection.createDiv({ cls: "annotation-note-label-row" });
    noteLabel.createEl("label", { text: "\u6216\u6DFB\u52A0\u6279\u6CE8" });
    const charCount = noteLabel.createSpan({ cls: "annotation-char-count", text: "(0/400)" });
    this.noteInput = noteSection.createEl("textarea", {
      cls: "annotation-note-input-small",
      placeholder: "\u8F93\u5165\u6279\u6CE8\u5185\u5BB9\uFF08\u53EF\u9009\uFF0C\u6700\u591A400\u5B57\uFF09..."
    });
    this.noteInput.setAttribute("maxlength", "400");
    this.noteInput.addEventListener("input", () => {
      const len = this.noteInput.value.length;
      this.pendingNote = this.noteInput.value;
      charCount.textContent = `(${len}/400)`;
      charCount.toggleClass("annotation-char-count-error", len > 400);
    });
    this.buildRubySection(noteSection);
    const actionRow = this.menuEl.createDiv({ cls: "annotation-action-row" });
    const copyBtn = actionRow.createEl("button", {
      cls: "annotation-btn annotation-btn-secondary annotation-btn-small",
      text: "\u590D\u5236"
    });
    copyBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      navigator.clipboard.writeText(this.selectedText);
      new import_obsidian2.Notice("\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F");
    });
    const saveBtn = actionRow.createEl("button", {
      cls: "annotation-btn annotation-btn-primary annotation-btn-small",
      text: "\u4FDD\u5B58"
    });
    saveBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      const note = this.noteInput.value.trim();
      if (note.length > 400) {
        new import_obsidian2.Notice("\u6279\u6CE8\u5185\u5BB9\u4E0D\u80FD\u8D85\u8FC7400\u5B57");
        return;
      }
      await this.createAnnotation(note);
    });
    const fullTextBtn = actionRow.createEl("button", {
      cls: "annotation-btn annotation-btn-secondary annotation-btn-small",
      text: "\u5168\u6587\u6807\u6CE8"
    });
    fullTextBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      const note = this.noteInput.value.trim();
      if (note.length > 400) {
        new import_obsidian2.Notice("\u6279\u6CE8\u5185\u5BB9\u4E0D\u80FD\u8D85\u8FC7400\u5B57");
        return;
      }
      await this.createAnnotation(note, true);
    });
    document.body.appendChild(this.menuEl);
    requestAnimationFrame(() => {
      if (!this.menuEl) return;
      const menuWidth = 280;
      const menuHeight = this.menuEl.offsetHeight || 200;
      let menuX = params.x + 10;
      let menuY = params.y + 10;
      if (menuX + menuWidth > window.innerWidth) {
        menuX = params.x - menuWidth - 10;
      }
      const threshold = window.innerHeight * 0.4;
      if (params.y > threshold) {
        menuY = params.y - menuHeight - 10;
      }
      if (menuY + menuHeight > window.innerHeight) {
        menuY = window.innerHeight - menuHeight - 10;
      }
      this.menuEl.style.left = `${Math.max(10, menuX)}px`;
      this.menuEl.style.top = `${Math.max(10, menuY)}px`;
    });
    const clickHandler = (e) => {
      if (this.menuEl && !this.menuEl.contains(e.target)) {
        this.hide();
        document.removeEventListener("click", clickHandler);
      }
    };
    setTimeout(() => document.addEventListener("click", clickHandler), 10);
  }
  buildRubySection(parent) {
    const rubySection = parent.createDiv({ cls: "annotation-ruby-section" });
    const rubyRow = rubySection.createDiv({ cls: "annotation-ruby-row" });
    const rubyCheckbox = rubyRow.createEl("input", {
      type: "checkbox",
      cls: "annotation-ruby-checkbox"
    });
    rubyCheckbox.checked = this.rubyTextEnabled;
    rubyCheckbox.addEventListener("change", () => {
      var _a;
      this.rubyTextEnabled = rubyCheckbox.checked;
      if (this.rubyTextEnabled) {
        this.rubyTextContainer.style.display = "block";
        this.rubyTextInput.focus();
        requestAnimationFrame(() => this.adjustMenuPosition());
      } else {
        this.rubyTextContainer.style.display = "none";
        this.rubyTexts = [];
        (_a = this.updateRubyList) == null ? void 0 : _a.call(this);
      }
    });
    rubyRow.createEl("label", { text: "\u6CE8\u97F3" });
    this.rubyTextContainer = rubySection.createDiv({ cls: "annotation-ruby-input-container" });
    if (!this.rubyTextEnabled) {
      this.rubyTextContainer.style.display = "none";
    }
    const rubyPreview = this.rubyTextContainer.createDiv({ cls: "annotation-ruby-preview" });
    rubyPreview.createEl("label", { text: "\u5212\u9009\u9700\u8981\u6CE8\u97F3\u7684\u6587\u5B57\uFF1A" });
    this.rubyTextPreview = rubyPreview.createDiv({
      cls: "annotation-ruby-text-preview",
      text: this.selectedText
    });
    this.rubyTextPreview.setAttribute("data-selected-text", this.selectedText);
    this.rubyTextPreview.addEventListener("mouseup", (e) => {
      e.stopPropagation();
      setTimeout(() => {
        const sel = window.getSelection();
        if (sel && !sel.isCollapsed) {
          const range = sel.getRangeAt(0);
          const offset = calculateRangeOffsetInElement(range, this.rubyTextPreview);
          if (offset) {
            this.selectedRubyRange = { start: offset.start, end: offset.end };
          }
        }
      }, 10);
    });
    const rubyInputRow = this.rubyTextContainer.createDiv({ cls: "annotation-ruby-input-row" });
    rubyInputRow.createEl("label", { text: "\u6CE8\u97F3\u5185\u5BB9\uFF1A" });
    this.rubyTextInput = rubyInputRow.createEl("input", {
      type: "text",
      cls: "annotation-ruby-input",
      placeholder: "\u8F93\u5165\u6CE8\u97F3\u5185\u5BB9..."
    });
    this.rubyTextInput.addEventListener("focus", () => {
      if (this.selectedRubyRange) {
        const sel = window.getSelection();
        if (sel) {
          const textNode = this.rubyTextPreview.firstChild;
          if (textNode) {
            const range = document.createRange();
            range.setStart(textNode, this.selectedRubyRange.start);
            range.setEnd(textNode, this.selectedRubyRange.end);
            sel.removeAllRanges();
            sel.addRange(range);
          }
        }
      }
    });
    const addRubyBtn = rubyInputRow.createEl("button", {
      text: "\u6DFB\u52A0",
      cls: "annotation-btn annotation-btn-small"
    });
    addRubyBtn.addEventListener("click", () => this.addRuby());
    const rubyListContainer = this.rubyTextContainer.createDiv({ cls: "annotation-ruby-list-container" });
    rubyListContainer.createEl("label", { text: "\u5DF2\u6DFB\u52A0\u7684\u6CE8\u97F3\uFF1A" });
    const rubyList = rubyListContainer.createDiv({ cls: "annotation-ruby-list" });
    this.updateRubyList = () => {
      rubyList.empty();
      if (this.rubyTexts.length === 0) {
        rubyList.createDiv({ text: "\u6682\u65E0\u6CE8\u97F3", cls: "annotation-ruby-empty" });
      } else {
        this.rubyTexts.forEach((ruby, index) => {
          const item = rubyList.createDiv({ cls: "annotation-ruby-item" });
          item.createSpan({
            text: `${this.selectedText.substring(ruby.startIndex, ruby.startIndex + ruby.length)} \u2192 ${ruby.ruby}`,
            cls: "annotation-ruby-item-text"
          });
          const deleteBtn = item.createEl("button", {
            text: "\xD7",
            cls: "annotation-ruby-item-delete"
          });
          deleteBtn.addEventListener("click", (e) => {
            var _a;
            e.stopPropagation();
            this.rubyTexts.splice(index, 1);
            (_a = this.updateRubyList) == null ? void 0 : _a.call(this);
          });
        });
      }
    };
    this.updateRubyList();
  }
  addRuby() {
    var _a, _b;
    const sel = window.getSelection();
    let selectedRubyText = "";
    let rubyStart = 0;
    if (sel && !sel.isCollapsed) {
      selectedRubyText = sel.toString();
      const range = sel.getRangeAt(0);
      const offset = calculateRangeOffsetInElement(range, this.rubyTextPreview);
      if (offset) rubyStart = offset.start;
    } else if (this.selectedRubyRange) {
      selectedRubyText = this.selectedText.substring(
        this.selectedRubyRange.start,
        this.selectedRubyRange.end
      );
      rubyStart = this.selectedRubyRange.start;
    }
    const rubyValue = this.rubyTextInput.value.trim();
    if (selectedRubyText && rubyValue) {
      this.rubyTexts.push({ startIndex: rubyStart, length: selectedRubyText.length, ruby: rubyValue });
      this.rubyTextInput.value = "";
      this.selectedRubyRange = null;
      sel == null ? void 0 : sel.removeAllRanges();
      (_a = this.updateRubyList) == null ? void 0 : _a.call(this);
    } else if (!selectedRubyText && this.selectedText.length === 1 && rubyValue) {
      this.rubyTexts.push({ startIndex: 0, length: 1, ruby: rubyValue });
      this.rubyTextInput.value = "";
      this.selectedRubyRange = null;
      (_b = this.updateRubyList) == null ? void 0 : _b.call(this);
    } else if (!selectedRubyText) {
      new import_obsidian2.Notice("\u8BF7\u5148\u5212\u9009\u9700\u8981\u6CE8\u97F3\u7684\u6587\u5B57");
    } else {
      new import_obsidian2.Notice("\u8BF7\u8F93\u5165\u6CE8\u97F3\u5185\u5BB9");
    }
  }
  async createAnnotation(note, isFullText = false) {
    var _a;
    if (!this.currentNotePath) return;
    try {
      const rubyTexts = !isFullText && this.rubyTextEnabled && this.rubyTexts.length > 0 ? this.rubyTexts : void 0;
      let result;
      if (isFullText) {
        result = await this.fileManager.addFullTextAnnotation(this.currentNotePath, {
          text: this.selectedText,
          color: this.selectedColor,
          note: note || void 0,
          isFullText: true
        });
      } else {
        result = await this.fileManager.addAnnotation(this.currentNotePath, {
          text: this.selectedText,
          color: this.selectedColor,
          note: note || void 0,
          rubyTexts,
          contextBefore: this.contextBefore,
          contextAfter: this.contextAfter,
          startLine: this.startLine,
          endLine: this.endLine,
          occurrence: this.occurrence
        });
      }
      if (result) {
        (_a = window.getSelection()) == null ? void 0 : _a.removeAllRanges();
        this.hide();
        if (this.onAddCallback) {
          await new Promise((resolve) => setTimeout(resolve, 100));
          this.onAddCallback();
        }
        if (isFullText) {
          new import_obsidian2.Notice(`\u5168\u6587\u6807\u6CE8\u5DF2\u6DFB\u52A0\uFF08\u5171 ${result.positions.length} \u5904\uFF09`);
        } else {
          new import_obsidian2.Notice(note || rubyTexts ? "\u6807\u6CE8\u548C\u6279\u6CE8\u5DF2\u6DFB\u52A0" : "\u6807\u6CE8\u5DF2\u6DFB\u52A0");
        }
      } else {
        new import_obsidian2.Notice("\u672A\u80FD\u5728\u6587\u4EF6\u4E2D\u627E\u5230\u9009\u4E2D\u7684\u6587\u5B57");
      }
    } catch (e) {
      console.error("\u6DFB\u52A0\u6807\u6CE8\u5931\u8D25:", e);
      new import_obsidian2.Notice("\u6DFB\u52A0\u6807\u6CE8\u5931\u8D25");
    }
  }
  hide() {
    if (this.menuEl) {
      this.menuEl.remove();
      this.menuEl = null;
    }
  }
  adjustMenuPosition() {
    if (!this.menuEl) return;
    const menuHeight = this.menuEl.offsetHeight || 200;
    const currentTop = parseInt(this.menuEl.style.top || "0", 10);
    if (currentTop + menuHeight > window.innerHeight - 20) {
      this.menuEl.style.top = `${Math.max(10, window.innerHeight - menuHeight - 20)}px`;
    }
  }
};

// src/ui/AnnotationMenu.ts
var import_obsidian4 = require("obsidian");

// src/ui/EditNoteModal.ts
var import_obsidian3 = require("obsidian");
var EditNoteModal = class extends import_obsidian3.Modal {
  constructor(app, params, onSave) {
    super(app);
    this.noteInput = null;
    this.rubyTextEnabled = false;
    this.rubyTexts = [];
    this.rubyTextInput = null;
    this.rubyTextContainer = null;
    this.rubyTextPreview = null;
    this.selectedRubyRange = null;
    this.updateRubyList = null;
    this.annotationText = params.text;
    this.currentNote = params.note;
    this.currentColor = params.color;
    this.currentRubyTexts = params.rubyTexts || [];
    this.rubyTexts = [...this.currentRubyTexts];
    this.rubyTextEnabled = this.rubyTexts.length > 0;
    this.onSave = onSave;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("annotation-note-modal");
    this.containerEl.addEventListener("mousedown", (e) => e.stopPropagation());
    this.containerEl.addEventListener("mouseup", (e) => e.stopPropagation());
    this.containerEl.addEventListener("focusin", (e) => e.stopPropagation());
    contentEl.createEl("h3", { text: this.currentNote ? "\u7F16\u8F91\u6279\u6CE8" : "\u6DFB\u52A0\u6279\u6CE8" });
    const previewEl = contentEl.createDiv({ cls: "annotation-modal-preview" });
    previewEl.createEl("strong", { text: "\u6807\u6CE8\u6587\u5B57\uFF1A" });
    const previewText = this.annotationText.length > 50 ? this.annotationText.substring(0, 50) + "..." : this.annotationText;
    previewEl.createEl("span", { text: previewText });
    const colorContainer = contentEl.createDiv({ cls: "annotation-color-picker" });
    colorContainer.createEl("label", { text: "\u6807\u6CE8\u989C\u8272\uFF1A" });
    const colors = ["red", "yellow", "green", "blue", "purple", "none"];
    for (const c of colors) {
      const btn = colorContainer.createEl("button", { cls: `annotation-color-dot color-${c}` });
      btn.title = COLOR_LABELS[c];
      if (c === this.currentColor) btn.addClass("active");
      btn.addEventListener("click", () => {
        colorContainer.querySelectorAll(".annotation-color-dot").forEach((b) => b.removeClass("active"));
        btn.addClass("active");
        this.currentColor = c;
      });
    }
    const noteContainer = contentEl.createDiv({ cls: "annotation-note-container" });
    noteContainer.createEl("label", { text: "\u6279\u6CE8\u5185\u5BB9\uFF08\u6700\u591A400\u5B57\uFF09\uFF1A" });
    this.noteInput = noteContainer.createEl("textarea", { cls: "annotation-note-input" });
    this.noteInput.setAttribute("maxlength", "400");
    this.noteInput.setAttribute("rows", "4");
    this.noteInput.setAttribute("placeholder", "\u8BF7\u8F93\u5165\u6279\u6CE8\u5185\u5BB9...");
    this.noteInput.value = this.currentNote;
    const charCount = noteContainer.createDiv({
      cls: "annotation-char-count",
      text: `${this.currentNote.length}/400`
    });
    this.noteInput.addEventListener("input", () => {
      var _a, _b;
      const len = (_b = (_a = this.noteInput) == null ? void 0 : _a.value.length) != null ? _b : 0;
      charCount.textContent = `${len}/400`;
      charCount.toggleClass("annotation-char-count-error", len > 400);
    });
    this.buildRubySection(contentEl);
    const buttonContainer = contentEl.createDiv({ cls: "annotation-modal-buttons" });
    buttonContainer.createEl("button", {
      text: "\u53D6\u6D88",
      cls: "annotation-btn annotation-btn-secondary"
    }).addEventListener("click", () => this.close());
    buttonContainer.createEl("button", {
      text: "\u4FDD\u5B58",
      cls: "annotation-btn annotation-btn-primary"
    }).addEventListener("click", () => {
      var _a, _b;
      const note = (_b = (_a = this.noteInput) == null ? void 0 : _a.value) != null ? _b : "";
      const rubyTexts = this.rubyTextEnabled && this.rubyTexts.length > 0 ? this.rubyTexts : void 0;
      this.onSave(note, this.currentColor, rubyTexts);
      this.close();
    });
  }
  buildRubySection(parent) {
    const rubySection = parent.createDiv({ cls: "annotation-ruby-section" });
    const rubyRow = rubySection.createDiv({ cls: "annotation-ruby-row" });
    const rubyCheckbox = rubyRow.createEl("input", {
      type: "checkbox",
      cls: "annotation-ruby-checkbox"
    });
    rubyCheckbox.checked = this.rubyTextEnabled;
    rubyCheckbox.addEventListener("change", () => {
      var _a;
      this.rubyTextEnabled = rubyCheckbox.checked;
      if (this.rubyTextEnabled) {
        this.rubyTextContainer.style.display = "block";
        this.rubyTextInput.focus();
      } else {
        this.rubyTextContainer.style.display = "none";
        this.rubyTexts = [];
        (_a = this.updateRubyList) == null ? void 0 : _a.call(this);
      }
    });
    rubyRow.createEl("label", { text: "\u6CE8\u97F3" });
    this.rubyTextContainer = rubySection.createDiv({ cls: "annotation-ruby-input-container" });
    this.rubyTextContainer.style.display = this.rubyTextEnabled ? "block" : "none";
    const rubyPreview = this.rubyTextContainer.createDiv({ cls: "annotation-ruby-preview" });
    rubyPreview.createEl("label", { text: "\u5212\u9009\u9700\u8981\u6CE8\u97F3\u7684\u6587\u5B57\uFF1A" });
    this.rubyTextPreview = rubyPreview.createDiv({
      cls: "annotation-ruby-text-preview",
      text: this.annotationText
    });
    this.rubyTextPreview.addEventListener("mouseup", (e) => {
      e.stopPropagation();
      setTimeout(() => {
        const sel = window.getSelection();
        if (sel && !sel.isCollapsed) {
          const range = sel.getRangeAt(0);
          let start = 0;
          const textNode = this.rubyTextPreview.firstChild;
          if (textNode && range.startContainer === textNode) {
            start = range.startOffset;
          }
          this.selectedRubyRange = {
            start,
            end: start + sel.toString().length
          };
        }
      }, 10);
    });
    const rubyInputRow = this.rubyTextContainer.createDiv({ cls: "annotation-ruby-input-row" });
    rubyInputRow.createEl("label", { text: "\u6CE8\u97F3\u5185\u5BB9\uFF1A" });
    this.rubyTextInput = rubyInputRow.createEl("input", {
      type: "text",
      cls: "annotation-ruby-input",
      placeholder: "\u8F93\u5165\u6CE8\u97F3\u5185\u5BB9..."
    });
    const addRubyBtn = rubyInputRow.createEl("button", {
      text: "\u6DFB\u52A0",
      cls: "annotation-btn annotation-btn-small"
    });
    addRubyBtn.addEventListener("click", () => {
      var _a, _b;
      const sel = window.getSelection();
      let text = "";
      let start = 0;
      if (sel && !sel.isCollapsed) {
        text = sel.toString();
        const range = sel.getRangeAt(0);
        const textNode = this.rubyTextPreview.firstChild;
        if (textNode && range.startContainer === textNode) {
          start = range.startOffset;
        }
      } else if (this.selectedRubyRange) {
        text = this.annotationText.substring(
          this.selectedRubyRange.start,
          this.selectedRubyRange.end
        );
        start = this.selectedRubyRange.start;
      }
      const value = this.rubyTextInput.value.trim();
      if (text && value) {
        this.rubyTexts.push({ startIndex: start, length: text.length, ruby: value });
        this.rubyTextInput.value = "";
        this.selectedRubyRange = null;
        sel == null ? void 0 : sel.removeAllRanges();
        (_a = this.updateRubyList) == null ? void 0 : _a.call(this);
      } else if (!text && this.annotationText.length === 1 && value) {
        this.rubyTexts.push({ startIndex: 0, length: 1, ruby: value });
        this.rubyTextInput.value = "";
        (_b = this.updateRubyList) == null ? void 0 : _b.call(this);
      } else {
        new import_obsidian3.Notice("\u8BF7\u5148\u5212\u9009\u9700\u8981\u6CE8\u97F3\u7684\u6587\u5B57\u5E76\u8F93\u5165\u6CE8\u97F3\u5185\u5BB9");
      }
    });
    const rubyListContainer = this.rubyTextContainer.createDiv({ cls: "annotation-ruby-list-container" });
    rubyListContainer.createEl("label", { text: "\u5DF2\u6DFB\u52A0\u7684\u6CE8\u97F3\uFF1A" });
    const rubyList = rubyListContainer.createDiv({ cls: "annotation-ruby-list" });
    this.updateRubyList = () => {
      rubyList.empty();
      if (this.rubyTexts.length === 0) {
        rubyList.createDiv({ text: "\u6682\u65E0\u6CE8\u97F3", cls: "annotation-ruby-empty" });
      } else {
        this.rubyTexts.forEach((ruby, index) => {
          const item = rubyList.createDiv({ cls: "annotation-ruby-item" });
          item.createSpan({
            text: `${this.annotationText.substring(ruby.startIndex, ruby.startIndex + ruby.length)} \u2192 ${ruby.ruby}`,
            cls: "annotation-ruby-item-text"
          });
          const deleteBtn = item.createEl("button", { text: "\xD7", cls: "annotation-ruby-item-delete" });
          deleteBtn.addEventListener("click", (e) => {
            var _a;
            e.stopPropagation();
            this.rubyTexts.splice(index, 1);
            (_a = this.updateRubyList) == null ? void 0 : _a.call(this);
          });
        });
      }
    };
    this.updateRubyList();
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/ui/AnnotationMenu.ts
var AnnotationMenu = class {
  constructor(fileManager) {
    this.menuEl = null;
    this.fileManager = fileManager;
  }
  show(params) {
    this.hide();
    const { annotation, notePath, onUpdate } = params;
    this.menuEl = document.createElement("div");
    this.menuEl.className = "annotation-card-menu annotation-view-menu";
    const header = this.menuEl.createDiv({ cls: "annotation-menu-header" });
    header.createEl("span", { text: "\u6807\u6CE8\u8BE6\u60C5", cls: "annotation-menu-title" });
    const closeBtn = header.createEl("button", { cls: "annotation-menu-close", text: "\xD7" });
    closeBtn.addEventListener("click", () => this.hide());
    const textPreview = this.menuEl.createDiv({ cls: "annotation-menu-text" });
    const previewText = annotation.text.length > 80 ? annotation.text.substring(0, 80) + "..." : annotation.text;
    textPreview.createEl("span", { text: `"${previewText}"` });
    if (annotation.isFullText && annotation.positions.length > 1) {
      const fullTextHint = this.menuEl.createDiv({ cls: "annotation-fulltext-hint" });
      fullTextHint.createEl("span", { text: `\u5168\u6587\u6807\u6CE8\uFF08\u5171 ${annotation.positions.length} \u5904\uFF09` });
    }
    if (annotation.note) {
      const noteSection = this.menuEl.createDiv({ cls: "annotation-menu-note" });
      noteSection.createEl("label", { text: "\u6279\u6CE8\u5185\u5BB9" });
      noteSection.createEl("div", { cls: "annotation-note-text", text: annotation.note });
    }
    const colorSection = this.menuEl.createDiv({ cls: "annotation-menu-section" });
    colorSection.createEl("label", { text: "\u6807\u6CE8\u989C\u8272" });
    const colorContainer = colorSection.createDiv({ cls: "annotation-color-buttons" });
    const colors = ["red", "yellow", "green", "blue", "purple", "none"];
    for (const c of colors) {
      const btn = colorContainer.createEl("button", {
        cls: `annotation-color-dot color-${c}`
      });
      if (c === annotation.color) btn.addClass("active");
      btn.title = COLOR_LABELS[c];
      btn.addEventListener("click", async (e) => {
        e.stopPropagation();
        if (c !== annotation.color) {
          await this.fileManager.updateAnnotation(notePath, annotation.id, { color: c });
          this.hide();
          onUpdate();
          new import_obsidian4.Notice("\u6807\u6CE8\u989C\u8272\u5DF2\u4FEE\u6539");
        }
      });
    }
    const actions = this.menuEl.createDiv({ cls: "annotation-menu-actions" });
    const editBtn = actions.createEl("button", {
      cls: "annotation-btn annotation-btn-secondary",
      text: "\u7F16\u8F91\u6279\u6CE8"
    });
    editBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.showEditModal(annotation, notePath, onUpdate);
    });
    const copyBtn = actions.createEl("button", {
      cls: "annotation-btn annotation-btn-secondary",
      text: "\u590D\u5236\u539F\u6587"
    });
    copyBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      navigator.clipboard.writeText(annotation.text);
      new import_obsidian4.Notice("\u5DF2\u590D\u5236\u539F\u6587\u5230\u526A\u8D34\u677F");
    });
    const deleteBtn = actions.createEl("button", {
      cls: "annotation-btn annotation-btn-danger",
      text: "\u5220\u9664"
    });
    deleteBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      const msg = annotation.isFullText && annotation.positions.length > 1 ? `\u786E\u5B9A\u5220\u9664\u5168\u90E8 ${annotation.positions.length} \u5904\u6807\u6CE8\uFF1F` : "\u786E\u5B9A\u5220\u9664\u6B64\u6807\u6CE8\uFF1F";
      if (!confirm(msg)) return;
      await this.fileManager.removeAnnotation(notePath, annotation.id);
      this.hide();
      onUpdate();
      new import_obsidian4.Notice("\u6807\u6CE8\u5DF2\u5220\u9664");
    });
    document.body.appendChild(this.menuEl);
    const menuWidth = 300;
    const menuHeight = this.menuEl.offsetHeight || 250;
    let menuX = params.x + 10;
    let menuY = params.y + 10;
    if (menuX + menuWidth > window.innerWidth) {
      menuX = params.x - menuWidth - 10;
    }
    const threshold = window.innerHeight * 0.4;
    if (params.y > threshold) {
      menuY = params.y - menuHeight - 10;
    }
    if (menuY + menuHeight > window.innerHeight) {
      menuY = window.innerHeight - menuHeight - 10;
    }
    this.menuEl.style.left = `${Math.max(10, menuX)}px`;
    this.menuEl.style.top = `${Math.max(10, menuY)}px`;
    const clickHandler = (e) => {
      if (this.menuEl && !this.menuEl.contains(e.target)) {
        this.hide();
        document.removeEventListener("click", clickHandler);
      }
    };
    setTimeout(() => document.addEventListener("click", clickHandler), 10);
  }
  showEditModal(annotation, notePath, onUpdate) {
    this.hide();
    const modal = new EditNoteModal(
      this.fileManager.app,
      {
        text: annotation.text,
        note: annotation.note,
        color: annotation.color,
        rubyTexts: annotation.rubyTexts
      },
      async (note, color, rubyTexts) => {
        await this.fileManager.updateAnnotation(notePath, annotation.id, {
          color,
          note,
          rubyTexts
        });
        onUpdate();
        new import_obsidian4.Notice("\u6279\u6CE8\u5DF2\u66F4\u65B0");
      }
    );
    modal.open();
  }
  hide() {
    if (this.menuEl) {
      this.menuEl.remove();
      this.menuEl = null;
    }
  }
};

// src/ui/AnnotationListPanel.ts
var import_obsidian5 = require("obsidian");
var AnnotationListPanel = class {
  constructor(app, fileManager) {
    this.panelEl = null;
    this.listBtn = null;
    this.currentNotePath = null;
    this.onUpdate = null;
    this.sortOption = "position-asc";
    this.panelClickHandler = null;
    this.app = app;
    this.fileManager = fileManager;
  }
  show(params) {
    this.currentNotePath = params.notePath;
    this.onUpdate = params.onUpdate;
    this.hide();
    this.createListButton();
  }
  // 创建固定定位的列表按钮（挂载到 body，不随内容滚动）
  createListButton() {
    this.listBtn = document.createElement("div");
    this.listBtn.className = "annotation-list-btn";
    this.listBtn.innerHTML = "<span>\u{1F4DD}</span>";
    this.listBtn.title = "\u67E5\u770B\u6807\u6CE8";
    this.listBtn.style.position = "fixed";
    this.listBtn.style.right = "20px";
    this.listBtn.style.top = "50%";
    this.listBtn.style.transform = "translateY(-50%)";
    document.body.appendChild(this.listBtn);
    this.listBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      if (this.panelEl && this.panelEl.style.display !== "none") {
        this.hidePanel();
      } else {
        this.showPanel();
      }
    });
  }
  async showPanel() {
    if (!this.currentNotePath) return;
    this.hidePanel();
    this.panelEl = document.createElement("div");
    this.panelEl.className = "annotation-list-panel";
    const header = this.panelEl.createDiv({ cls: "annotation-list-header" });
    header.createEl("span", { text: "\u6807\u6CE8\u5217\u8868", cls: "annotation-list-title" });
    const sortContainer = header.createDiv({ cls: "annotation-list-sort-container" });
    const sortSelect = sortContainer.createEl("select", { cls: "annotation-list-sort-select" });
    sortSelect.innerHTML = `
      <option value="position-asc" ${this.sortOption === "position-asc" ? "selected" : ""}>\u6309\u5185\u5BB9\u987A\u5E8F\uFF08\u4ECE\u4E0A\u5230\u4E0B\uFF09</option>
      <option value="position-desc" ${this.sortOption === "position-desc" ? "selected" : ""}>\u6309\u5185\u5BB9\u5012\u5E8F\uFF08\u4ECE\u4E0B\u5230\u4E0A\uFF09</option>
      <option value="time-asc" ${this.sortOption === "time-asc" ? "selected" : ""}>\u6309\u65F6\u95F4\u6B63\u5E8F\uFF08\u4ECE\u65E7\u5230\u65B0\uFF09</option>
      <option value="time-desc" ${this.sortOption === "time-desc" ? "selected" : ""}>\u6309\u65F6\u95F4\u5012\u5E8F\uFF08\u4ECE\u65B0\u5230\u65E7\uFF09</option>
    `;
    sortSelect.addEventListener("change", () => {
      this.sortOption = sortSelect.value;
      this.refreshContent();
    });
    const closeBtn = header.createEl("button", { cls: "annotation-list-close", text: "\xD7" });
    closeBtn.addEventListener("click", () => this.hidePanel());
    const content = this.panelEl.createDiv({ cls: "annotation-list-content" });
    this.renderContent(content);
    document.body.appendChild(this.panelEl);
    this.panelEl.style.position = "fixed";
    this.panelEl.style.right = "60px";
    this.panelEl.style.top = "50%";
    this.panelEl.style.transform = "translateY(-50%)";
    this.panelClickHandler = (e) => {
      if (this.panelEl && !this.panelEl.contains(e.target) && (!this.listBtn || !this.listBtn.contains(e.target))) {
        this.hidePanel();
      }
    };
    setTimeout(() => {
      if (this.panelClickHandler) {
        document.addEventListener("click", this.panelClickHandler);
      }
    }, 10);
  }
  async renderContent(content) {
    content.empty();
    if (!this.currentNotePath) {
      content.createDiv({ cls: "annotation-list-empty", text: "\u6682\u65E0\u6807\u6CE8" });
      return;
    }
    let annotations;
    try {
      annotations = await this.fileManager.getAnnotations(this.currentNotePath);
    } catch (e) {
      content.createDiv({ cls: "annotation-list-empty", text: "\u6682\u65E0\u6807\u6CE8" });
      return;
    }
    if (annotations.length === 0) {
      content.createDiv({ cls: "annotation-list-empty", text: "\u6682\u65E0\u6807\u6CE8" });
      return;
    }
    const sorted = [...annotations];
    switch (this.sortOption) {
      case "position-asc":
        sorted.sort((a, b) => a.positions[0].start - b.positions[0].start);
        break;
      case "position-desc":
        sorted.sort((a, b) => b.positions[0].start - a.positions[0].start);
        break;
      case "time-asc":
        sorted.sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime());
        break;
      case "time-desc":
        sorted.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
        break;
    }
    for (const annotation of sorted) {
      const item = content.createDiv({ cls: "annotation-list-item" });
      item.createSpan({ cls: `annotation-list-dot color-${annotation.color}` });
      if (annotation.isFullText && annotation.positions.length > 1) {
        const badge = item.createSpan({ cls: "annotation-list-badge" });
        badge.textContent = `\u5168\u6587(${annotation.positions.length})`;
      }
      const textPreview = item.createDiv({ cls: "annotation-list-text" });
      const previewText = annotation.text.length > 60 ? annotation.text.substring(0, 60) + "..." : annotation.text;
      textPreview.textContent = previewText;
      if (annotation.note) {
        const notePreview = item.createDiv({ cls: "annotation-list-note" });
        const noteText = annotation.note.length > 100 ? annotation.note.substring(0, 100) + "..." : annotation.note;
        notePreview.textContent = `\u{1F4DD} ${noteText}`;
      }
      item.addEventListener("click", () => {
        this.scrollToAnnotation(annotation);
      });
      item.addEventListener("contextmenu", (e) => {
        e.preventDefault();
        e.stopPropagation();
        this.showContextMenu(annotation, e.clientX, e.clientY);
      });
    }
  }
  async refreshContent() {
    if (!this.panelEl) return;
    const content = this.panelEl.querySelector(".annotation-list-content");
    if (content) {
      await this.renderContent(content);
    }
  }
  showContextMenu(annotation, x, y) {
    document.querySelectorAll(".annotation-context-menu").forEach((el) => el.remove());
    const menu = document.createElement("div");
    menu.className = "annotation-context-menu";
    const deleteBtn = menu.createEl("button", {
      text: "\u5220\u9664\u6807\u6CE8",
      cls: "annotation-context-menu-item annotation-context-menu-danger"
    });
    deleteBtn.addEventListener("click", async () => {
      var _a;
      if (!this.currentNotePath) return;
      await this.fileManager.removeAnnotation(this.currentNotePath, annotation.id);
      menu.remove();
      new import_obsidian5.Notice("\u6807\u6CE8\u5DF2\u5220\u9664");
      this.hidePanel();
      (_a = this.onUpdate) == null ? void 0 : _a.call(this);
    });
    document.body.appendChild(menu);
    const menuWidth = 120;
    const menuHeight = menu.offsetHeight || 80;
    let menuX = x + 10;
    let menuY = y + 10;
    if (menuX + menuWidth > window.innerWidth) menuX = x - menuWidth - 10;
    if (menuY + menuHeight > window.innerHeight) menuY = window.innerHeight - menuHeight - 10;
    menu.style.left = `${Math.max(10, menuX)}px`;
    menu.style.top = `${Math.max(10, menuY)}px`;
    const handler = (e) => {
      if (!menu.contains(e.target)) {
        menu.remove();
        document.removeEventListener("click", handler);
      }
    };
    setTimeout(() => document.addEventListener("click", handler), 10);
  }
  // 滚动到指定标注位置并高亮
  async scrollToAnnotation(annotation) {
    var _a;
    this.hidePanel();
    const content = await this.fileManager.readAnnotationFile(this.currentNotePath);
    const lineIndex = content.substring(0, annotation.positions[0].start).split("\n").length - 1;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (view == null ? void 0 : view.previewMode) {
      const renderer = view.previewMode.renderer;
      if (renderer && typeof renderer.applyScroll === "function") {
        renderer.applyScroll(lineIndex, { center: true });
      }
    }
    await new Promise((resolve) => setTimeout(resolve, 300));
    const containerEl = (_a = view == null ? void 0 : view.previewMode) == null ? void 0 : _a.containerEl;
    const highlightEls = containerEl == null ? void 0 : containerEl.querySelectorAll(
      `mark[data-annotation-id="${annotation.id}"]`
    );
    if (highlightEls && highlightEls.length > 0) {
      this.highlightElements(Array.from(highlightEls));
    } else {
      new import_obsidian5.Notice("\u672A\u80FD\u5B9A\u4F4D\u5230\u6807\u6CE8\uFF0C\u53EF\u80FD\u6587\u6863\u5185\u5BB9\u5DF2\u66F4\u6539");
    }
  }
  // 给标注元素添加临时蓝色边框高亮
  highlightElements(elements) {
    for (const el of elements) {
      el.style.transition = "box-shadow 0.3s ease";
      el.style.boxShadow = "0 0 0 3px var(--interactive-accent)";
    }
    setTimeout(() => {
      for (const el of elements) {
        el.style.boxShadow = "";
      }
    }, 2e3);
  }
  hidePanel() {
    if (this.panelClickHandler) {
      document.removeEventListener("click", this.panelClickHandler);
      this.panelClickHandler = null;
    }
    if (this.panelEl) {
      this.panelEl.remove();
      this.panelEl = null;
    }
  }
  hide() {
    this.hidePanel();
    if (this.listBtn) {
      this.listBtn.remove();
      this.listBtn = null;
    }
  }
  async refresh() {
    if (this.panelEl) {
      await this.refreshContent();
    }
  }
};

// src/main.ts
var AnnotationPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    // 原始文件路径 → 标注文件路径的映射
    this.activeAnnotationSessions = /* @__PURE__ */ new Map();
    // DOM 元素 → 源文件行号的映射（由 MarkdownPostProcessor 填充）
    this.sectionLineMap = /* @__PURE__ */ new WeakMap();
  }
  async onload() {
    var _a;
    await this.loadSettings();
    const pluginDir = (_a = this.manifest.dir) != null ? _a : ".obsidian/plugins/obsidian-annotation-marker";
    this.fileManager = new AnnotationFileManager(this.app, pluginDir);
    this.selectionMenu = new SelectionMenu(this.fileManager);
    this.annotationMenu = new AnnotationMenu(this.fileManager);
    this.annotationListPanel = new AnnotationListPanel(this.app, this.fileManager);
    this.registerEvents();
    this.registerCommands();
    this.registerCacheListeners();
    this.registerAnnotationInteraction();
    this.registerSectionLineCapture();
    this.addRibbonIcon("lucide-highlighter", "\u6807\u6CE8\u6A21\u5F0F", () => {
      this.toggleAnnotationView();
    });
  }
  onunload() {
    for (const [, annotationPath] of this.activeAnnotationSessions) {
      this.removeFakeTFile(annotationPath);
      this.removeMetadataCache(annotationPath);
    }
    this.activeAnnotationSessions.clear();
    this.selectionMenu.hide();
    this.annotationMenu.hide();
    this.annotationListPanel.hide();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ========== 假文件管理 ==========
  // 构造假 TFile 并注入 vault 的 fileMap
  createFakeTFile(path) {
    const vault = this.app.vault;
    const anyFile = vault.getFiles()[0];
    if (!anyFile) throw new Error("Vault is empty");
    const TFileConstructor = Object.getPrototypeOf(anyFile).constructor;
    const fakeFile = new TFileConstructor(vault, path);
    fakeFile.deleted = false;
    vault.fileMap[path] = fakeFile;
    return fakeFile;
  }
  // 从 vault.fileMap 中移除假文件
  removeFakeTFile(path) {
    delete this.app.vault.fileMap[path];
  }
  // ========== 元数据缓存 ==========
  // 为标注文件注入原笔记的元数据缓存
  injectMetadataCache(annotationPath, originalPath, fakeTFile) {
    const cacheInternal = this.app.metadataCache;
    const originalCache = cacheInternal.metadataCache[originalPath];
    if (originalCache) {
      cacheInternal.metadataCache[annotationPath] = originalCache;
    }
    const originalFileCache = cacheInternal.fileCache[originalPath];
    if (originalFileCache) {
      cacheInternal.fileCache[annotationPath] = originalFileCache;
    }
    if (originalCache) {
      this.app.metadataCache.trigger("changed", fakeTFile, "", originalCache);
    }
  }
  removeMetadataCache(annotationPath) {
    const cacheInternal = this.app.metadataCache;
    delete cacheInternal.metadataCache[annotationPath];
    delete cacheInternal.fileCache[annotationPath];
  }
  // 注册元数据缓存相关的全局事件监听
  registerCacheListeners() {
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor, info) => {
        var _a;
        const filePath = (_a = info.file) == null ? void 0 : _a.path;
        if (!filePath) return;
        const originalPath = this.getOriginalPathByAnnotationPath(filePath);
        if (originalPath) {
          this.injectMetadataCache(filePath, originalPath, info.file);
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        for (const [originalPath, annotationPath] of this.activeAnnotationSessions) {
          let isStillOpen = false;
          this.app.workspace.iterateAllLeaves((l) => {
            var _a, _b;
            if (((_b = (_a = l.view) == null ? void 0 : _a.file) == null ? void 0 : _b.path) === annotationPath) {
              isStillOpen = true;
            }
          });
          if (!isStillOpen) {
            this.removeFakeTFile(annotationPath);
            this.removeMetadataCache(annotationPath);
            this.activeAnnotationSessions.delete(originalPath);
            this.annotationListPanel.hide();
          }
        }
      })
    );
  }
  // ========== 视图切换 ==========
  getSavedScroll(leaf) {
    var _a;
    const view = leaf == null ? void 0 : leaf.view;
    if ((_a = view == null ? void 0 : view.currentMode) == null ? void 0 : _a.getScroll) {
      const scroll = view.currentMode.getScroll();
      return typeof scroll === "number" ? scroll : 0;
    }
    return 0;
  }
  restoreScroll(leaf, scroll) {
    if (!scroll) return;
    const view = leaf == null ? void 0 : leaf.view;
    if (view == null ? void 0 : view.setEphemeralState) {
      view.setEphemeralState({ scroll });
    }
  }
  getOriginalPathByAnnotationPath(annotationPath) {
    for (const [originalPath, aPath] of this.activeAnnotationSessions) {
      if (aPath === annotationPath) return originalPath;
    }
    return null;
  }
  // 获取当前标注视图对应的原始笔记路径
  getActiveAnnotationNotePath() {
    var _a;
    const leaf = this.app.workspace.activeLeaf;
    if (!leaf) return null;
    const currentFile = (_a = leaf.view) == null ? void 0 : _a.file;
    if (!currentFile) return null;
    return this.getOriginalPathByAnnotationPath(currentFile.path);
  }
  async toggleAnnotationView() {
    var _a;
    const leaf = this.app.workspace.activeLeaf;
    if (!leaf) return;
    const currentFile = (_a = leaf.view) == null ? void 0 : _a.file;
    if (!currentFile) {
      new import_obsidian6.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u4EF6");
      return;
    }
    const originalPath = this.getOriginalPathByAnnotationPath(currentFile.path);
    if (originalPath) {
      await this.closeAnnotationView(leaf, originalPath);
    } else if (currentFile.extension === "md") {
      await this.openAnnotationView(leaf, currentFile.path);
    }
  }
  async openAnnotationView(leaf, notePath) {
    var _a, _b;
    const savedScroll = this.getSavedScroll(leaf);
    const ok = await this.fileManager.ensureAnnotationFile(notePath);
    if (!ok) {
      new import_obsidian6.Notice("\u6807\u6CE8\u6587\u4EF6\u521B\u5EFA\u5931\u8D25");
      return;
    }
    const annotationPath = (0, import_obsidian6.normalizePath)(this.fileManager.getAnnotationFilePath(notePath));
    console.log("[\u6807\u6CE8] annotationPath:", annotationPath);
    const fakeTFile = this.createFakeTFile(annotationPath);
    this.activeAnnotationSessions.set(notePath, annotationPath);
    try {
      this.injectMetadataCache(annotationPath, notePath, fakeTFile);
      await leaf.openFile(fakeTFile, { state: { mode: "preview" } });
      console.log("[\u6807\u6CE8] openFile \u5B8C\u6210, \u5F53\u524D view:", (_b = (_a = leaf.view) == null ? void 0 : _a.constructor) == null ? void 0 : _b.name);
      if (savedScroll) {
        requestAnimationFrame(() => {
          requestAnimationFrame(() => this.restoreScroll(leaf, savedScroll));
        });
      }
      this.setupAnnotationListPanel(notePath);
    } catch (e) {
      console.error("[\u6807\u6CE8] openFile \u5931\u8D25:", e);
      new import_obsidian6.Notice("\u6253\u5F00\u6807\u6CE8\u6587\u4EF6\u5931\u8D25: " + e);
    }
  }
  async closeAnnotationView(leaf, originalPath) {
    const savedScroll = this.getSavedScroll(leaf);
    const annotationPath = this.activeAnnotationSessions.get(originalPath);
    const originalFile = this.app.vault.getAbstractFileByPath(originalPath);
    if (!(originalFile instanceof import_obsidian6.TFile)) {
      new import_obsidian6.Notice("\u539F\u59CB\u6587\u4EF6\u4E0D\u5B58\u5728");
      if (annotationPath) {
        this.removeFakeTFile(annotationPath);
        this.removeMetadataCache(annotationPath);
      }
      this.activeAnnotationSessions.delete(originalPath);
      return;
    }
    await leaf.openFile(originalFile);
    if (annotationPath) {
      this.removeFakeTFile(annotationPath);
      this.removeMetadataCache(annotationPath);
    }
    this.activeAnnotationSessions.delete(originalPath);
    this.selectionMenu.hide();
    this.annotationMenu.hide();
    this.annotationListPanel.hide();
    if (savedScroll) {
      requestAnimationFrame(() => {
        requestAnimationFrame(() => this.restoreScroll(leaf, savedScroll));
      });
    }
  }
  // ========== 标注交互事件 ==========
  // 注册标注视图中的鼠标事件（选区检测、标注点击）
  registerAnnotationInteraction() {
    this.registerDomEvent(document, "mouseup", (e) => {
      const notePath = this.getActiveAnnotationNotePath();
      if (!notePath) return;
      const target = e.target;
      if (target.closest(".annotation-card-menu, .modal-container")) return;
      if (target.closest("input, textarea")) return;
      setTimeout(() => {
        var _a;
        const selection = window.getSelection();
        if (!selection || selection.isCollapsed) return;
        const context = extractSelectionContext(selection);
        if (!context || !context.text) return;
        const range = selection.getRangeAt(0);
        const startEl = range.startContainer instanceof HTMLElement ? range.startContainer : range.startContainer.parentElement;
        const endEl = range.endContainer instanceof HTMLElement ? range.endContainer : range.endContainer.parentElement;
        const startLineInfo = startEl ? this.findSectionLineInfo(startEl) : void 0;
        const endLineInfo = endEl ? this.findSectionLineInfo(endEl) : void 0;
        const lineStart = startLineInfo == null ? void 0 : startLineInfo.lineStart;
        const lineEnd = (_a = endLineInfo == null ? void 0 : endLineInfo.lineEnd) != null ? _a : startLineInfo == null ? void 0 : startLineInfo.lineEnd;
        const isCrossSection = (startLineInfo == null ? void 0 : startLineInfo.sectionEl) !== (endLineInfo == null ? void 0 : endLineInfo.sectionEl);
        const sectionEl = startLineInfo == null ? void 0 : startLineInfo.sectionEl;
        const offset = sectionEl && !isCrossSection ? calculateOffsetInBlock(range, sectionEl) : 0;
        const sectionText = !isCrossSection ? (sectionEl == null ? void 0 : sectionEl.textContent) || "" : "";
        const occurrence = !isCrossSection ? countOccurrenceIndex(sectionText, context.text, offset) : void 0;
        this.annotationMenu.hide();
        this.selectionMenu.show({
          x: e.clientX,
          y: e.clientY,
          selectedText: context.text,
          contextBefore: context.contextBefore,
          contextAfter: context.contextAfter,
          notePath,
          startLine: lineStart,
          endLine: lineEnd,
          occurrence,
          onAdd: () => this.refreshAnnotationView(notePath)
        });
      }, 10);
    });
    this.registerDomEvent(document, "click", (e) => {
      var _a, _b, _c;
      const notePath = this.getActiveAnnotationNotePath();
      if (!notePath) return;
      const target = e.target;
      const markEl = target.closest("mark[data-annotation-id]");
      if (!markEl) return;
      e.preventDefault();
      e.stopPropagation();
      const annotationIds = [];
      let currentEl = markEl;
      while (currentEl) {
        const id = (_a = currentEl.getAttribute) == null ? void 0 : _a.call(currentEl, "data-annotation-id");
        if (id && !annotationIds.includes(id)) {
          annotationIds.push(id);
        }
        currentEl = (_c = (_b = currentEl.parentElement) == null ? void 0 : _b.closest("mark[data-annotation-id]")) != null ? _c : null;
      }
      this.fileManager.getAnnotations(notePath).then((annotations) => {
        this.selectionMenu.hide();
        if (annotationIds.length === 1) {
          const annotation = annotations.find((a) => a.id === annotationIds[0]);
          if (!annotation) return;
          this.annotationMenu.show({
            x: e.clientX,
            y: e.clientY,
            annotation,
            notePath,
            onUpdate: () => this.refreshAnnotationView(notePath)
          });
        } else {
          const annotation = annotations.find((a) => a.id === annotationIds[0]);
          if (!annotation) return;
          this.annotationMenu.show({
            x: e.clientX,
            y: e.clientY,
            annotation,
            notePath,
            onUpdate: () => this.refreshAnnotationView(notePath)
          });
        }
      });
    });
  }
  // 设置标注列表面板
  setupAnnotationListPanel(notePath) {
    this.annotationListPanel.show({
      notePath,
      onUpdate: () => this.refreshAnnotationView(notePath)
    });
  }
  // 刷新标注视图（标注增删改后调用）
  // 通过 ReadViewRenderer.set() 直接更新渲染器文本并触发重渲染
  async refreshAnnotationView(notePath) {
    const leaf = this.app.workspace.activeLeaf;
    if (!leaf) return;
    const view = leaf.view;
    if (!view.previewMode) return;
    const content = await this.fileManager.readAnnotationFile(notePath);
    const renderer = view.previewMode.renderer;
    if (renderer && typeof renderer.set === "function") {
      renderer.set(content);
    }
    this.annotationListPanel.refresh();
  }
  // ========== Section 行号捕获 ==========
  // 注册 MarkdownPostProcessor，捕获每个 section 的行号信息
  registerSectionLineCapture() {
    this.registerMarkdownPostProcessor((el, ctx) => {
      const sectionInfo = ctx.getSectionInfo(el);
      if (sectionInfo) {
        this.sectionLineMap.set(el, {
          lineStart: sectionInfo.lineStart,
          lineEnd: sectionInfo.lineEnd
        });
      }
    });
  }
  // 从 DOM 元素向上查找最近的 sectionLineMap 条目（同时返回 section 元素）
  findSectionLineInfo(el) {
    let current = el;
    while (current) {
      const info = this.sectionLineMap.get(current);
      if (info) return { ...info, sectionEl: current };
      current = current.parentElement;
    }
    return null;
  }
  // ========== 事件和命令 ==========
  registerEvents() {
    this.registerEvent(
      this.app.vault.on("rename", async (file, oldPath) => {
        if (file instanceof import_obsidian6.TFile && file.extension === "md") {
          try {
            await this.fileManager.migrateAnnotationFile(oldPath, file.path);
          } catch (e) {
            console.error("\u8FC1\u79FB\u6807\u6CE8\u6587\u4EF6\u5931\u8D25:", e);
          }
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", async (file) => {
        if (file instanceof import_obsidian6.TFile && file.extension === "md") {
          try {
            await this.fileManager.deleteAnnotationFile(file.path);
          } catch (e) {
            console.error("\u5220\u9664\u6807\u6CE8\u6587\u4EF6\u5931\u8D25:", e);
          }
        }
      })
    );
  }
  registerCommands() {
    this.addCommand({
      id: "toggle-annotation-view",
      name: "\u5207\u6362\u6807\u6CE8\u89C6\u56FE",
      checkCallback: (checking) => {
        var _a;
        const leaf = this.app.workspace.activeLeaf;
        if (!leaf) return false;
        const file = (_a = leaf.view) == null ? void 0 : _a.file;
        if (!file || file.extension !== "md") return false;
        if (!checking) {
          this.toggleAnnotationView();
        }
        return true;
      }
    });
  }
};
function countOccurrenceIndex(text, searchText, offset) {
  const positions = [];
  let pos = 0;
  while (true) {
    const idx = text.indexOf(searchText, pos);
    if (idx < 0) break;
    positions.push(idx);
    pos = idx + 1;
  }
  if (positions.length === 0) return 0;
  let bestIdx = 0;
  let bestDist = Math.abs(positions[0] - offset);
  for (let i = 1; i < positions.length; i++) {
    const dist = Math.abs(positions[i] - offset);
    if (dist < bestDist) {
      bestDist = dist;
      bestIdx = i;
    }
  }
  return bestIdx;
}
